### ISSUE TITLE
weighted contents/folders

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/pyBRAT#10]
@philipbaileynar I am trying to add weights to the some of the contents in this pyBRAT repo.  I have given Vision weight one and it is at the top of the summary on the side.  If I understood our conversation yesterday I needed to change the title of my "summary.md" page in the Documentation folder to "index.md" and it should make the folder also a link like the example ThingsA in the Template Docs.  I am not sure if it is taking longer than normal to show these changes on [http://brat.riverscapes.xyz/](http://brat.riverscapes.xyz/) or if I have done something incorrectly.  Let me know if you can figure out what is going on. 
Part 2 of my question is then to assign a weight to a folder do I then add the weight in the index file of the subfolders?  
Let me know if my question is clear or if it would be easier to get on a gotomeeting again.

**Comment by philipbaileynar** [comment]
The theme updates that we reviewed yesterday have not been applied to the pyBRAT repo yet. I will do this later today (and use this process to write the documentation so that you can reproduce the new theme features on other sites).

**Comment by philipbaileynar** [comment]
I've just updated the theme on this repo to reflect the changes that we discussed on Monday. Please reload this site to see the changes. I will now switch gears and document how to implement this theme on other sites.

**Comment by lhaycock** [comment]
Thanks @philipbaileynar  looks like it just needed a day to refresh.  Adding the weight to the index page in each sub-folder did the trick
