### ISSUE TITLE
Run BRAT for Red Rock Canyon for 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#100]
Popo Agie HUC 8
As of 4/10/18 we have no data on this (this is outside the Green River Basin BRAT)
**Task:** we need to run BRAT and R-CAT for this watershed. (With Riverscapes compliant structured outputs- Mic’s Templates) (@Albonicomt is tasked with this one)
- [x] BRAT
- [x] RCAT
@Albonicomt use A40921 for this. Please post progress here.

**Comment by joewheaton** [comment]
All transfered across from @wally-mac 's notes: https://docs.google.com/document/d/1wleLImeBnRc2ldYXDqDid_N2YLpArcIiNQrTWMJSa4U/edit?ts=5b1016e7#

**Comment by Albonicomt** [comment]
Sounds good! I am on it.

**Comment by wally-mac** [comment]
@Albonicomt how is this coming along? Please have @CHafen made the summary products.  Thanks

**Comment by Albonicomt** [comment]
@wally-mac, It's coming along. I can send out the RCAT outputs to @CHafen. Still working on BRAT for the area. Looking for some regression equations.

**Comment by CHafen** [comment]
RCAT summary products are done and on Box.
[https://usu.app.box.com/folder/36487271761](url)

**Comment by Albonicomt** [comment]
Hey @CHafen here is the link to the BRAT outputs for Popo Agie. I am sharing the Layer package, so you won't have to find the symbologies. https://usu.box.com/s/hy0hhjc9y40947s9w4r1bmkh9ovfj35c

**Comment by joewheaton** [comment]
Thanks @CHafen for pretty maps and @Albonicomt for running the models. FYI to both, this is fine for what I need (so I'm closing this), but I'm going to provide some comments in new tickets and refer back to this and use this as example. Some of these comments will be aimed at @Albonicomt and @CHafen for what I'd like to see in our 'default' Atlas and cartography. Some of this will be more aimed at @banderson1618 for how to change default symbology.... Stay tuned.
