### ISSUE TITLE
Upper Humboldt HUC 8

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#101]
Workshop is  August 15-16. 
Run 
- [ ] BRAT
- [ ] RCAT
for Upper Humboldt HUC 8
As of 4/10/18 we have no data on this HUC 8

**Task**: we need to run BRAT and R-CAT for this watershed. (With Riverscapes compliant structured outputs- Mic’s Templates) (Scott is tasked with this one).

@sshahverdian please post your updates here on progress and links to files on Box. Bill A40921 for this.

**Comment by joewheaton** [comment]
All transfered across from @wally-mac 's notes: https://docs.google.com/document/d/1wleLImeBnRc2ldYXDqDid_N2YLpArcIiNQrTWMJSa4U/edit?ts=5b1016e7#

**Comment by sshahverdian** [comment]
@joewheaton @wally-mac @Albonicomt @MatthewMeier 
I have put all the data required for BRAT and RCAT for the Upper Humboldt (16040101) on Box at: 

https://usu.app.box.com/folder/49363840253

I have been having some trouble with VBET - long processing time (12 hrs), unit conversions in the tool (from pixels to sq km), and excessively long (i.e., prohibitively long) delays when attempting to manually edit the valley bottoms.

I have outlined everything that has been done and more details on the troubleshooting in the Read Me .docx on Box - see for more details. I need some help with figuring out what is taking causing VBET such delays. My only guess is that the network is so large (nothing has been removed from the NHD flowline data).

**Comment by joewheaton** [comment]
@sshahverdian thanks for the update. For your own sake, it would be nice to have that run for your upcoming visit. Keep posting helpful comments like this as you make progress...

Perhaps talk to @MatthewMeier and/or @bangen about the VBET stuff. Maybe move your [Read Me](https://usu.app.box.com/file/302553130635) notes about [VBET](http://rcat.riverscapes.xyz/Documentation/Version_1.0/VBET.html) in particular over to a specific new issue in the [RCAT forum](https://github.com/Riverscapes/RCAT/issues?q=is%3Aopen+is%3Aissue) (as VBET is now part of RCAT)...  that forum has not seen as much traffic as here simply because we're not actively developing in RCAT, but that is the place to have the conversation.  Post with  a 'Question' label and use @ mention to direct question.

**Comment by wally-mac** [comment]
@sshahverdian were you able to resolve your VBET issues? What's the current status? How can we help?

**Comment by wally-mac** [comment]
@sshahverdian what's the status here? I recall that you needed help with the floodplain connectivity step of RCA and that @Albonicomt was going to do this. Is this correct?

**Comment by Albonicomt** [comment]
@wally-mac, I believe this is correct. @sshahverdian Send me a link to the data and I will get to work on it.

**Comment by sshahverdian** [comment]
@Albonicomt here is the data for the upper humboldt. Shout if you need anything else.
https://usu.app.box.com/folder/51479650645

**Comment by Albonicomt** [comment]
@sshahverdian Thanks. Do you also want me to go ahead and just run RCA after I finish up the FP Connectivity layer?
