### ISSUE TITLE
Bear River Range & Wellsvilles Updated BRAT outputs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#102]
We are teaching an [NRCS Workshop](http://beaver.joewheaton.org/nrcs---utah.html) here in Logan September 11-12. We will do field work up Logan Canyon, Station Creek (ID) and Birch Creek (ID), and Three Mile Creek (UT Wellsvilles). We have various flavors of RCAT and BRAT outputs for all of these, but we need to update them all and make them Riverscapes Compliant with the new projects structure and layer packages (ask @Albonicomt for details) 
- [ ] BRAT
- [ ]  RCAT

@MatthewMeier use A40921 for this. Please post progress here and updates to Box.

**Comment by MatthewMeier** [comment]
Will do

**Comment by MatthewMeier** [comment]
These outputs were completed and can be found on box.
