### ISSUE TITLE
Idaho BRAT Meeting Update

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#103]
We met on June 22 after the [Hailey, ID NRCS Workshop](http://beaver.joewheaton.org/nrcs---idaho.html).

In attendance were:
- Cory Mosby (IDFG)
- Joe Wheaton (USU)
- Nick Bouwes (USU)
- Terry Gregory (IDFG)
- Chris Yarborough (IDFG)
- Dave Weskamp (TNC)
- Lee Maybe (USFS - Representing the GYA BRAT effort too)

We talked about the datasets folks had on beaver activity, dam locations and translocations. We also talked about ideas folks had for how BRAT could be used and to start thinking about where to highlight some case study examples.

**Comment by wally-mac** [comment]
Yes, I agree. I think it's worth breaking it out by the regions like we did for Utah.

**Comment by wally-mac** [comment]
@mhallerud and @bangen like we did for the Utah BRAT found [here](https://usu.box.com/s/3jqr3d61cnvd9wq5dl7bkzhw6aox8t96) we'll want to clip & summarize BRAT data by the IDF&G Administrative Regions found [here](https://usu.box.com/s/lwyke9289s0q4ou1qjmgchkj0bes5rdu).  For TNC and GYA BRAT we'll want to use similar regions to clip and summarize data.  We can take about options. Note also that for Utah we clipped BRAT data to the USGS Geohydrologic Regions and we should do the same for Idaho, TNC, and GYA.  Could we batch process by the USGS Geohydrologic Regions or are they too large?

**Comment by wally-mac** [comment]
What probably makes the most sense for the GYE BRAT is to clip by US Forest Service boundaries (because this is USFS funded). Sara you might already have an idea for TNC.

**Comment by mhallerud** [comment]
@wally-mac Sounds good. Do you know where I could find said boundaries for GYE? I don't see why BRAT couldn't be run at these larger spatial scales, but I think we should try a test run before we go any further with that idea. Like @wally-mac mentioned previously, it might give large cumulative values for drainage area that will affect other outputs down the line. @banderson1618 @bangen, what are your thoughts on running BRAT at a larger scale?
