### ISSUE TITLE
Data Capture Event - Lets start playing

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#104]
Lets start working on process of getting Survey123 or WebGIS Apps or maybe just something simpler ready as platform to ingest some of this old IDFG data into BRAT Riverscapes Project as data capture events.  See #103 for context from Cory. We need to get these ingested in as shapefiles as 'Data Capture' events on dam locations, colony locations, and beaver activity stuff.  

For now, see data in XLS formats:
- [ ] From Region 1: https://usu.app.box.com/file/302400035111
- [ ] From Region 4: https://usu.app.box.com/file/302391320476
  - [ ] From Rock Creek: https://usu.app.box.com/folder/49360296877
- [ ] From Region 7: https://usu.app.box.com/file/302400108319

We'll want to house these in inputs folder as described in #31 and then figure out subsequent intermediate analyses and visualizations. For example:
- map of where dams or dam complexes are, 
- map of calculated actual dam density, 
- comparison of actual dam density to modeled dam density to show additional available capacity (i.e. more dams)... 

This will necessarily be a little exploratory but we need to start somewhere.

Post updates as you make them...  grabhelp from @bangen  or @Albonicomt for ideas on how to display things.

**Comment by wally-mac** [comment]
@chadFHC, can you please look into this. Thanks!

**Comment by joewheaton** [comment]
Where we at on this @wally-mac and @chadFHC. If we need more specific requests, lets close this and do it.
