### ISSUE TITLE
We need a tracking sheet for Survey123 Apps

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#105]
In the same way you guys made that handy Google Sheet for the Dam Census Web App (https://docs.google.com/spreadsheets/d/14EXBvLc6VscY6m48O3hVYDC_1jIYMVe-Tny02BQNkNI/edit?ts=5b3527a5#gid=644297276), we need one for the Survey123 Apps (probably seperate for all our projects).  @chadFHC and @bangen can you get this sorted out? 
- [ ] Idaho BRAT
- [ ] TNC BRAT
- [ ] John Day & Powder Basin BRAT
- [ ] GYA BRAT

@chadFHC we'll need to finish up the tweaks to Data Capture apps (I think we primarily want to rely on a mix of Simple BRAT, Advanced BRAT, Simple Dam Complex, and Advanced Dam Complex forms... Maybe we can start another issue and tweak those as needed and get those set up for each of these projects. We can wait until @wally-mac returns to set milestone(s) for this... I'm just logging this now.

**Comment by bangen** [comment]
@joewheaton I'm a little unclear on what the Survey123 app tracking spreadsheet should have.  Is this a row for each HUC in the project area or a row for each project?  Let me know and I'll put it together.

**Comment by joewheaton** [comment]
We need to have a place where we can access the URLs for every Survey123 BRAT and BeaverDam traciking Apps we have, as well as where on box to access data and any WebViewer of that.... So each row represents a different Survey123 Data Collection App and associated 'stuff'. Maybe something like:

| Project | Type | Survey123 Data Collection App URL | Survey123 Web View of Collected Data URL | Data on Box | Status | 
|--- |--- |--- |--- |--- | --- | 
| TNC Sierra Nevada BRAT| BRAT-Advanced | [Link](https://survey123.arcgis.com/share/f1c37b80ba3f482fbadb38251c5d7a7f?open=menu) | Survey123 Web View of Collected Data URL | NA | Preliminary - Data Collection in Progress |

**Comment by wally-mac** [comment]
@chadFHC @bangen have we made any progress on this? What's the status? How can I help? Thanks!

**Comment by chadFHC** [comment]
@wally-mac 
Joe mentioned that we could wait until you return to set milestones for the tweaks on the data capture apps, so I've actually been waiting for that. I'm not %100 sure what needs to be done to them.

**Comment by wally-mac** [comment]
@chadFHC , let's work on this on Friday when we meet.

**Comment by chadFHC** [comment]
@wally-mac Sounds good.

**Comment by wally-mac** [comment]
@chadFHC as we discussed today we are now set to have you work on this.  Please coordinate with @webernick79 and @joewheaton.
