### ISSUE TITLE
Beaver Bottom - UpperBaver (Birch Creek) BRAT and RCAT

### ISSUE THREAD

**Issue by Albonicomt** [Riverscapes/pyBRAT#106]
Hey Team, @bangen @MatthewMeier @wally-mac @sshahverdian @joewheaton @banderson1618 
I have been trying to complete this BRAT run of the Huc 8 "Beaver Bottom-Upper Beaver" today which contains Birch Creek, Utah. Unfortunately as some of you know, I will not have time to work on this for the next three days (July 5-7). I will be available to work on this task on the 8th and 9th, but I will be out of the country from July 10th - 18th and will not be available during this time. 
I have all the components of this run completed except for the Braid editing and the Maximum Drainage area. This watershed just needs to be run through the BRAT project. The LANDFIRE data (EVT and BPS) are both coded, and I have regression equations here in the metadata: https://usu.box.com/s/9e62k8qtf6e9gixxxrkueyskw4qdq4d3. Here is a link to all the other data: https://usu.box.com/s/1pj3elgpvfhvjxezd8nl6wx8lg8s3m78

Would someone be willing to help me run this data through the BRAT tool and when I am available on the 8th and 9th, I can complete all the Riverscapes compliant products as well as the summary products?

**Comment by banderson1618** [comment]
I can run this through BRAT, but I'm a bit confused by what you mean by "I have all the components of this run completed except for the Braid editing and the Maximum Drainage area", specifically the Braid editing part. Do you mean you haven't given the stream an IsMainstem value?

I also wouldn't know how to identify a proper maximum drainage area value, so maybe I'm not the best one for the job.

**Comment by banderson1618** [comment]
Thanks @MatthewMeier for answering my questions in a phone call just now. I'll run the tool, and upload the results to Box and post a link here.

**Comment by banderson1618** [comment]
@MatthewMeier and @Albonicomt, the tool is hanging up at where it's adding Land Use data. I'm using the land use raster at the location [here](https://usu.app.box.com/folder/50945051327), but I'm not sure if that should work. Is there some editing that I need to do before running it?

**Comment by MatthewMeier** [comment]
@banderson1618 
It looks to me like you are missing some of the fields that are a product of the "LANDFIRE_LUCode.py" script namely the "CODE" and "LUI_Class" fields. I would try running that script again and see where that takes you.

**Comment by banderson1618** [comment]
@MatthewMeier 
I ran the script and tried again, and the same thing happened. I did some debugging, and I figured out the section of code that's going wrong.

For some reason, the call to zonalStatsWithinBuffer on line #578 in the BRAT Table tool  (link [here](https://github.com/Riverscapes/pyBRAT/blob/717120b71285a0ea5c455670b113b2879883f024/BRAT_table.py#L578)) is causing the tool to go into an infinite loop. The while len(needStatList) > 0 loop on line 208 never ends. I don't know enough about the code to spot a quick fix, but I'll dig into it first thing on Monday. @bangen, I figured you should know about this issue. If there's something quick and easy that you spot, let me know.

**Comment by Albonicomt** [comment]
@banderson1618 , I did a little reprocessing on the EVT and was able to get passed the LUI error you were getting. Try using this EVT_raster instead: https://usu.box.com/s/xxfr70f21g5ohpmtl8dsywxbx40otsig

Unfortunately, Now the tool is getting stuck on the Canals. 
![brat_error](https://user-images.githubusercontent.com/39168968/42473846-f6701296-8382-11e8-8911-71845c747db8.PNG)

**Comment by banderson1618** [comment]
That's not it getting stuck on canals, specifically. That's in the code that's supposed to mark reaches as braided or not. There might be a bug in the code that's trying to avoid marking canals as braided. I'll look into why that's going wrong and let you know if I get through it.

**Comment by banderson1618** [comment]
I ran it on my 10.6 version of ArcGIS, and I didn't have that problem, but I did get that error when I ran it on an installation of 10.5. Looks like it might be a version issue. I'll look into it some more.
