### ISSUE TITLE
pyBRAT's code could be more modular

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#108]
In my conversation with @MattReimer in #95, he mentioned that code needs to be in discrete units to be effectively unit tested. Unfortunately, a lot of pyBRAT's code isn't very modular at the moment. Breaking code into more functions would improve readability, make modifying the code easier in the future, and make it easier to reuse code, as well as making it more testable. This issue is meant to be a place to put commits that break pyBRAT code into more functions, so that those improvements are easier to track.

**Comment by MattReimer** [comment]
Old issue with no actions. Closing.
