### ISSUE TITLE
adding hyperlinks to other sites in subfolders

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/pyBRAT#11]
@philipbaileynar How can I add a link to [Escalante Pilot Project](http://etal.joewheaton.org/projects/past-projects/gct-pilot-study-testing-the-beaver-restoration-assessment-tool-brat) in the Documentation subfolder?  ( Or any other links that are *not* pages in the pyBRAT repo?)

**Comment by philipbaileynar** [comment]
Do you mean in markdown? Simply use the full, absolute HTML ref, that starts with HTTP, like this:

```
blah blah [link text here](http://etal.joewheaton.org/projects/past-projects/gct-pilot-study-testing-the-beaver-restoration-assessment-tool-brat)
```

Make sense? Am I missing something?

**Comment by lhaycock** [comment]
@philipbaileynar what shows up in the sidebar of the webpages is basically the structure of what is in folders/sub-folders.  So files that are saved in sub-folders will show up in the side bar.  How would I add a link to another page not within the repo as in the example I listed above?

**Comment by philipbaileynar** [comment]
That is not possible. Options:

1) add the link in the "useful links" section that can be turned on and
appears below the site table of contents. See the Jekyll documentation for
instructions.

2) create a page for the external link with the front matter title that
will appear in the site table of contents. The page should just have a
sentence or two about the project, perhaps a thumbnail, then the link.

Sorry but this is the best we can do.

Pb
