### ISSUE TITLE
zonalStatisticsWithinBuffer() sometimes gets stuck in an infinite loop

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#112]
The loop starting on line 208 of the BRAT Table Tool will sometimes get stuck in an infinite loop. This goes back to the section where the variable "stat" is calculated. For some reason, in cases where there is an infinite loop, the table that is calculated is empty. Because nothing is calculated, nothing is removed, and so the loop's break condition is never triggered.

I can implement a workaround, where if the loop iterates, say, 10 times without progress, the loop breaks, a warning shows the user the reaches that didn't get a value, and the remaining objects are given 0 as their value. That's not a great long term solution, though. Ideally we could figure out why this isn't working, and fix it permanently. I have a feeling that the problem is in the "Select Layer by Attribute" call, but I can't say for sure, because I haven't figured out a good way to test it.

@bangen, because you wrote this part of the code, it would be good to have a conversation about why the loop is necessary. If we could implement it as a for loop somehow, that would be excellent.

The dataset at this Box link has this error when trying to extract values for max and min elevation: [https://usu.app.box.com/folder/51109950795](https://usu.app.box.com/folder/51109950795). @sshahverdian ran into this issue. I believe he's currently working on making a new DEM, and it would be interesting to know if that DEM ran into the same problem.

**Comment by banderson1618** [comment]
Upon investigating the ReachIDs pulled out by the workaround, it looks like this issue is caused by reaches that are hanging off the DEM. We haven't had a chance to exhaustively check that that's the problem, but it makes sense. If that's the problem, then my workaround may be all that we can do. The important thing is that the tool isn't stuck in infinite loops, so if we avoid that, then I'm happy.

**Comment by wally-mac** [comment]
In talking to @sshahverdian this error was the result of NHD streamlines extending beyound the watershed boundary (an obvious input data error).  @banderson1618, perhaps the error message could be more specific so the user has more information on what has caused the error.

**Comment by banderson1618** [comment]
The one concern I have with a more detailed error message is that this error might not always come from the NHD hanging off the raster. For example, I could see this error popping up if the datasets didn't have the same projection. If that was the problem, then a more detailed error message could be a red herring.

Maybe we could use the "FAQ" idea we were talking about yesterday. We could make a page called "Troubleshooting BRAT" on the GitHub page, and have different categories for different error messages. Each category would have a series of recommended troubleshooting steps, things to look for, stuff like that. The error message might include something like "For more information, go to this link: www.somepage.com"

**Comment by wally-mac** [comment]
Good point.  I like the idea of having a URL that provides more information.
