### ISSUE TITLE
Lets nest and ship the BRAT layer package with a Context layer underneath....

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#113]
Can we please add the context WMS and WMST to the layer package. I think it should include:
- NAIP imagery
- HR state imagery if available
- Contours
- WBD (HUC)
- USGS Shaded Relief

Example: https://usu.box.com/s/gb1frqe967ydgd31a9wupcpj6ajqu5fp

We should be shipping this as part of Layer Package output. Perhaps we could ask @Albonicomt and @bangen what they like.

**Comment by wally-mac** [comment]
@banderson1618 are you working on this? Do you have questions or issues?

**Comment by wally-mac** [comment]
I think it pretty high priority.  @chadFHC, might have some insights on this. ArcGIS Pro makes this pretty easy to do.

**Comment by joewheaton** [comment]
![usgs](https://user-images.githubusercontent.com/9723905/43102359-25d82ec8-8e88-11e8-844b-1ac8bffd7756.png)
Some thoughts for context layer packages. Should we just include all the [USGS National Map Basemap services](https://viewer.nationalmap.gov/services/)?

**Comment by wally-mac** [comment]
I've noticed that the contour layer does not show up and the NAIP imagery is hit or miss. @Albonicomt can you please look into this.

**Comment by joewheaton** [comment]
I tried to figure out what was going on with that contour layer and could not. As long as we have the USGS 7.5 minute quad (i.e. USGS Topo Base Map layer) WMTS on, I think we're good. Here's a rambling video showing what I want: https://youtu.be/we7_mS1jxy8

In short,  same as what we said above but please place it in Layer Packages of both BRAT and RCAT below the Inputs, Intermediates and Outputs...

WE should also package it up by itself and show people how to use it in a boring video and then make a page on our website for how to use those.

**Comment by joewheaton** [comment]
And here's that layer package: https://usuonline.maps.arcgis.com/home/item.html?id=cc98d377218a43728c403b57133ac0fa

**Comment by Albonicomt** [comment]
Sounds good @joewheaton. I will get to this today.

**Comment by Albonicomt** [comment]
Another option @joewheaton, in case the contour map from the USGS keeps giving us trouble, is to create a contour layer from the DEM. @banderson1618, if we do this, would it be easy to include this step in the Layerpackage builder? If we do this, we can control the contour intervals and potentially have multiple contour layers at different intervals, which might be nice.

**Comment by banderson1618** [comment]
If we can automatically create the contour layer, we should be able to make a layer out of it. Once we have that, including it in the layer package would be pretty easy, I think.

**Comment by joewheaton** [comment]
Hi Folks,
Good ideas for work arounds. Lets not worry about the contour layer. Its redundant with the USTopo Map base layer that shows contours anyway.  I'm going to close this one down as @banderson1618 has already made the first version of the layer package, the contour issues is moot, and I started new thread to deal with this (#134)...
