### ISSUE TITLE
Layer Package Outputs Missing some Input Layers

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#114]
I'm just reviewing #97 for Scott and Salmon and while overall things look good, the outputs in the layer packages for both are missing all the inputs at bottom of tree:
![2018-07-11_084156](https://user-images.githubusercontent.com/9723905/42583681-58f79268-84e6-11e8-8a09-07a36bb66f1b.png)

It looks like inputs are in BRAT project, but not getting properly output. Namely, the childeren of the following layer groups in `Inputs` are empty:

- Topography
- Landuse
- Vegetation

are all missing. The bug should be fixed, and if possible the new layer package spit out. If we don't have enough time, @kbartelt can you please just update the layer package file manually so it includes all those layers. Maybe @banderson1618 can help figure it out? Thanks guys!

**Comment by banderson1618** [comment]
My guess is that the layers either weren't generated during the running of the tool, or that there was something weird about the folder structure that lead to the tool not finding them. Can the person who ran the tool (@kbartelt, I assume) send me either a zip file of the project folder, or a screen shot of the folder with every folder expanded out, so I can investigate the inputs?

**Comment by kbartelt** [comment]
@banderson1618 when I re-download the layer package from box I am able to see the mentioned input layers, so maybe it is something with my folder structure.. I just sent you an email with a zip file of the project folder for both watersheds. Thanks for the help.

![image](https://user-images.githubusercontent.com/39836333/42585030-cd674df4-84f1-11e8-854d-26e0a26d99b9.png)

**Comment by joewheaton** [comment]
Interesting... I just tried downloading again and I have the same problem/result as I originally had. So I'm not sure what's going on. Maybe @banderson1618 or someone else could try downloading just the layer package and see if they have same problem? Thanks. I'm here for about another hour.... Then on road. I don't know my WiFi situation tonight... but I think I will have a spot I can download things again.

**Comment by banderson1618** [comment]
Oddly enough, the layer package seems fine when I download it. I wonder if somehow, there's a dependency on something in the zip file. I deleted everything else in the zip file, and my layer package was still fine, but it's the only difference I can think of. @joewheaton, what version of ArcGIS are you using? I might spin up a virtual machine of that same version and see if it works there.

**Comment by banderson1618** [comment]
A quick update: I tried downloading just the layer packages for the Scott and the Salmon, and they seem to be fine. I'm running ArcGIS 10.6. @kbartelt, what version of ArcGIS are you using?

**Comment by kbartelt** [comment]
I'm using 10.5

**Comment by kbartelt** [comment]
@banderson1618 @wally-mac @bangen @joewheaton I've been using the virtual machine along with Scott for the past few hours trying to figure out any way to manually add the missing inputs to the layer package or recreate the layer package in 10.4 and cannot figure it out. If anyone has any last minute suggestions I will gladly give it a shot. I'm so sorry I couldn't get it to work Joe!

**Comment by wally-mac** [comment]
@kbartelt were you able to resolve this issue? Please advise.

**Comment by kbartelt** [comment]
@wally-mac I still do not know how to resolve the issue. My understanding is that the symbology for the DEM inputs will not work with 10.4. I don't know how to fix this. @banderson1618 Do you know a workaround? Would this be fixed if I re-ran the BRAT start to finish in 10.4?

**Comment by banderson1618** [comment]
@kbartelt, you can add the layers necessary by hand as a workaround. I don't have much experience working with layer packages manually, but I'm pretty sure that @MatthewMeier knows how, and I believe he works in the same office as you? If not him, then Mic definitely know, and I could probably figure it out eventually.

Running through BRAT on 10.4 would probably work, but you'd need to use the latest version of pyBRAT (v3.0.16, or straight from the master branch). I probably wouldn't recommend this, however. Learning to modify a layer package is a useful skill, and it'll be a lot easier to do this in the future if you learn to now.

**Comment by kbartelt** [comment]
Thank you @banderson1618. Do I need to manually add them using 10.4 then?

**Comment by banderson1618** [comment]
Yes, you'd need to make the layers in 10.4, @kbartelt. Sorry, I should have mentioned that. I think @sshahverdian already showed you how to use the virtual machines? I can send you the instructions if not.

**Comment by kbartelt** [comment]
Thank you for the help @banderson1618, that worked.
