### ISSUE TITLE
distance to railroad and canal error

### ISSUE THREAD

**Issue by sshahverdian** [Riverscapes/pyBRAT#118]
I'm getting inaccurate distances to railroads and canals when running the BRAT table tool, which results in erroneously high conflict potential. There are a number of segments that show a 0 value (i.e., a railroad or canal crossing) where there are no railroads or canals nearby.

![railroad_canal_error](https://user-images.githubusercontent.com/21205131/42709502-f117b218-869d-11e8-9afb-2c17b9be6644.png)

@bangen @banderson1618 @wally-mac @joewheaton 

I'm running arc 10.5 and BRAT 3.0.17

**Comment by banderson1618** [comment]
Can you upload the dataset you were using?

**Comment by sshahverdian** [comment]
@banderson1618 Here is the data I used:
https://usu.app.box.com/folder/51251956841

**Comment by banderson1618** [comment]
I just ran it in ArcGIS 10.6, and I didn't get the problem. It's likely a versioning issue. I'm running it on a virtual machine now.

**Comment by banderson1618** [comment]
I ran it in the virtual machine, and... I didn't get the error. Until we figure out how to reproduce this error, I'm going to tentatively put a pin in this issue.
