### ISSUE TITLE
IsBraided? How about IsAnabranched?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#122]
@sshahverdian has a good rant about terminology given we are the Fluvial Habitats Center! @sshahverdian  please rant here and lets update our labels and terminology in source code, attribute tables and outputs!

**Comment by wally-mac** [comment]
Sounds good to me.

**Comment by joewheaton** [comment]
Agreed

**Comment by bangen** [comment]
@wally-mac I'm going to reopen this until the change is implemented so it doesn't fall off our radar.

**Comment by banderson1618** [comment]
Should we rename the tool as well? "Multi Channel Handler", or something like that?
