### ISSUE TITLE
Projects: Focus Area

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#123]
@joewheaton @wally-mac @bangen @banderson1618 
So on my mind lately is with all of us running the full NHD network through BRAT and then wanting to have particular focus areas. Whether it will be a focus pertaining to perennial or within a particular landowner boundary or something else. I feel like it could be beneficial and save time if we included an optional checkbox within the creation of the layer package or a different summary step that would subset/clip the data to that focus area. 
I do not know if this is already in the works but it might be worth it for these large projects that we are doing for TNC and/or Idaho.

**Comment by wally-mac** [comment]
@MatthewMeier , thanks for bringing this up.  @banderson1618 , what are your thoughts on this?

**Comment by joewheaton** [comment]
Great idea @MatthewMeier. This is very similar conceptually to what we added in GCD 7 with a 'Mask Library' in the inputs. The masks become different spatial extents that you might want to summarize any intermediate or output result by. So one thing I'm seeing a ton in the 'Atlas Maps' that @Albonicomt and @CHafen are spitting out so well is they tend do them for the HUC8, which is just our default pyBRAT processing extent. Well, some other really obvious summary extents:
- by land ownership
- by subwatershed
- by management boundaries

In the latest GCD, we've expanded the Mask Library to include polygons of type:
- Area of Interest (a clip for processing or summary extents)
- Standard Mask (where you differentiate summary results by a categorical text field (e.g. land ownership) and then it splits summary results out by each unique category (i.e. budget segregation)
- Directional Mask (a special instance of standard mask where you add a integer topology field that defines the order (e.g. valley bottom segments working downstream) to summarize over.

My advice is that we nail down some of the ways in which we will do verification/validation from data capture, and get the sybology (#134) management model (#133) and conflict models (#16) doing what we want and then when we revisit the summary ouputs, metrics and atlas products we assign this request an enhancement ticket.

In meantime, @banderson1618 can you scope this?
