### ISSUE TITLE
Run BRAT for: Middle Columbia-Hood HUC 8 (17070105) 

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#127]
@chadFHC, we have a small contact to run the Middle Columbia-Hood HUC 8 (17070105) and I'd like to use this as an opportunity for you to get up to speed on the BRAT model.  @sshahverdian has done some of the initial data capture for this when he ran Rock Cr. (the other Rock Cr) near the Wind River.  Please reach out to him and also lean on @kbartelt, @banderson1618 and @MatthewMeier as needed. The index for this is A38321.  @joewheaton I'm adding you to this ticket just so you're keep in the loop.  
Thanks!

**Comment by chadFHC** [comment]
@wally-mac 
Okay, I will work on this.
