### ISSUE TITLE
Segmenting Network Script error

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#130]
@bangen @banderson1618 
I was working on BRAT and when I was getting the network into 300m segments as I was working with the data it is deleting many of the segments that are in the network and creating holes they seem to be segments that are dealing with Fcodes of 42803 and 42800 I am not sure if there are ay other relationships but that was the closest that I could figure. It is not due to the nhd area or water bodies. Anyway I am inclosing the data for you to work through and I am using BRAT 3.0.17 supporting tools but it works fine with 3.0.9. Here is the data...
[hydrography.zip](https://github.com/Riverscapes/pyBRAT/files/2255535/hydrography.zip)

**Comment by bangen** [comment]
@MatthewMeier Those FCODES pertain to pipelines (see full descriptions [here](https://nhd.usgs.gov/userGuide/Robohelpfiles/NHD_User_Guide/Feature_Catalog/Hydrography_Dataset/Complete_FCode_List.htm)).  We absolutely do not want to include pipelines in our BRAT networks even if they create gaps in the overall network.
