### ISSUE TITLE
More changes to  Management Outputs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#133]
So, in #17 Scott proposed some helpful changes to the management outputs. In discussions with our sponsors, collaborators and BRAT stakeholders, I've realized what we need to do is focus less on a synthesized single output for management, and break it apart into smaller, more readily digestible chunks. We focus on demoting the individual chunks to less (potentially controversial) emphasized outputs of the model and just examples of how any BRAT user (of output) might want to combine different lines of evidence to answer specific questions. We emphasize creating specific case studies to illustrate stories. 
![2018-08-03_113538](https://user-images.githubusercontent.com/9723905/43656899-603c9342-9711-11e8-985c-dc578e91f149.png)
That being said, I want to implement very quickly some changes to the management outputs and particularly the layer packages (symbology, word choice and cartography are 95% of what strikes nerves good and bad with folks).  Please see this video and start implementing the requested changes:
https://youtu.be/VGll4Bobigk

The dataset can be found at: https://usuonline.maps.arcgis.com/home/item.html?id=eff3e540db8b4c33a779d683246fe15e

@bangen and @banderson1618  please coordinate on how you want to tackle this.

**Comment by wally-mac** [comment]
@Albonicomt, please also watch Joe's video above and work with @bangen and @banderson1618 on this.

**Comment by bangen** [comment]
@joewheaton I've implemented those changes into the 'new_conflict_model' branch, but need to look over them with you and @wally-mac before we merge them into the master.

**Comment by wally-mac** [comment]
That's great news Sara, I can make myself available for a time that works for @joewheaton.

**Comment by joewheaton** [comment]
So we're talking about, changing Scott's 'management model' to 'Beaver Dam Building Opportunities' - and having two layer outputs of this that break it into 'Unlikely Dam Building' and 'Possible Dam Building'. This differs from the capacity models alone, in that it combines existing, historic and land use intensity. 

We're thinking about a new 'Provisional Management Overlay Generator' (altogether):
This will exist with three levels of interaction:

1.  Only combining the Beaver Dam Opportunities out of the box, with the Anthropogenic Metrics
2. Using (1), and adding in specific human-beaver conflict issues and/or layers (e.g. flooding, clogging, undesirable harvest, etc.) and potentailly tolerance input (dead beaver, beaver can do no wrong, possible problems but 'living w/ beaver') 
3. Using data capture of beaver dams and or beaver conflicts. This allows us to a) pin point actual realized conflicts from plausible... and on b) dams allows us to separate conservation opportunites from restoration.

**Comment by wally-mac** [comment]
@bangen, I came away with the same interpretation as you did "only 'Unlikely Beaver Dam Building Opportunities' if the 'EX' is 'None'.  @sshahverdian and @joewheaton is our assumption correct? Also, what do you think of Sara's concerns that " 'PT' could be higher and I don't think we should discourage people from working in these areas. Second, the naturally limited areas (vegetation limited, slope/hydrologically limited) are based on the potential categories (oVC_PT and oCC_PT) ALONE which I think have sound logic (see Mgmt Categories below). **We need to get the potential human-beaver conflict model resolved ASAP (within the next couple of days).** Also, please have a look at the rest of Sara's post.  Thank you!

**Comment by wally-mac** [comment]
@bangen I just read through your entire post and my notes and I think your takehomes are correct.  @joewheaton and @sshahverdian can you please take a few minutes and weigh-in and address Sara's questions above?  **Note: Sara only has a few weeks before she takes her maternity leave and she wants/needs to have all the TNC basins run before then.**  Thanks!

**Comment by joewheaton** [comment]
@bangen thanks for all this... To keep this more readable. I'm going to just address this in pieces (working here with @wally-mac):

You wrote:

> @joewheaton A major point you made was that reaches should only fall under the 'Unlikely Beaver Dam Building Opportunites' if the 'EX' is 'None'. Is this the case or did I misinterpret what you were saying? I have 2 issues with this. First, the 'PT' could be higher and I don't think we should discourage people from working in these areas. Second, the naturally limited areas (vegetation limited, slope/hydrologically limited) are based on the potential categories (oVC_PT and oCC_PT) ALONE which I think have sound logic (see Mgmt Categories below).

Not exactly the point I was trying to make. I was trying to say that:

- I want a new 'Unlikely Beaver Dam Building Opportunities' layer that comes from a combination of the logic in Scott's 'new' model and our 'old' one. The reason for splitting into its own layer, is for ease of interpretation of cartography, and to isolate the parts of the network where we don't really need to worry about beaver building dams.
-  It IS NOT that I want to "discourage people from working in these areas". This falls under context of 'Management' layers, and I just want to isolate the 'rest' of the network where if we're talking about beaver management, restoration, conservation or nusiance control from dam building, we can cross these areas off the list. Now, the other 'management' outputs, focus us on where to do conservation and restoration. And the nuisance stuff, still might consider undesirable harvest as an impact in some of these areas, but that is ITS own, highly specific output. 
- The broader thing I was picking up on was that in the management model of old, everything that was red and orange (i.e. natural or anthropogenically limiting was from `occEX = 0`. That's exactly what I still want. Scott's logic of why its limiting I like, but I don't like that it had included `occEX <= 1'. So, take the good of his changes, and just get rid of the rares in this context. My rationale for that is a) in case of Truckee we're talking difference between 10,000 km and 16,000 km.... drawing attention to way too much of network; b) this layer I'm asking for is specifically 'Unlikely Beaver Dam Building' and I don't consider rare to be 'unlikely'. In fact, 'rare' are precisely the locations we often find dispersing beavers getting into trouble. I want those 'nuisance' situations where the impact is from dam building to be highlighted (not buried inappropriately here).

**Comment by joewheaton** [comment]
This thread was a useful discussion but too confusing.... See new, more concise issues that reference it.

**Comment by joewheaton** [comment]
I'm not reopening this... just adding this for context. See #175 for where we're going. 

@sshahverdian distilled managmeent down to 

1. Immediate Returns: High Impact/Activity
2. Immediate Returns: Moderate Impact/Activity 
3. Long-Term: Moderate Potential, Short-Term: Unsuitable
4. Long-Term: Moderate Potential, Short-Term: Unsuitable

I told @sshahverdian I understand his motivations (i.e. removing conflict from this model), but after much reflection I don't think it is that helpful, because it ultimately turns into the non-red areas of BRAT capacity (i.e. none = `oCC_EX`). Also, I am not fan of the labels. They are paragraphs (as bad as River Styles name that don't roll off the tongue).  I think we need to stop screwing around and pretending we can't say something meaningful about conflict (#16, #69)! With the refinements and improvements we have made to what was 'conflict' (i.e. #69, #134), we can get back to what was driving this. I'm also not sure I buy the LUI as a useful or discriminating or necessary input for all categories (I think it is redundant with what are 'risks' layer already tells us). I appreciate that Scott was trying to get at a mix of time investment, degree of 'impact' and some expectations in short-term, but I think it tried to do too much with the names and not enough for how we'd use this. What Scott meant by impact was good here, and that was confusing and contradictory with other stuff. Plus, we need to cut to the chase and get to conservation and restoration opportunities and we want to avoid those areas that have higher risks of conflict as a first cut.
