### ISSUE TITLE
Taking Connor's Data and Building Data Capture Event & Pretty Maps

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#138]
So in testing our new functionality in BRAT for data capture, we want some good local examples. Connor Penrod's [thesis](https://usu.app.box.com/file/289480995316) (Connor will add links to data and figures) looked at Beaver Dam Dynamics in Logan River Watershed. He specifically did desktop data capture events of dams through time: 
- 2009 Baseline
- 2011 Big Water Year Disturbance
- 2014 Recovery
- 2016 Recovery
- Connor didn't do 2017, but it would be a great second disturbance and easy to get someone to do.

## My Request
Connor please share the data with @chadFHC and @CHafen 

### Figures
As Connor is out of time and has no funding, @CHafen can you please work with Connor to help him prepare new figures 2, 5- 8 (maybe split out 5 too). For us, I want you to work on how we display this sort of data we're now getting from our Survey123 apps cartographically. Make some versions of things and run them by me (here) and then we'll arrive at something we'll rope into BRAT Layer Packages and our Atlas standards. 

Apply our lab cartographic standards and reproduce these. Connor, if you want to learn how to do this, Chalese can help you, but I don't expect you to do the work at this stage. I'm going to have her update the figures and provide them to you.

![fig 5 connor](https://user-images.githubusercontent.com/9723905/43664591-a7c7f8d2-972a-11e8-9bdf-3500d1d0b3b4.png)
![fig7connor](https://user-images.githubusercontent.com/9723905/43664594-a9510f90-972a-11e8-8b72-0963dada51a2.png)

### Data Capture Events
@chadFHC I'd like you to get all the GIS data together from Connor, organize it on Box and ingest these into a BRAT project (enlist help from @banderson1618  if you need it).  The challenge here is to grab the most recent Logan BRAT (talk to @MattReimer on #102) and then figure out how to convert the existing shapefiles from Connor into a riverscapes pyBRAT compliant data capture event. This is something we need to figure out anyway as many of our TNC and Idaho project partners will be giving us data. So lets figure it out now. 

@CHafen you can make maps summarizing these data, and @bangen, @wally-mac and I can help come up with ways to display it.

### StoryMap
Once we get done with this, @chadFHC I'd like you to help Connor make a short web page on his project, highlighting what he did, and make a nice little StoryMap to walk through things.

----
Clear as mud?

**Comment by joewheaton** [comment]
@CHafen and @chadFHC you can bill your time on this to TNC BRAT

**Comment by chadFHC** [comment]
Okay

**Comment by CHafen** [comment]
Sounds good. I can work on these as soon as the data is ready. Also, it would be helpful to have the .mxd files, especially for the zoom ins in figures 6 and 7.

**Comment by chadFHC** [comment]
This sounds good @joewheaton.

**Comment by PenrodC** [comment]
Here is the data used to make the figures
[ABDD_data.xlsx](https://github.com/Riverscapes/pyBRAT/files/2272008/ABDD_data.xlsx)

**Comment by CHafen** [comment]
What's the status on getting shapefiles and .mxd files organized and on Box for this project @chadFHC and @PenrodC ?

**Comment by chadFHC** [comment]
@CHafen 
I haven't seen any shapefiles or .mxd files yet to upload on Box. I'll keep my eye out for them.

**Comment by PenrodC** [comment]
Apologies for missing that request earlier. Everything is on box in this link [https://app.box.com/folder/45862501491](url) 

I can pull out the exact mxd's since the file is a bit of a mess later today.

**Comment by PenrodC** [comment]
Rather, this link

[https://app.box.com/folder/45862501491](url)

**Comment by PenrodC** [comment]
If you copy and paste the link works, clicking on it doesn't for some reason.

**Comment by chadFHC** [comment]
Thanks @PenrodC,  that would be great.

**Comment by CHafen** [comment]
Thanks @PenrodC

**Comment by CHafen** [comment]
Hey @PenrodC  is there a shapefile for 2017 dams? I didn't see it with the files for the other years.

**Comment by CHafen** [comment]
Thanks @PenrodC, is there data for 2017 dam locations and such just not compiled into one shapefile? If so, is compiling that data something you want @chadFHC  to work on @joewheaton ?

**Comment by PenrodC** [comment]
Here it is @CHafen [https://app.box.com/folder/45862453494](url)
Listed under 2017_dams. In the attribute table under column "2017" are the values 1-3. 1 = intact, 2 = breached, 3 = blown out.

**Comment by CHafen** [comment]
Thanks @PenrodC

**Comment by CHafen** [comment]
Draft figures 2 and 5. What do you think @joewheaton ?
![logan_littlebear_studyarea](https://user-images.githubusercontent.com/39837888/44556982-42a15a80-a6f1-11e8-9513-13081dfe9e07.png)
![logan_2009-2017_damstatus](https://user-images.githubusercontent.com/39837888/44556983-4503b480-a6f1-11e8-8435-19900bfe9b7e.png)

**Comment by wally-mac** [comment]
These are awesome maps! Nice work Chalese!  @Albonicomt, I think this is a good template for the Escante maps you are working on.

**Comment by Albonicomt** [comment]
Nice! I will definitely keep these in mind when I put some of those maps together. Thanks!

**Comment by PenrodC** [comment]
I think they work fantastically. Thank you Chalese, they are much more effective than my originals!

**Comment by CHafen** [comment]
Thanks @wally-mac 
@Albonicomt if you have any questions on how I made these let me know
@PenrodC I'm having some trouble figuring out what shapefile to use for figure 7 (2014 dams comparing NAIP and Google imagery) could you point me to the correct shapefile for that?

**Comment by PenrodC** [comment]
@CHafen I'll be back home in a couple days, I'll try to track it down for you then.

**Comment by PenrodC** [comment]
Here you go @CHafen 

[https://app.box.com/folder/45862478876](url)
Shapefile is 2014_NAIP_Google_comp.

Again, thank you for the amazing work you've put in to these figures.

**Comment by PenrodC** [comment]
Just in case the link doesn't work again, it is under Mapped_Beaver_Dams -> Status_Change_Analysis.

**Comment by CHafen** [comment]
Thanks @PenrodC . Also, I'm not sure what data to use for the 2016 comparison. I thought it would be the 2016_dam_figure shapefile in the same folder, but it looks like that file doesn't have all the watersheds.

**Comment by PenrodC** [comment]
If you go to Maps @CHafen  -> it's NAIP_Field_Comparison

**Comment by CHafen** [comment]
Thanks @PenrodC I found the map. I can't find the shapefiles for "NAIP" and "Field" though.

**Comment by CHafen** [comment]
I've posted completed figures to Box [here](https://usu.app.box.com/file/317436456267)

**Comment by PenrodC** [comment]
Apologies @CHafen , I named them generally for the map but they retained their individual names within the files. NAIP is 2016_Dams_point found under the header Mapped Dams. Each of the "field" shape files will be found under the "konrad" header (as he collected the data). Rock_creek_field, Temple_field, and East_Fork_Little_bear_field.

**Comment by CHafen** [comment]
Hey @PenrodC . I found the data and everything looks good, except the field data for Rock Creek. What I found doesn't match your figure (see attached image- yellow being NAIP, green being field). The shapefile I found for dams surveyed in the field has way more dams than are shown in the figure you made. Not sure why this one doesn't seem to match and Temple Fork and East Fork Little Bear look like they match. I got them all from the same folder (Mapped_Beaver_Dams--> Konrad). Any thoughts as to why this might be off?
![capture](https://user-images.githubusercontent.com/39837888/45836021-81124100-bcc0-11e8-8198-9a20c2753a59.PNG)

**Comment by PenrodC** [comment]
@CHafen it's an artifact of an earlier version. The data you worked off of should be more accurate for the current narrative.

**Comment by CHafen** [comment]
So Konrad was looking at this figure (figure 8) and was wondering where @PenrodC  got the data. He says they didn't collect any field data for East Fork Little Bear and that it looks like all the dams that we're calling "field" in this figure are from Google Earth imagery. He sent me a shapefile for the dams they surveyed in the field for the Logan-Little Bear HUC 8. It shows dams in Rock Creek and Temple Fork, but not in the East Fork Little Bear.

**Comment by PenrodC** [comment]
I pulled them all off of the iPad in the lab. Are the dams for Rock Creek and Temple the same as in the folder?

**Comment by CHafen** [comment]
No, there are more dams for both Temple and Rock Creek in the file Konrad sent me than in the folder I got from you.

**Comment by PenrodC** [comment]
Well I still think we should keep three sub basins for the comparison. Does Konrad remember what other sites were surveyed in the field in addition to Temple and Rock? I was under the erroneous impression that everything in that file was collected in the field. How many dams short are Temple and Rock? The "artifact" I mentioned earlier was when I initially was looking for false positives and negatives I was only interested in dams that were visible in the imagery, but were misclassified; ignoring dams not visible due to low resolution/occlusions/etc. I later decided that methodology construed the data in to a more favorable light than in reality. My best guess is that I sent you the "old" data.

**Comment by CHafen** [comment]
The data I got from Konrad is on Box [here](https://usu.app.box.com/folder/26688961768). All the dams in this file were collected in the field. There are several other watersheds.
Below is a picture of the difference in # of dams from the data I got from you (in green) and from the data I got from Konrad (black)
![capture](https://user-images.githubusercontent.com/39837888/45970549-b0d88600-bfeb-11e8-96f8-3cb2d2466ae0.PNG)

**Comment by PenrodC** [comment]
@CHafen, here is the data for figure 8. I decided a third sub-watershed actually was not necessary. In the original I have a built in table, but I'm going to include some extra variables and I feel it would be too busy to keep alongside everything else. I appreciate all of the help you've given. I know you're busy, so whenever you have a little bit of extra time is fine.
[NAIP_Field_comparison.zip](https://github.com/Riverscapes/pyBRAT/files/2590387/NAIP_Field_comparison.zip)
