### ISSUE TITLE
Add or Modify Tool to add Existing Dams to BRAT Table

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#14]
We need to add a tool to BRAT to ingest in the dam census data. We already have a couple fields to populate in the `e_DamCt`, `eDamDens` and `eDAMPcC` [attributes](http://brat.riverscapes.xyz/Documentation/10-WorkingWithBRATOutputs.html#attribute-field-descriptions). We need a tool that:
-  Asks user to load:
   - Specify BRAT Project
   - Choose BRAT Realization/Ouput Table to Add to'
   - Load from Shapefile (of type point) a Dam census layer 
   - Choose (radio button) whether this is a 'Dam Inventory', or a 'Scenario'
  -  Specify the date this dam census corresponds to.
- Upon loading:
  1. snaps points to network
  2. populates `e_DamCt` for each segment by counting points that intersect line (do we want to do this separately for primary dams or complexes)?
  3. Calculates `eDamDens` for each segment by dividing   `e_DamCt`  by `iGeo_Length`
  4. Calculates `eDAMPcC' by dividing `eDamDens` by `oCC_EX`
- Then we need to output as layers 
  - `eDamDens` symbolized in same way as capacity
  - `eDamPcC` with new symbology to show off the areas of network with additional capacity.

In management model, we will need to add this `eDamPcC` to look specifically at restoration potential and limit it by conflict potential areas. Similarly, we need to look at `eDamCt` that are high and focus on those as conservation zones.  We should anticipate this being one of many Dam Inventories added to a BRAT project (say over time).

**Comment by joewheaton** [comment]
@bangen had a good idea that we may not want the output put in the main BRAT table. It may make more sense to output these to their own shapefiles and/or realizations.

**Comment by joewheaton** [comment]
@banderson1618 I thought you were working on this one? Can you please provide an update and also tie your commit history on these to this by mentioning #14 in your commit title.  If you use the `Fix #14` in your commit, that both ties it to this issue and closes it (don't do that until we've tested).

**Comment by banderson1618** [comment]
@joewheaton, I worked on Issue #26, which seemed similar to what you were asking for here. I've written documentation on what I wrote for it (the Summary Report tool) on the website (link [here](http://brat.riverscapes.xyz/Documentation/9-SummaryReport.html)). Let me know if that fulfills what you wanted to come out of this issue, or if there's something else we should add to it.

**Comment by wally-mac** [comment]
@banderson1618, yes this is a similar issue for sure but let's make sure that what you have done with the "Summary Report tool" fulfills all that @joewheaton is requesting here.  For example, we'll like these outputs to be a separate shapefile that would show actual dam density based on the date of the imagery or date of the field collection. @bangen may have some input on the topic.

**Comment by banderson1618** [comment]
From what I can see, the only requirement stipulated here that isn't fulfilled by the SummaryReport tool is that it doesn't save when the actual dam value was collected, and that we haven't prepared a layer with symbology for it.

I'm not sure what the best way is to save the date, unfortunately. I'm assuming that there's some metadata field that we'd want to use in the shapefile output, but I'm not super familiar on best practices regarding shape file metadata. We could also add it as a field, but that would get repetitive, I'm sure.

@joewheaton, how were you picturing the date being saved?

**Comment by bangen** [comment]
@banderson1618 If it's easy enough we should just assign the user-defined date to the shapefile metadata.  The only instance where I see this approach being an issue is if the user has a composite dataset that's based off points from imagery and field data.  Thoughts @wally-mac?

**Comment by bangen** [comment]
@banderson1618 did you ever hear back from anyone regarding symbology layer files?  For density you can just use the existing capacity layer file.  If you don't have a layer file for the eDamPcC field I can create one if you send me some example data.

**Comment by wally-mac** [comment]
@banderson1618 I like your idea of user-defined date.  I think if its a composite they might just enter the data as two separate projects.

**Comment by wally-mac** [comment]
@banderson1618 what is the status of this enhancement?

**Comment by banderson1618** [comment]
This is pretty much what was requested in #26, and that issue was closed. Continued discussion on these fields should probably take place in the context of that issue, so I'd say we can close this issue.
