### ISSUE TITLE
BRAT Table Tool: Hard-Coded Scratch Workspace

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#141]
@banderson1618 I downloaded the latest release (version 3.0.18 commit bc97ea4).  On line 244 there's a hard-coded scratch workspace.  Probably left from some testing?  Can you please remove this?  

I'm digging into Karen's issue (issue #140) so might be worth holding off on a new release until we figure out the source/fix for that one.

![capture](https://user-images.githubusercontent.com/6502954/43853600-7f3bafde-9af5-11e8-9026-536e78350e64.PNG)

**Comment by banderson1618** [comment]
Good catch, sorry for that. I pushed the change, and now I'm running it again to make sure that there's nothing that broke without that line.
