### ISSUE TITLE
Error running Segment Network supporting tool

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/pyBRAT#142]
@bangen @banderson1618 

I am getting the error below when running the Segment Network supporting tool in pyBRAT 3.0.17 for Bruneau_17050102 in Idaho

![image](https://user-images.githubusercontent.com/39836333/43855361-8c7e4a8c-9b02-11e8-98f7-090ca45e07c5.png)

Can I change the value type in the code for ReachID from SHORT to LONG? I tried this and it worked (gave me a segmented network output)- but I do not know if changing the value type would cause issues later on when running through BRAT.

Thanks!

**Comment by banderson1618** [comment]
Yes, you can. That was changed in pyBRAT 3.0.18, so you're totally fine to make that change.

**Comment by kbartelt** [comment]
@banderson1618 awesome, thank you!
