### ISSUE TITLE
Discussion on what differences were seen between a previous and current run of BRAT

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#149]
@bangen @banderson1618 @joewheaton @sshahverdian 
@wally-mac wanted this to be on the discussion board about where we have come through the BRAT refining process and some differences that we are seeing between the statewide run of BRAT and a current run using BRAT version 3.0.17
The study area is Cache Valley Logan Utah [layer package](https://usu.box.com/s/1j063qzglecxu248kycdqpm0s0on7onc). Also here is the link to the state of utah brat [layers files](https://usu.box.com/s/luduojo8hi6qnhwbgjfmz2ovkijbd4h9). The following [video](https://youtu.be/1wSZIjJoVts) describes some of these differences...
Matt

**Comment by wally-mac** [comment]
@bangen here is the box [Link](https://usu.box.com/s/kazw9oqkiien9q7o6t440ottlxhhbim2) to Matt's Logan-little Bear BRAT data.  Here is the box [Link](https://usu.box.com/s/epvi4xdavvwutuhrj27xhl9dph363avn) to Karen's Bruneau watershed BRAT Run. As a reminder we want to explore the Q2 stream power it appears to me that the existing capacity outputs are estimating much more capacity on the mainstem rivers than really exists.  Please start a new issue if you would like to I was short on time this morning but I wanted to get the ball rolling on this.  Thanks!

**Comment by wally-mac** [comment]
I spent something looking into the Bruneau watershed BRAT data and I think that Karen's second run using a new Q2 equation looks very reasonable. I'm closing this issue But I think its important that interrogate the outputs of the BRAT model every time we run it.
