### ISSUE TITLE
Implement a new Dam Placement Algorithm

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#15]
We discussed moving from just a dam density algorithm output of the FIS, we could use modifications to [Konrad's dam placement algorithm](https://github.com/khafen74/beaver-dam-location-generator) turned on its head to:
1. place a primary dam  (starting similarly in rank-order based on vegetation)... 
2. Then, sample off an empirical distribution of dam heights (preferably from low gradient systems)
3. Then, use his [BDSWEA](https://github.com/khafen74/bd_h2o), to backwater from that dam and figure out how far upstream the dam would extend (also take the volume and area outputs)
4. Then, using a new empirical distribution of dam complex counts in low-gradient systems, take a random sample of how many dams to include. 
5. Then, if more dams, look upstream and downstream and decide if beaver would build dam there (based on vegetation ouptuts in those areas/reaches).

In end, you'd get locations of dams (points), plus inundated areas, volumes, and we could develop some new metrics along the lines of:
- Dam count and density backed out from this algorithm - Added to network line as new attribute
- Dam inundation areas (polygon) - Added to network line as new attribute
- Dam surface volume (upper and lower estimates too) - as new attribute
- Ratio of water surface storage to valley bottom area.
- Potential inundated area divided by reach length (i.e. a normalized water depth storage per kilometer)

Just some thoughts based on conversations with @bangen, @wally-mac, Scott Shahveridan, Nicole Stohl and Nick Bouwes. Please add to discussion...

**Comment by joewheaton** [comment]
@banderson1618 and @bangen can you please provide some updates as to discussion or any progress on this issue?

**Comment by bangen** [comment]
@joewheaton @wally-mac  I'm not aware of any progress on this front.  IMO, this is more of a priority for the Milwaukee BRAT project than for the TNC or Idaho BRAT projects.  What's the current status of that project?

**Comment by joewheaton** [comment]
Not sure @bangen... Lets scope this #88 but then @wally-mac and I can shelve it.

**Comment by wally-mac** [comment]
This is also important for the John Day BRAT project.  I'm having @MatthewMeier and @banderson1618 scope this.

**Comment by wally-mac** [comment]
@banderson1618 and @MatthewMeier what is the status of this enhancement?

**Comment by MatthewMeier** [comment]
@wally-mac as far as I know @banderson1618 had gotten the code transferred to python and was researching on how to create the input rasters for the script to work with.  This is an important step that is best to be coded. Konrad had to use code in order to do this in the first place but used c++ to do so.
