### ISSUE TITLE
Areas of 'Potential Undesirable Impacts from Beaver Dam Building' elaborated

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#151]
From #16 
>  Areas of Potential Undersirable Impacts from Beaver
> Not so straightforward in that we need to fine-tune the logic and thresholds
> 
> @joewheaton what thresholds were you using here? Rather than take a stab in the dark, it would save use some time to get some in the weeds direction from you.
> I don't quite understand how 'Anthropologically Limited' equates to 'Negligible Risk'. This could be misleading.

Difference between Potential Undesirable Impact and Realized Risk and Realized Impact
- If you have an actual beaver dam data capture event... these can go from potential (i.e. capacity to support dam building) to realized risk if beaver dams are there
- If you have an actual realized impact if you have a data capture event reporting impacts 

### Undesirable Impact: Harvest of Trees:
Lines of evidence:
- Veg Capacity layer (not our oCC) iVeg100 
- Closest Distance to Human Activity - (formerly probability of conflict) minimum
- LUI is higher

### Undesirable Impact: Flooding
- road or railroad or high intensity LU IN a valley bottom
- capacity to build dams there (higher risk if higher capacity... realized risk if actual dams)

### Undesirable Impact: Clogging / Crossing... 

**** IN PROGRESS **** 

![areasofundesireableimpacts](https://user-images.githubusercontent.com/9723905/46162772-6d2d8880-c246-11e8-9f2b-dc02c1f339c1.png)

**Comment by bangen** [comment]
@joewheaton @banderson1618 

For now I just added the 'oPBRC_UI' field and am setting all the rows to 'Negligible' until the in the weeds details are provided by Joe so that Braden can code it up.
