### ISSUE TITLE
Layer Package Changes: Order and Sub-Grouping

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#158]
@banderson1618 

Just a few more changes I'd like you to make to the layer package in the 'new_conflict_model' branch.  Check out this video [here](https://youtu.be/FG2i2qLh5pk).  I put a [dataset on Box](https://usu.box.com/s/dmlj68l1l0wr3pudsib72gcnkdetltm9) that was run using the latest updates in the 'new_conflict_model' branch.  You can find the layer package in the Outputs folder.  Please use this for you testing. 

If you could tackle this while I wait to get Wally's input on the zonal stats issue that'd be great.  Holler with any questions.  Thanks!

**Comment by bangen** [comment]
Cross-referencing Issue #134

**Comment by banderson1618** [comment]
@bangen, that workflow makes sense. I'll focus on this issue as my top priority, though I sadly don't have time today.

I was thinking we should merge the branch layer_package_changes into the master and publish a new release. Should we include these changes in that, or no? I'd appreciate your feedback on that.

**Comment by banderson1618** [comment]
This is a summary of everything I saw asked for in the video. Anything I missed?

- [ ] Change DEM header to "Elevation (m)"
- [ ] Change Flow Acc header to "Drainage Area (sq kms)"
- [ ] Up Hillshade Brightness
- [ ] Existing Veg over Historic Veg
- [ ] Order Intermediates in the following way:
  - Buffers
  - Topographic Index
  - Braid Handler
  - Hydrology
  - Veg Dam Capacity
  - Human Beaver Conflict
- [ ] Order Human Beaver Conflict in the following way:
  - Land Use Intensity
  - Distance to Closest Infrastructure
  - Distance to Road in Valley Bottom
  - Distance to Road Crossing
  - Distance to Road
  - Distance to Railroad in Valley Bottom
  - Distance to Railroad
  - Distance to Canal
- [ ] Put Capacity layers into their own group layer
- [ ] Divide Capacity into Existing and Historic group layers
- [ ] Put Capacity layers in their own folder

**Comment by bangen** [comment]
@banderson1618 

Let's hold off on merging those changes since there are some more tweaks we're going to make.  Also, please make sure you're making your edits on the conflict model branch and not the layer package branch.  

That list looks correct.  I spoke with @wally-mac and @joewheaton earlier today. Some additional changes we'd like to see are:

- Changes inputs 'Conflict' folder name to 'Anthroprogenic'
- Change intermediates 'HumanBeaverConflict' folder name 'AnthroprogenicMetrics'
- Change intermediates 'TopographicIndex' folder name to 'TopographicMetrics'
- Change intermediates 'BraidHandler' to 'AnabranchHandler'.  Change the name of this layer file from 'MainstemBraids' to 'AnabranchType'.  
- In layer package TOC for inputs the vegetation sub-groupings should just be 'Existing Vegetation' or 'Historic Vegetation'.  Right now they're being populated as something like 'Existing Vegetation Dam Building'
- **Critical lpk Change:** Need to include functionality to clip the layers to a subset of the network.  For us, this is so that we can create a layer package that has just the perennial network.  Even though we're running BRAT on the full network, the deliverable we'll most often want to ship is the perennial network.

**Comment by banderson1618** [comment]
Why make the changes to the conflict model branch? These changes seem more suited for the layer package branch. I'm not sure that I follow your logic on that decision.

**Comment by banderson1618** [comment]
@bangen, I've completed the tasks that have been checked off. I didn't get a chance to get into the layer package ordering changes. I'll plan on getting on those on Monday.

**Comment by banderson1618** [comment]
For some reason, I couldn't put buffers on top. It just would not go. I think it must have something to do with it being a polygon layer instead of a polyline. Regardless, everything else is in order, so I'm checking it off.

**Comment by bangen** [comment]
@banderson1618 

I pulled the latest changes from the conflict branch.  I'm not seeing all the changes referenced in my post from 6 days ago (I'm appending them below).  Can you give me a time estimate for finishing these?

Let's hold off on merging those changes since there are some more tweaks we're going to make. Also, please make sure you're making your edits on the conflict model branch and not the layer package branch.

That list looks correct. I spoke with @wally-mac and @joewheaton earlier today. Some additional changes we'd like to see are:

- Changes inputs 'Conflict' folder name to 'Anthroprogenic'
- Change intermediates 'HumanBeaverConflict' folder name 'AnthroprogenicMetrics'
- Change intermediates 'TopographicIndex' folder name to 'TopographicMetrics'
- Change intermediates 'BraidHandler' to 'AnabranchHandler'. Change the name of this layer file from 'MainstemBraids' to 'AnabranchType'.
- In layer package TOC for inputs the vegetation sub-groupings should just be 'Existing Vegetation' or 'Historic Vegetation'. Right now they're being populated as something like 'Existing Vegetation Dam Building'
- Critical lpk Change: Need to include functionality to clip the layers to a subset of the network. For us, this is so that we can create a layer package that has just the perennial network. Even though we're running BRAT on the full network, the deliverable we'll most often want to ship is the perennial network.

**Comment by banderson1618** [comment]
I've been working on the checklist I put together first. Hopefully I'll be done with all the changes except for the capacity rework by next week. The capacity rework is the most significant of all of them, so I'm probably going to save it for last.

**Comment by banderson1618** [comment]
@bangen 

I've implemented all of the things you requested except for the following one:
> **Critical lpk Change:** Need to include functionality to clip the layers to a subset of the network. For us, this is so that we can create a layer package that has just the perennial network. Even though we're running BRAT on the full network, the deliverable we'll most often want to ship is the perennial network.

I'm not sure how you're envisioning this. Should we filter by FCODE? If so, what FCODEs should we accept/reject?

Also note that we'll have to change the source dataset. The cleanest option that I can think of would be to copy the source network, create layers based on that, package them, and then delete everything. That might be a bit performance heavy, though.

**Comment by bangen** [comment]
> I'm not sure how you're envisioning this. Should we filter by FCODE? If so, what FCODEs should we accept/reject?

No, bc a) we don't carry the FCODE over due to how we segment the network, and b) not all users will have a network with a FCODE field.  I was envisioning the user providing a shapefile representing a subset of the network.  For us, this is the perennial network shapefile techs have delineated.  From there it's just a matter of selecting by location or clipping the layers to the subsetted network.  

> Also note that we'll have to change the source dataset. The cleanest option that I can think of would be to copy the source network, create layers based on that, package them, and then delete everything. That might be a bit performance heavy, though.

I'm not clear on what you mean about changing the source dataset.  @joewheaton and @wally-mac do either of you have input on how to package a clipped BRAT run (i.e., keep just the lpk and delete individual clipped lyrs after generating the lpk or keep the individual clipped lyrs, etc.).

**Comment by banderson1618** [comment]
>I'm not clear on what you mean about changing the source dataset. @joewheaton and @wally-mac do either of you have input on how to package a clipped BRAT run (i.e., keep just the lpk and delete individual clipped lyrs after generating the lpk or keep the individual clipped lyrs, etc.).

What I mean is, because the layer gets all its data from its source, we'll have to change the source of the layer if we want to filter out certain streams. For example, because the AnabranchHandler uses BRAT_Table_Output.shp as its source, we'll need to alter BRAT_Table_Output.shp before we package the layer. If we care about preserving BRAT_Table_Output.shp in its original form, we'll have to make a copy of it, edit it, and then create layers based on that copy. Once we've created the layers, we can package them up, then delete them and the copy of the source data. Does that make sense, @bangen?

**Comment by bangen** [comment]
That's one route.  Another option is to just clip the lyr files themselves to the subsetted network.  I'm pretty sure Arc will force you to save this as a feature class, but then just convert it to a lyr file and apply the same symbology as the un-clipped layer.

**Comment by banderson1618** [comment]
I'm pretty sure that would be more expensive, computationally. I think creating shape files is more expensive than creating layers.

**Comment by bangen** [comment]
@banderson1618 however you want to tackle it is fine.  The most important thing is that it's tested and works as intended.
