### ISSUE TITLE
pyBRAT needs to put functions used in multiple files (like makeLayer()) in just one spot

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#159]
Right now, there are functions used all over pyBRAT that have been copy and pasted across the files. While re-using code is good, it means that small updates and bug fixes have been applied incompletely, as issues come up. A good example is the makeLayer() function, which has been implemented in almost every tool in BRAT, and has been slightly tweaked, so that almost every implementation is a little bit unique. By importing all makeLayer() functions from a single file, we make modifying and maintaining the code significantly easier.

Other functions that could use this include makeFolder(), parseInputBool(), and findAvailableNum(). If others come up, I'll post them in this issue.

@bangen, I'm tagging you just so you know what I'm planning to do. If other functions that could use this treatment come to mind, let me know.

**Comment by joewheaton** [comment]
@bangen thinks you addressed this in above commits. So we're closing.
