### ISSUE TITLE
 Changes to Current Naming Conventions for Management Outputs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#160]
@bangen this comes from your #133 and specifically:

## Changes to Current Naming Conventions:
> - Change 'Provisional Management Interpretations' to 'Beaver Dam Building Opportunities'

Almost... this is actually taking Scott's 'Provisional Mgt' layer, and splitting it into two like I did in video. 
In fact, these may all be the same shapefile, but what we're talking about here is the layer packages and the layer groups. So I don't want a 'layer' anymore for provisional management. I want a layer group for 'Beaver Dam Building Opportunities'. There should be two sub layers under that:
1. 'Unlikely Dam Building' and
2.  'Possible Dam Building'. 

It just so happens, that 'Possible Dam Building' layer is where we highlight the conservation and restoration opportunities. 
> - Change 'Unsuitable Or Limited Opportunities' to 'Unlikely Beaver Dam Building Opportunities'

Almost... 'Unlikely Dam Building' because in parent layer group, we already say 'Beaver Dam Building Opportunities' so we don't need to be so verbose.

> - Change 'Restoration and Conservation Opportunities' to 'Potential Beaver Dam Building Opportunities'

So almost on this... 'Possible Dam Building'

## Other Changes:

> - Remove 'Beaver Management Zones' lyr - These will now be split out so no reason to show the full layer

YES PLEASE!

> - Develop 'Provisional Management Overlay Generator' tool - See Joe's comment right above this. We won't develop this in time for the batch run of the TNC basins, but is something we want to implement asap.

Exactly!

**Comment by joewheaton** [comment]
Also, just to clarify, when I say 'split' this layer into two, we're talking about same network, same shapefile, same geometry all in re-displaying the layer based on the 'oPBRC` field. As you'll see in video and my maps, that means that actually for both cases, we display the whole network. 

- For the ' Unlikely  Dam Building' that means we show colors like red and orange for the nuiances Scott defined, but we lump everywhere else with thin (i.e .width = 0.2) grey lines.
- For the 'Possible Dam Building' this means everywhere with `oCCEX > 0`, we show colors based on cons

ervation and restoration, and for all the `oCCEX = 0' it is thin grey lines. 

What this does, is cartographically draw attention to point we're trying to make with that specific layer.

**Comment by wally-mac** [comment]
@bangen, is this the post you were looking for?

**Comment by bangen** [comment]
@wally-mac that's not the post I'm looking for.  What I need from @joewheaton is the specifics for all the other management categories (i.e., the dam building possible categories).  Now that the 'unlikely dam building' logic has changed that has repercussions for the other mgmt categories.

**Comment by joewheaton** [comment]
@bangen I think you can start on this anyway and just report back where you're struggling in specific tickets. Just follow what is provided and be more specific about those 'repercussions for the other management categories.'
