### ISSUE TITLE
Unlikely Dam Building - Areas for Mgmt Outputs 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#161]
@bangen here I am responding still to #133, but see also #160.

> Mgmt Categories:
> Note: The logic laid out below is in a successive conditional statement, starting with the top of the ifelse statement.

Fine... you do what you need to...

## By Unlikely Dam Building Categories
Three categories from Scott's model:
1. Naturally Unsuitable: Hydrologically or Slope Limited
2. Naturally Unsuitable: Vegetation Limited
3. Unsuitable: Anthropogenically Limited
And there is the fourth, that is everything else... i.e. `oCC_EX > 0`

### Naturally Unsuitable: Slope Limited
NOTE! I'm splitting this because we can - NU: Slope Limited vs. Hydrologically.

> Description: Vegetation resources exist to support beaver, but excessive discharge, streampower or slope prevents persistent dams.
> 
> Current Logic:
> oVC_PT is Occasional or higher
> oCC_PT is None or Rare

> Proposed Logic:
> oVC_PT is Occasional or higher
> oCC_PT is None
> oCC_EX is None

Almost, I think we need to just focus on _EX. 
-  `oCC_EX` is None `&`
-  `oVC_EX` is occasional or higher `&`
-  `iGeoSlope` above whatever thereshold we change it in FIS (I think this is that above 23% range, but we would just make it `iGeoSlope>23` here

> Questions:
> Should we really be including combined existing here?

YES... this matters as that condition is entry point to this whole layer!
> What to do with reaches where oCC_PT is Rare?
I don't care about these.

### Naturally Unsuitable: Hydrolgically Limited

Proposed logic:
-  `oCC_EX` is None `&` 
-  `oVC_EX` is occasional or higher `&`
- `iGeoSlope` is < 23, which should cover the following situations:
  -  'iHyd_SP2' above whatever thereshold we use in FIS for 'Blowout' `or`
  -  `iHyd_SPlow` above whatever theshed we use in FIS for 'Cannot Build Dam'
  -  'iGeo_DA' above whatever thereshold we use in FIS for 'too big of drainage area' to make up for fact that SP2 isn't always that good especially in low areas (either too wide, or crap slope calc)...

In these cases, we have these SP and slope values in the FIS and not as a hard code. For this reason, we should always ship or grab the FIS used and put it in the Riverscapes project (this is what we now do in GCD https://github.com/Riverscapes/gcd/issues/303). If we have thresholds in our code (not as part of FIS), we should expose those threhsolds as variables instead of as hard-coded values and in GUI, provide a default value (current hard code).

### Naturally Unsuitable: Vegetation Limited

> Description: Stream power and/or discharge do not limit dam building. Inadequate vegetation resources available. I don’t think we would see this very often. Anywhere with a perennial water source is probably capable of supporting woody riparian vegetation.
> 
> Current Logic:
> oVC_PT is None or Rare
> Proposed Logic:
> oVC_PT is None
> oCC_EX is None

This is correct. This condition is not met in above (because `oVC_PT > 0`), but is met here. The veg is no good, and was never good.

> Questions:
> Should we really be including combined existing here?

Fair point... It could be redundant and including `oVC_EX` seems more direct. However, I'd like to make sure we have a home for all our `oCC_EX` = none, and this helps force that issue. Its also a nested conditional if statement and this is the entry point `if oCC_EX == 0`. 

> What to do with reaches where oCC_PT is Rare?
Since they don't meet the entry point, they all get symbolized as thin grey lines and fall into the 'Possible Dam Building' category (another map)

### Unsuitable: Anthropogenically Limited

> Description: Stream power and/or discharge do not limit dam building. Inadequate vegetation resources available. I don’t think we would see this very often. Anywhere with a perennial water source is probably capable of supporting woody riparian vegetation.
> 
> Current Logic:
> Agriculture LU > 40% OR Developed LU > 40%
> Proposed Logic:
> Agriculture LU > 40% OR Developed LU > 40%
> oCC_EX is None

So if this is a process of elimination in your nested conditional logic, lets get rid of LU as it is just from LANDFIRE. What really want here is:
- `oCC_EX` = none `&`
- `oVC_EX` = none `&`
- `oVC_PT` was > `oVC_EX`
but we arrive at this by this is all that's left over.... after getting rid of naturally limiting. We don't need to check for it. 

> Questions:
> Under proposed logic, all high land use where oCC_EX is not None will be pushed to the 'Potential Beaver Dam Building Opportunities' layer. What do we want to name this category?
Dealing with that in other ticket.

**Comment by joewheaton** [comment]
@sshahverdian agreed with this new anthropogenically limited logic and ditching LUI, but said it would be a good verification/validation to see what LUIs are in those areas.

**Comment by bangen** [comment]
@joewheaton  and @wally-mac I'm trying to finish up Joe's changes so I can run a few basins.  I need the logic for the 'Potential Beaver Dam Building Opportunities' layer.  @joewheaton noted above that he was going to make separate ticket for these, but I'm not seeing it anywhere.

**Comment by bangen** [comment]
Commit should have said ' oPBRC_UD' insteads of ' oPBRC_DB'

**Comment by wally-mac** [comment]
@banderson1618 and @MatthewMeier do you guys know where Joe and Sara left this issue?  Please advise.

**Comment by wally-mac** [comment]
Thanks for the update @MatthewMeier.  @banderson1618, do you have anything to add to this update?

**Comment by banderson1618** [comment]
Nothing that Matt hasn't already said.
