### ISSUE TITLE
It'd be nice if pyBRAT had a standardized code style

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#163]
pyBRAT code switches between camelCase and snake_case a lot in its variable names. It was written by a lot of people, over a long period of time, with many different views on code style, so it makes sense, but it could be improved.

I suggest that all pyBRAT code follow the following naming conventions
- Variable names use snake case
  - For example, `input_network` would be a valid variable name
- Function names use snake case
  - For example, 'make_layers()` would be a valid function name
- Class names use Upper Camel Case
  - For example, `BraidStream` would be a valid class name
- Constants would use all caps
  - For example, `NUM_REPS` would be a valid constant name

@bangen, would you be OK with this? It's fairly simple to change variable names using the "Refactor" command in PyCharm, and it would be nice to have a standard for future development.

**Comment by joewheaton** [comment]
Great idea @banderson1618. You are rewarded for this by simply needing to make a new GitHub page in the documentation on the website for what the standard for our coders should be. Don't worry too much about where to put this. Just make a new *.md page, and @wally-mac and I can organize the help.

**Comment by bangen** [comment]
@banderson1618 As long as you're going to the trouble, please use the [PEP8 style guide](https://www.python.org/dev/peps/pep-0008/).  From a quick search this is popping up as the 'preferred' Python style.

**Comment by banderson1618** [comment]
@joewheaton @wally-mac, here's my suggested coding standards in a markdown file. I had to zip it up to attach it, but it's just the one file.

[Code_Standards.zip](https://github.com/Riverscapes/pyBRAT/files/2462085/Code_Standards.zip)
