### ISSUE TITLE
Procuring some Riverscapes compliant BRAT projects

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#165]
Philip Bailey recently asked @wally-mac to provide 1-3 Riverscapes compliant BRAT projects. The full email is below, but the requirements are fairly simple: they need to be Riverscapes compatible, and they should be somewhat diverse.

Wally and I just met, and what came to mind for us was the Truckee, from the Sierra Nevada project, and Big Wood, from the Idaho project. However, we figured that @bangen and @joewheaton would have some ideas for good watersheds.

The significant concern that Wally and I had was the state of the XML producer. To my knowledge, it hasn't been updated months, and there's been a lot of changes to BRAT in that time. We're not sure if it's still acceptable. @bangen and I should probably sit down and look at this in the near future. We can probably get away with manually editing the XMLs for the projects we choose for this specific request, but it'd be good to not need to. 

---------- Forwarded message ---------
From: Philip Bailey <philip@northarrowresearch.com>
Date: Tue, Sep 11, 2018 at 4:30 PM
Subject: Riverscapes sample projects
To: Wally Macfarlane <wally.macfarlane@gmail.com>

Hey Wally,

I hope all is well.

I'm launching into the Riverscapes toolbar for ArcGIS. Joe mentioned that you are the guy to talk too about getting hold of some sample Riverscapes projects.... probably BRAT but I'm keen if you have other types of Riverscapes compatible projects too.

I need 1 to 3 BRAT projects that you've produced and that are Riverscapes compatible. Preferably these projects would be as diverse as possible - either different locations, for different clients or have different project layers.

Once I get these, I'll probably come back knocking for symbologies and tables of contents. In other words, I need to see how you are looking at the projects in a GIS (either ArcMap or Google Earth etc).

I presume these projects will be large (even when zipped). Let me know if you don't have a way of transferring them. Shared files in Box have worked in the past.

Let me know if you want a quick chat to discuss.

Thanks in advance,

Philip

**Comment by banderson1618** [comment]
Wally sent me the link [here](https://usu.app.box.com/s/u22u9nkc1zf4e6c1nn1bcxlhsjy1k15x) as a good possible source for projects. It's the projects from the recent NRCS conference. I'm posting it here so it's available for everyone.

**Comment by joewheaton** [comment]
@wally-mac says this has been sent to @philipbaileynar. @philipbaileynar do you have what you need?

**Comment by wally-mac** [comment]
Let’s rephrase this @philipbaileynar. Please use the link Braden provided above for your requeasted BRAT data. Thanks!

**Comment by philipbaileynar** [comment]
Quick update to say that I have successfully accessed the BRAT projects. Thank you all.

**Comment by wally-mac** [comment]
@philipbaileynar [here](https://usu.box.com/s/u22u9nkc1zf4e6c1nn1bcxlhsjy1k15x) is the link.

**Comment by philipbaileynar** [comment]
Thanks @wally-mac. I have successfully downloaded some projects. I also got a really good layer package for Nevada that will be extremely helpful for me to develop the layer symbology.

**Comment by joewheaton** [comment]
Okay... this has moved on.
