### ISSUE TITLE
The Layer Package Generator should be able to clip layers to an extent chosen by the user

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#167]
This was previously asked for in Issue #158, but I felt it deserves its own issue, since it's getting its own branch. This is where I'll be numbering commits that develop this feature.

**Comment by banderson1618** [comment]
@bangen, I've been working on this issue. I can clip the source file, but I haven't found a good method for setting the source of the layer files. I've tried to use Layer.replaceDataSource(), but it gives me broken layers in the layer package. I've also tried to use the tool documented [here](http://desktop.arcgis.com/en/arcmap/latest/tools/defense-mapping-toolbox/set-data-source.htm), but I don't seem to be able to use the `defense` module for some reason.

I'm a bit stuck at the moment. If you have any thoughts or advice on the matter, I'd love to hear it.

**Comment by bangen** [comment]
@banderson1618 

I pulled the layer_package_clip branch and ran it.  It's not clipping to the network.  See the below screenshots.  The first shows the input clipping network.  The second shows the capacity output.  So it's definitely not working as intended.  I included the results info so you can see the parameters were correctly declared.  What data did you test this on where you were able to get it to work?

![Input_ClippingNetwork](https://user-images.githubusercontent.com/6502954/57048952-041e5100-6c2b-11e9-8903-815b48a542d5.PNG)

![Output_LayerFiel](https://user-images.githubusercontent.com/6502954/57048954-07194180-6c2b-11e9-8886-000755ecc5ea.PNG)

**Comment by banderson1618** [comment]
Sorry I wasn't able to respond to this, I formally graduated today and that
took up most of my time. I'll take a look at this tomorrow and try to
figure out what's going on with this.

**Comment by banderson1618** [comment]
Hey Sara, I ran through the BRAT input [here](https://usu.app.box.com/folder/75345599152), and I got it to work. Not sure what's the issue on your end.

![Capture](https://user-images.githubusercontent.com/21353496/57148138-3ee8cc00-6d86-11e9-846a-841d3f5b0743.PNG)

In Layer_Package_Generator.py, on line 474, there's a call to the function `restore_copies`. If you comment it out, it won't delete the clipped network and copy over the original. If you do that and look at the shape file that was created, it'd give us some insight into what went wrong.

**Comment by banderson1618** [comment]
Specifically, the BRAT Table output and the Combined Dam output will be altered. They should have a `ShouldKeep` field, which should be given a 1 if we should keep it and a 0 if we shouldn't. All the ones where a 0 is assigned should have been deleted in the tool, so they should all be 1s.

**Comment by bangen** [comment]
@banderson1618 I tried re-running again with the same result (i.e., clipping isn't happening).  Neither the BRAT Table nor the Combined Dam output have a `ShouldKeep` field in the attribute table.  How are you reading in those shapefiles given the user names them and they aren't declared as input parameters to the layer package generator tool?

**Comment by bangen** [comment]
Also, after running the tool the TOC wasn't properly populated.  See screenshot below:

![TOC_AfterRunning](https://user-images.githubusercontent.com/6502954/57154754-7ce9ee00-6d8e-11e9-8b5c-ba13ee47c9b7.PNG)

**Comment by banderson1618** [comment]
Did you comment out the function I said to? If you did, there should be a "<file_name>_Copied.shp" for the BRAT Table output and the Combined Dam output. The originals should have the `ShouldKeep` field. If you're not getting that, then we've got a problem with the code never being run in the first place, for some reason. If that's the case, try looking in to whether the function `clip_folder_to_peren` is being run.

As far as how I'm getting the shape files, I set up a function that looks through the output folder and collects all the non-buffer shape files it finds. The function is called `get_shape_files`.

**Comment by bangen** [comment]
I commented out the call to the `restore_copies` function.  It created all of the "<file_name>_Copied.shp" files, but there is no `ShouldKeep` field in the attribute table.

**Comment by bangen** [comment]
Correction.  I was looking at the  "BRAT_Table_Copied.shp"  attribute table.  There is a `ShouldKeep` field in the "BRAT_Table.shp" attribute table, but every row has a value of 1.

**Comment by bangen** [comment]
The "BRAT_Table.shp" is clipped, but for some reason when the layer package is being generated it must still somehow reference the full network?

**Comment by bangen** [comment]
Some screenshots

BRAT_Table and BRAT_Table_Copied:
![Screenshot_1](https://user-images.githubusercontent.com/6502954/57157068-81b1a080-6d94-11e9-9703-6436b88c0bab.PNG)

Layer package should be clipped but isn't:

![Screenshot_2](https://user-images.githubusercontent.com/6502954/57157104-98f08e00-6d94-11e9-8204-40a0e644f2f0.PNG)

**Comment by bangen** [comment]
At this point we know:

- the "<file_name>_Copied.shp" is being created
- the `ShouldKeep` field is being populated in the "<file_name>.shp" attribute table.  This shapefile is the clipped version each shapefile

Are you creating 'new/temporary' layer files of the clipped shapefiles?  When I the tool with the `restore_copies` function commented out the individual layer files still showed the entire network.  I would think they should have been clipped (since they reference the  "<file_name>.shp" which was clipped.  But for some reason they're not.  Thoughts?  Ideas for further troubleshooting?

**Comment by banderson1618** [comment]
Are you pulling in the layers/layer packages fresh after a run, or are they
in the ToC while you run the tool? I've had issues with Arc not
automatically refreshing layers, but when pulled in from the file, they
work

**Comment by bangen** [comment]
They are not in the ToC.  As in, I'm just testing the layer package generator script using existing run output.  I'm less concerned about the ToC side of things than the layer package not being clipped.  Just so we're covering all bases, are all of your changes pushed up to the `layer_package_clip` branch or did you make some changes and only push to the master?

**Comment by banderson1618** [comment]
All of my changes are pushed. I'm drawing a blank on what the issue could
be. That's very odd that the layers aren't updating. Maybe ArcGIS 10.6.1
introduced some sort of caching that's messing with how the script works?
