### ISSUE TITLE
Invalid Project XML File Paths

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#171]
Every BRAT project XML file that I've looked at has lots of invalid file paths. Here's just example that I got from the Nevada project in Box at `NRCS_2018_Workshops\wrk_Data\Nevada\GIS`. Is this a real problem with the BRAT script that generates these project files, or are these simply disposable workshop files that were never intended to be used?

![2018-09-25_084027](https://user-images.githubusercontent.com/8645379/46026000-133e8e80-c09f-11e8-8916-b907df83c050.png)

**Comment by banderson1618** [comment]
@philipbaileynar, updating the scripts that create the XML files has been a back-burner priority for a while now, so it doesn't surprise me that they're going wrong somehow. This is probably a good time to make it a higher priority.

**Comment by philipbaileynar** [comment]
Ok good to know. I am preparing a release of the RAVE Addin for arcgis for this Friday. It will essentially be useless until those file paths are fixed by either the project owners or the BRAT script owner.

**Comment by banderson1618** [comment]
I'll get on it, then.
