### ISSUE TITLE
BRAT product layers' differences? (examples of how they could be used together?)

### ISSUE THREAD

**Issue by ssuplick** [Riverscapes/pyBRAT#173]
Hello,

I was curious if there's a BRAT team member who'd be able to help me better understand the "human conflict" and "conservation and restoration" model layers in relation to "combined capacity" layer? I.e. whether the first is independent of the second, and perhaps broad examples of their different implications in past projects.

I looked at a few of the most recent GitHub threads on updating the logic for "conservation and restoration", but am a bit unclear on where it stands currently. Its logic appears separate (non-related) from the "human conflict" layer, unless I overlooked a few things?

I want to ensure I understand what I'm looking at so I can be more critical of the outputs and not erroneously analyze BRAT results for the Salinas River watershed in California. If there were past threads that covered this, I would appreciate being pointed to those (to minimize inconvenience to you). Thanks! 

Stuart

P.S. @joewheaton thread #172 is indeed helpful for enhancing understanding of BRAT (at least mine). Thanks for posting that.

**Comment by joewheaton** [comment]
@ssuplick we're in the throws of debating this and developing it... so when it calms down, we'll update the documentation. Stay tuned. 

The old 'human conflict' was way too conservative in that it basically produced a map of how close you are to infrastructure. This dramatically over-predicts where human-beaver conflicts might take place as it does not account for where beaver are likely to build dams (as the old management model did).... nor where good vegetation is... i.e. `ex_VC`...
