### ISSUE TITLE
Lots of private property riparian areas - ideas/alternatives for rapid field surveys

### ISSUE THREAD

**Issue by ssuplick** [Riverscapes/pyBRAT#174]
Hello again,

Briefly, do any members of the BRAT team have experience using orthophotos or aerial photogrammetry as a substitute for rapid field surveys for beaver dams? Or ideas for soundly validating or comparing BRAT results with on-the-ground realities? (In terms of being statistically rigorous - if that's deemed important.)

Much of the riparian area in my study area's watershed is private property, which makes model results validation (or at least comparison to current field realities) via field surveys infeasible for my current project's scope because of property access-seeking time costs and the time limits that I unfortunately have. I've used Google Earth, but it doesn't seem reliable for my purposes based on image quality during zoom-ins.

I am reviewing a few beaver studies that used aerial photogrammetry to identify beaver dams and their dynamics, but wanted to know if any of you had experience with using such.

Best,
Stuart

**Comment by joewheaton** [comment]
Hi @ssuplick , Yes we've done quite a bit of this dam censusing from imagery. We had one plan B MS student (@PenrodC see #138) who focused a lot on this form of censusing to track dynamics.  We've got a number of threads too on data capture events, inclusive of field vs. desktop (e.g. #104). See also the #55.  [Korad's](http://etal.joewheaton.org/konrad-hafen.html) [thesis] has a lot of desktop and field data (Hafen et al. 2017; table 2.2, Figure 2.1). 
(https://digitalcommons.usu.edu/etd/6503/
![dams](https://user-images.githubusercontent.com/9723905/46109770-cfcb4980-c19e-11e8-971f-04d4189521be.png)

@wally-mac you might want this too for work with Google.
