### ISSUE TITLE
'Possible Beaver Dam Conservation & Restoration Opportunities' layer

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#175]
WORKING!!!  JUST SAVING
Okay @bangen, here's that missing stuff from #133

> 'Potential Beaver Dam Building Opportunities' layer. @joewheaton noted above that he was going to make separate ticket for these, but I'm not seeing it anywhere.

### Motivation for this layer
Lets recall that in the old management model we wanted to differentiate three things:
1. Areas that could support beaver, but beaver could cause damage (blue and yellow)
2. Areas that couldn't support beaver (now 'Unlikely Dam Building Areas' #161) (red and orange)
3. Areas that could support beaver dam building, and that would be desirable (i.e. Restoration or Conservation opportunities) (rest of rainbow).

In this ticket, its all about number 3! In #151 I'll deal with number 2. However, as I showed in #133 and that [video](https://youtu.be/VGll4Bobigk), we can do a much better job on where we might want to worry about human-beaver conflicts than we have been. 

![2018-08-03_113538](https://user-images.githubusercontent.com/9723905/43656899-603c9342-9711-11e8-985c-dc578e91f149.png)

#### What this layer really is
Note that this 'layer' is actually a recasting of some of the categories in the `oPBRC` layer (see [table](http://brat.riverscapes.xyz/Documentation/Tutorials/WorkingWithBRATOutputs.html#attribute-field-descriptions)), which has categorical values, and this 'layer' is a filtered subset of that. Please note that the other pieces of it are the 'Unlikely Dam Building' layer (#161) and I am going to propose 'Potential Beaver Dam Building Impacts' layer.  So the _other_ categories that end up in those _other_ layers from `oPBRC` will be:
- Unlikely Dam Building Areas (layer number 2 above and #161) 
  - Naturally Unsuitable: Slope Limited - let `oPBRC = "Un_Slope"`
  - Naturally Unsuitable: Hydrologically Limited - let `oPBRC = "Un_Hyd"`
  - Naturally Unsuitable: Vegetation Limited - let `oPBRC = "Un_Veg"`
  - Unsuitable: Anthropogenically Limited- let `oPBRC = "Un_Anthro"`
- Potential Undesirable Impacts from Beaver Dam Building (layer number 1 above and #151)
 
While this is more or less true, I explain in #178  why its a little white lie. These things are NOT actually mutually exclusive. So here, we need to make a new field that is `oPBRC_CR`. In it we do what we have laid out below, so we can make a map like above.

------

## SPECIFICATION for FIRST CUT of a '_Possible Beaver Dam Conservation & Restoration Opportunities_'
What I want here as a first cut (in absence of data capture event with dams) is conservation and restoration opportunities (where beaver dam building could do good) lumped together. So this layer is thin and grey for all the _other  categories_ above, and for here is:
- 'Possible Beaver Dam Conservation & Restoration Opportunities' (layer 1 above)
  - Easiest - Low-Hanging Fruit - let `oPBRC_CR = "DBO_LHF"` - _Symbology: Thick line-weight (1.75) green_
  - Straight Forward - Quick Return - let `oPBRC_CR = "DBO_QR"` - _Symbology: Medium line-weight (1.25) pastel blue_
  - Strategic - Long-Term Investment - let `oPBRC_CR = "DBO_LTI"` - _Symbology: Normal line-weight (1.0) cyan_

I know @sshahverdian doesn't like that 'low hanging fruit' doesn't sound  different enough from 'quick return' hence my prefixes above, but they've resonated with many people and we just need to define what is meant by them.  So those definitions are below for this 'first cut' or what we run with nationally available data and without refinement from data capture events of where beaver or their dams are. 

### Easiest - Low-Hanging Fruit 
These are areas that have high existing capacity (i.e. _frequent or pervasive_), minimal departure from historic capacity (#176), and low potential for undesirable impacts (i.e. Negligible to minor risk). In a conservation sense, these are areas you wrap up and put a bow on and try to preserve. In a restoration sense, these are areas that you just need to reintroduce, attract, or increase beaver dam building in. 
- 'oCC_EX > 5` &  `mCC_HisDep <= 3`, & `oPBRC_UI = "Negligible" or "Minor"`

### Straight Forward - Quick Return
These are areas that aren't realizing there full potential currently, but could rather easily or quickly. That is throw some BDAs in, or throw some beaver in, and you could quickly increase capacity. This is where we do bring in the LUI (land use intensity) on the logic that areas that have moderate LUI might be degraded from good historic  (i.e. _frequent or pervasive_), but could get back quickly.  In a conservation sense, these aren't the areas to quite yet wrap up and put a bow on. However, from a restoration perspective, these are areas you focus on a few LT-PBR meals to hit them, and get things to the point that beaver could take over restoration for you in that 3-5 year time frame (e.g. Bridge Creek). 

- 'oCC_EX > 1` , & `oCC_PT >= 5`, & `mCC_HisDep <= 3`, & `oPBRC_UI = "Negligible" or "Minor"`
, &  `Developed LU > 10%`, & `Natural/No LU` > 75%` 

### Strategic - Long-Term Investment
These are areas that historically had higher capacity (i.e. _frequent or pervasive_), currently have lower capacity (i.e. rare or occasional), have land uses conducive to recovery (i.e. grazing, logging, pasture are potentials... urban, orchards, roads, industrial, are less so), and have low potential for undesirable impacts (i.e. Negligible to minor risk). In a conservation sense, these are not areas that you would be looking to preserve. These are areas that desperately need some better land management (e.g. better grazing management, better weed/invasive management, better forestry practices). In a restoration sense, these are areas that you likely DO NOT just dump beaver in and hope for the best. Instead, you use LTPBR structures to kickstart recovery in conjunction with better vegetation management that allows riparian vegetation recovery. If that succeeds, over time, these can become your 'quick returns'. They are 'strategic' because your choice to work in these areas, may be guided by a bigger picture or strategic desire to work in that place (instead of it just being quick and/or feasible).  

- '0 > oCC_EX < 5 `, & `oCC_PT >= 5`, & `Developed LU > 10%`, & `Natural/No LU` > 75%`  ,& `mPUI = "Negligible" or "Minor"`

### Everywhere else (less obvious Conservation & Restoration Opportunities).
This is NOT to say that there are no conservation or restoration opportunities with dam building beaver, but they just aren't as obvious as above or might require more careful (e.g. adaptive management and living with beaver strategies). DO NOT worry about this 'everywhere else' being mutually exclusive with 'Unlikely Dam Building Areas' and 'Potential Undesirable Impacts from Beaver Dams'. In general, it roughly will be, but it will also include areas that someone could decide to restore anyway using beaver. That's fine, these different layer views of 'oPRBC' are not meant to mutually exclusive! They are meant to highlight the map in ways that are useful for addressing specific management questions and objectives. 

-----

If you want more refined then this, see #177.

I am not saying above field calculator games are perfect. I'm saying, lets code them up, look at the outputs, see what we're missing, and tweak. Lets not debate this endlessly at this coding stage! One idea, might be to expose as parameters the thresholds defined above (e.g. `oCC_PT >= 5` where **5** is a parameter or know the user could dial to their hearts' content).

**Comment by bangen** [comment]
@joewheaton 

> Strategic - Long-Term Investment
These are areas that historically had higher capacity (i.e. frequent or pervasive), currently have lower capacity (i.e. rare or occasional), have land uses conducive to recovery (i.e. grazing, logging, pasture are potentials... urban, orchards, roads, industrial, are less so), and have low potential for undesirable impacts (i.e. Negligible to minor risk). In a conservation sense, these are not areas that you would be looking to preserve. These are areas that desperately need some better land management (e.g. better grazing management, better weed/invasive management, better forestry practices). In a restoration sense, these are areas that you likely DO NOT just dump beaver in and hope for the best. Instead, you use LTPBR structures to kickstart recovery in conjunction with better vegetation management that allows riparian vegetation recovery. If that succeeds, over time, these can become your 'quick returns'. They are 'strategic' because your choice to work in these areas, may be guided by a bigger picture or strategic desire to work in that place (instead of it just being quick and/or feasible).

> '0 > oCC_EX < 5 , &oCC_PT >= 5, &Developed LU > 10%, &Natural/No LU> 75% ,& mPUI = "Negligible" or "Minor"

Need some clarifications:

- Was 'mPUI" actually meant to refer to 'oPBRC_UI'?  If not, I don't know what 'mPUI' refers to.
- Should 'Developed LU' > 10% be < 10%?  Same goes for the 'Straighforward - Quick Return' category
