### ISSUE TITLE
New 'Departure from Historic' Intermediate Output

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#176]
In #175 I ask for the use of this, and struck me its just a good layer to have.  Please add to the standard BRAT table three new fields (don't forget documentation too: See #129):
- A `mCC_EX_CT` short for an alias of **Modeled Capacity: existing maximum number of dams**, which is simply the number of dams that could fit in the reach, has units of _dams/kilometer_ and is calculated as `mCC_EX_CT = [oCC_EX]*([iGeo_Len]/1000)` - Lets calculate this as an integer, but be careful that all values between 0 and 1 get rounded to one (not just those > 0.5). 
- A `mCC_PT_CT` short for an alias of **Modeled Capacity: historic maximum number of dams**, which is simply the number of dams that could fit in the reach, has units of _dams/kilometer_ and is calculated as `mCC_PT_CT = [oCC_PT]*([iGeo_Len]/1000)` - Integer 
- A `mCC_HisDep` short for an alias of **Departure from Historic Capacity**, which is simply `mCC_PT_CT - mCC_EX_CT` and has units of _dams_.  Have as Integer. 

So below is a screen shot of how this might look:
![departurecapacity](https://user-images.githubusercontent.com/9723905/46165873-f34dcd00-c24e-11e8-97b3-c71031fbc2fa.png)

We would let our `mCC_HisDep` be labled as **Departure from Historic Dam Building Capacity**, show units of number of dams lost or gained, and  have five categories:
- **Extreme Departure (loss of > 30 dams)** - _symbolized with burnt dark red and thick lineweight (2.0)_
- **Large Departure (loss of 10 - 30 dams)** - _symbolized with red and thick lineweight (1.5)_
- **Significant Departure (loss of 3 - 9 dams)** - _symbolized with orange and moderate lineweight (1.25)_
- **Minor  Departure (loss of 1 - 2 dams)** - _symbolized with yellow and normal lineweight (1)_
- **Negligible or No Departure** - _symbolized with grey and thin lineweight (0.25)_
 as to downplay these areas
- **Potential Increase** - _symbolized with grey-pastel-green and thin line weight (0.25)_ as to not draw the eye to them, kind of lump with negligible, but highlight areas where maybe classification of historic or present could be suspect.

**Comment by bangen** [comment]
@joewheaton 

> Lets calculate this as an integer, but be careful that all values between 0 and 1 get rounded to one (not just those > 0.5).

I'm not a fan of the idea of rounding linear densities to whole numbers.  IMO, there's a big difference between 0.1 dams/km and 1 dams/km.  That being said, we can implement what you're asking for here.  Do you want all values rounded up (e.g., 1.1 to 2) or just for values between 0 and 1?

**Comment by bangen** [comment]
@joewheaton 

Some clarification.  Above you have the mCC_**_CT field units as dams/km.  But it's really just dams since the oCC fields are already a linear density.
