### ISSUE TITLE
Splitting the many categories of oPBRC into three layers and not worrying about mutually exclusive...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#178]
ESRI has a really nice symbology feature, which is symbology for 'everything else'. We want to take advantage of that so that we split was all lumped in mutually exclusive categories into `oPBRC` is now nicely split out into the specific layers we care about. These _roughly_ will be mutually exclusive between:

- Unlikely Dam Building Areas (layer number 2 above and #161) 
- Potential Undesirable Impacts from Beaver Dam Building (layer number 1 above and #151)
- 'Possible Beaver Dam Conservation & Restoration Opportunities' (#175)

But NOT exactly! So what we do is split above into their own `oPBRC` and let there be some overlap:
- **Unlikely Dam Building Areas** becomes `oPBRC_UD`
- **Potential Undesirable Impacts from Beaver Dam Building**  becomes `oPBRC_UI`
- **Possible Beaver Dam Conservation & Restoration Opportunities**  becomes `oPBRC_CR`

That overlap is described elsewhere... just floating this concept for @banderson1618 and @bangen beneift.

**Comment by joewheaton** [comment]
I never realized until now, but @wally-mac pointed out that `oPBRC` has awfully nice alignment with:
![pbr_lt_cc_250w](https://user-images.githubusercontent.com/9723905/46169007-32801c00-c257-11e8-9e97-4c23fbcf7a17.png)

**Comment by bangen** [comment]
@joewheaton @wally-mac 

A 'beta' version of these is up on the 'conflict_model' branch.  I haven't put the symbology together yet, so one one of the techs will need to tackle that.  I'll note it in the individual issues for the 3 categories.

I'm going to go ahead and close this for now.
