### ISSUE TITLE
TNC BRAT - Basins with Landfire Issues

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#183]
@wally-mac - please assign this to someone

There were only 3 basins that weren't successfully run through the BRAT Project tool.  It appears to be issues with either the Landfire EVT or BPS rasters.  We need to figure out and resolve the issue with the Landfire rasters (can be found in the 'LANDFIRE' folder for the respective basin) and then run the basins through the BRAT Project and BRAT Table tools (this needs to be done using the zonal stats branch of BRAT....so maybe hold off until that's merged back with the main branch...?).  

The 3 basins are:

- Lower Pit
- Middle Fork Feather
- Upper Deer Upper White

**Comment by wally-mac** [comment]
@Albonicomt, can you please take a look into this issue? You can hold off on it until after you put out the current fires but please put it on your To Do list.

Thanks,

**Comment by Albonicomt** [comment]
@wally-mac, Alright will do thanks!

**Comment by bangen** [comment]
@mhallerud can you check that there aren't any issues with the above basins?  I'm pretty sure they aren't, but since this is still open we should double-check before closing.  Thanks!
