### ISSUE TITLE
TNC BRAT - Batch Runs

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#186]
@wally-mac and @banderson1618 

Once the techs finish making the anabranch edits for the TNC basins we'll want to batch process the rest of the BRAT model.  @banderson1618 you'll be tasked with this.  Most all of the tools will be straightforward to batch process with the exception of the iHyd tool.  

Batch processing the iHyd tool will require reading in a csv with the basin specific parameters.  @banderson1618 I put an [example batch script](https://usu.box.com/s/5bs13z2wini2jyzxtigkntxru2q2d7d8) up on Box that I used to run VBET.  If you have a better/more efficient approach feel free to implement it.  

Additional info (including the regression equations and basin-specific parameter values) can be found [here](http://brat.riverscapes.xyz/Documentation/Tutorials/FHC/2-TNCBrat.html).  Work with @wally-mac to determine which month to use for the low flow equations.

**Comment by joewheaton** [comment]
Just a thought @banderson1618. You _can_ do this batch processing like Sara said. However, if you think it is something we can produce some internal documentation targeted at our techs (but on the website), we could task the techs with this.  I think for TNC it makes sense for you to batch it, but I'm mindful you have a lot on your plate. As such, if we can figure out a way to delegate this (or the next ones .... i.e. Idaho and GYA), it could free up your time. Thoughts?

**Comment by joewheaton** [comment]
Lets hold off on this until we've completed all the testing and updates to new pyBRAT (i.e. ealry to mid November).

**Comment by mhallerud** [comment]
@banderson1618 Let me know when you'll be around later this week and I can plan to be in the lab so we can discuss this.

**Comment by banderson1618** [comment]
@mhallerud I'll be in tomorrow from 10:30-1:30, and in on Monday from 11:30-1:30, and in on Tuesday from 12:00-5:00. Would any of those times work for you?

**Comment by mhallerud** [comment]
@banderson1618 Apologies for the late response, but I'll be around this morning.

**Comment by banderson1618** [comment]
@mhallerud this is an example of what I'd expect to see in a batch processing script. Let me know if you have any questions or concerns.

[BatchProcessingExample.zip](https://github.com/Riverscapes/pyBRAT/files/2756734/BatchProcessingExample.zip)

**Comment by mhallerud** [comment]
@banderson1618 Looks straightforward enough- thanks!

**Comment by bangen** [comment]
@banderson1618 and @mhallerud 

@wally-mac asked me to chime in here.  I took a look at what Braden put together as an example and that could work.  The main downside to that workflow is it requires filling out all the filepaths in a csv.  It's not an issue when running a few basins, but is an unnecessary time sink when we need to run a bunch of basins.  

Assuming all of the file names are generic (which they should be - if not then everyone needs to make those changes) batch processing using a file directory approach is straightforward.  In the case of the TNC project all of my inputs and outputs have generic filenames.  As such, the only portion of the filepath that differs is the huc8 folder name.  Again, the nice aspect of this approach is you don't have to fill out the csv and it removes possible errors due to copying and pasting paths into the wrong cell.  Also, you can include a 'if' line to only run if a specific output folder doesn't exist which is nice for skipping basins that have already run successfully.

Below is an example of what I used to batch run the 'BRAT_table' code.  This approach also differs slightly from Braden's in that I imported the main script which requires commenting out the sys.argv lines.  

Feel free to holler with any questions and/or let me know if either of you want to GoTo at some point.

```
#  define parent folder path and run folder name for directory search
pf_path = r'C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data'
run_folder = 'BatchRun_01'

#  import required modules and extensions
import os
from BRAT_table import main as brattable

def main():
    # change directory to the parent folder path
    os.chdir(pf_path)
    # list all folders in parent folder path - note this is not recursive
    dir_list = filter(lambda x: os.path.isdir(x), os.listdir('.'))
    # remove folders in the list that start with '00_' since these aren't our huc8 folders
    for dir in dir_list[:]:
        if dir.startswith('00_'):
            dir_list.remove(dir)

    # run function for each huc8 folder
    for dir in dir_list:
        if os.path.exists(os.path.join(pf_path, dir, 'BRAT', run_folder)):
            if not os.path.exists(os.path.join(pf_path, dir, 'BRAT', run_folder, 'Output_1')):
                print dir
                projPath = os.path.join(pf_path, dir, 'BRAT', run_folder)
                projName = 'TNC BRAT'
                hucID = dir.split('_')[1]
                hucName = dir.split('_')[0]
                seg_network = os.path.join(projPath, 'Inputs\\02_Network\\Network_1\\NHD_24k_300mReaches.shp')
                inDEM = os.path.join(projPath, 'Inputs\\03_Topography\\DEM_1\\NED_DEM_10m.tif')
                FlowAcc = None
                coded_veg = os.path.join(projPath, 'Inputs\\01_Vegetation\\01_ExistingVegetation\\Ex_Veg_1\\LANDFIRE_140EVT.tif')
                coded_hist = os.path.join(projPath, 'Inputs\\01_Vegetation\\02_HistoricVegetation\\Hist_Veg_1\\LANDFIRE_140BPS.tif')
                valley_bottom = os.path.join(projPath, 'Inputs\\04_Anthropogenic\\01_ValleyBottom\Valley_1\\Provisional_ValleyBottom_Unedited.shp')
                road = os.path.join(projPath, 'Inputs\\04_Anthropogenic\\02_Roads\\Roads_1\\tl_2017_county_roads.shp')
                if os.path.exists(os.path.join(projPath, 'Inputs\\04_Anthropogenic\\03_Railroads\\Railroads_1\\tl_2017_rails.shp')):
                    railroad = os.path.join(projPath, 'Inputs\\04_Anthropogenic\\03_Railroads\\Railroads_1\\tl_2017_rails.shp')
                else:
                    railroad = None
                if os.path.exists(os.path.join(projPath, 'Inputs\\04_Anthropogenic\\04_Canals\\Canals_1\\NHDCanals.shp')):
                    canal = os.path.join(projPath, 'Inputs\\04_Anthropogenic\\04_Canals\\Canals_1\\NHDCanals.shp')
                else:
                    canal = None
                landuse = os.path.join(projPath, 'Inputs\\04_Anthropogenic\\05_LandUse\\Land_Use_1\\LANDFIRE_140EVT.tif')
                out_name = 'BRAT_Table.shp'

                brattable(projPath, projName, hucID, hucName, seg_network, inDEM, FlowAcc, coded_veg, coded_hist,
                          valley_bottom, road, railroad, canal, landuse, out_name,
                          findClusters = True, should_segment_network = False, is_verbose = True)


if __name__ == '__main__':
    main()

**Comment by mhallerud** [comment]
@bangen Thanks for the pointers! That's definitely going to save a bit of time.

**Comment by bangen** [comment]
Closing since these scripts have been developed (see [here](https://github.com/Riverscapes/pyBRAT/tree/TNC_Changes/SupportingTools/BatchScripts)).
