### ISSUE TITLE
The BRAT Atlas: It's time to develop a template

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#188]
One of the project deliverables for several of our current BRAT projects is an **atlas**.  So what is this **atlas** going to look like and include? Well as a team (@CHafen, @Albonicomt , @kbartelt @joewheaton and I) we are going to determine this in the coming weeks.

I suggest to initial this process we have Chalese, generate a map for each of the inputs, and intermediates using our layer package symbology. Once this first-round of maps has been developed we will review them and determine which ones we think warrant inclusion in an atlas and provide comments and suggested edits.

Also, I think we should build a map booklet using the [data driven pages](http://desktop.arcgis.com/en/arcmap/10.3/map/page-layouts/creating-data-driven-pages.htm) in ArcGIS.  Here is an example of this approach [Green River BRAT Atlas](https://usu.box.com/s/c801z78tlxk9ii5jwc64gcc46hrfz5sv) I think the map pages (zoom in maps) can be greatly improved on by including for example an aerial photo base and additional overlay layers such as ownership @Albonicomt has developed some great examples of this for example check out [this map](https://usu.app.box.com/file/316936233173).

This is post in intended to just get this process started and please feel free to add any thoughts and ideas you might have to this post.

Thanks,

**Comment by wally-mac** [comment]
@CHafen let's have you use the [Middle Fork John Day](https://usu.box.com/s/vlepp43hxhzi455lw96eye842bba2foy0 watershed as our test watershed.

**Comment by joewheaton** [comment]
This is now moved to #184, #204, #193 so closing this.
