### ISSUE TITLE
How do I refer to BRAT 2.0?

### ISSUE THREAD

**Issue by ctobalsk** [Riverscapes/pyBRAT#189]
We're writing a report on the Montana BRAT; I ran it using a series of Python scripts (Jordan Gilbert, 09/2016) in an ArcGIS Toolbox (BRAT.pyt) in a folder called BRAT_2.0/BRAT_arc. I assume that my version is a version of pyBRAT and should be referenced as such?
Thanks!
Claudine Tobalske

**Comment by wally-mac** [comment]
Hi Claudine,

I suggest you call it PyBRAT Version 2.0. You could add the date as well 09/16.

Thanks for reaching out,

Wally

**Comment by ctobalsk** [comment]
Thanks Wally!
