### ISSUE TITLE
"Eager": Partnering with Google to use image recognition & ML to identify beaver dams

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#191]
@danackerstein, @eddiecorwin, @trkelsey, and @yufengg welcome to the Riverscapes pyBRAT Issues Board.  I hope we can use this platform to effectively deal with the technical issues we arise on the Eager Project.  As as starting point, I have added the email I sent out to the group below and I think we should address it here instead of through email and see how it goes.

Back in July, I shared [this](https://usu.app.box.com/folder/51139088561l) kmz file that shows beaver dam locations identified using **manual air photo interpretation**. Since July, Dan, Eddie and Yufeng  have been sharing this kmz file with image recognition and ML experts at Google. Questions regarding the usability of these data have surfaced leading me to think we need to be using a dataset that is not based on image interpretation but one based on **field data collection**. Here is [that](https://usu.box.com/s/f8l4yr2c1duot1unema2cx8479mu37h8) kmz file which is part of Konrad Hafen's [thesis](https://digitalcommons.usu.edu/etd/6503/).

Please have a look at Konrad's kmz file and see if it serves our needs better. 

@khafen74 and @CHafen I'm adding you to this tread with you hopes that you can provide some insights into these dataset as we move forward with our discussions

**Comment by wally-mac** [comment]
@khafen74 noted that "some of these points are shifted off the stream." These stifts are due to GPS error and points that are "way off the stream" are most likely accidental placements.

**Comment by joewheaton** [comment]
This manuscript is in review.
