### ISSUE TITLE
Develop a standardized folder structure for BRAT summary and atlas products

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#192]
@Albonicomt and @CHafen please continue to work on developing a standardized folder structure on Box for the summary products.  What does this look like now? How do we want it to look in the future? Once you have developed this structure we can have Braden generate a script that automatically generates this structure. Down the road we can make this more compliant with the Riverscaps project structure.

**Comment by joewheaton** [comment]
FYI, @banderson1618 and I spoke about this. I haven't tasked him with hit just yet as I want to see how it works for us. @banderson1618 said this would be easy to do.

For now we suggested:
1. A simple tool that when you run it asks you to select a current BRAT project, and specify the output Figs directory (e.g. [`BOX\etal\Projects\USA\Oregon\JohnDayBart\wrk_Figs\`](https://usu.app.box.com/folder/55370358235)
2. It creates or looks for a `BRAT_Figs` folder in which it will create each output of the project containers with a parent folder name of `YYYY_MM_DD`. The idea being, everytime we re-run or add to BRAT, you just run this tool again. Figures get made as static snapshots from a project as of the date you download them. The folder structure will rarely be fully populated with maps, but you will know exactly where to navigate to find a map or put a map in there.
3. Each time the tool is run, in addition to making an empty folder structure, it also makes a static copy in root of `YYYY_MM_DD` folder of the `project.rs.xml` file. This provide us snapshot metadata of what is in project. We are not attempting to link back over in any dynamic way to actual project.

As far as what the script does, it creates and empty folder structure, based on BRAT project structure at time of export (with however many realizations it has) in following way:
- `BOX\etal\Projects\USA\Oregon\JohnDayBart\wrk_Figs\`
  - `YYYY_MM_DD`.
    - `AI`    - _Complete copy of empty folder structure for Inputs and Outputs_
      - Inputs
      - Intermediates
      - Outputs   
    - `PDF`      
      - Inputs
      - Intermediates
      - Outputs   
    - `PNG`    
      - Inputs
      - Intermediates
      - Outputs   

The idea would be this gets created on the cartographer's local disc, and they can push it all up to BOX, but most end users or other analysts would only navigate to PNG folders or PDF folders and maybe even sync just those.

**Comment by banderson1618** [comment]
@joewheaton, I'm wondering when you want this done by. Is this a high priority, or should I continue to work on XML stuff?

**Comment by joewheaton** [comment]
Good question @banderson1618. @Albonicomt and @CHafen, have you guys played with this yet? What do you guys think? Should I have Braden slap this together so you can? 

I'm thinking this might be a nice quick distraction for you from joys of XML. However, make sure its future proof (i.e. it actually reads the directory structure and coppies it (folders without files) instead of a bunch of hard-coded `mdir` shit that requires you to edit it everytime you change the folder structure (e.g. #197).

**Comment by joewheaton** [comment]
Okay guys...  working version of this is [here for NF Burnt](https://usu.app.box.com/folder/55426293880)

Note, I 
- downloaded zip of latest version of full project from `wrk_data`
- unzipped it (massive) to my `wrk_figs` folder
- set aside the `project.rs.xml` file to keep in root of 'date' of download folder
- opened a command prompt (just type `cmd`) and `cd` to the directory in `wrk_figs`
-[ got rid of all files but kept directory structure](https://stackoverflow.com/questions/15640599/delete-all-files-while-maintaining-directory-structure) by typing `del *.* /s /q` at command prompt in root of project folder. This deletes all the files only. You can type `tree` to confirm this works.
- created `AI`, `PDF` , and `PNG` folders in date folder
- copied above `inputs` and `Output_1` from directory structure into each of the   `AI`, `PDF` , and `PNG` folders 
- then put the PNG files in the right place

See what you think... it highlights some improvements we will likely want to make to our directory structure in projects, but overall is organized just like our projects.

**Comment by Albonicomt** [comment]
@wally-mac, I have not gotten started on this yet. Must have gotten lost among other tasks, my bad . I will get started on it.

**Comment by wally-mac** [comment]
No worries.  I know you have been working hard on getting project deliverables out.

**Comment by Albonicomt** [comment]
@wally-mac, @joewheaton, @banderson1618 Here is my attempt at creating a project folder that includes the additional AI, PDF, and PNG folders with copied Inputs and Outputs within each of those folders using the Cmd prompt. I believe I followed your instructions correctly. Here is a link to the test folder with the project structure. There is no real data in the folder, except for the NF PNGs as an example. Let me know what you think or let me know if I missed the mark on the instruction. link to folder: https://usu.box.com/s/30bwaone7yxqf7skccp23zdu4a8x9vof

**Comment by wally-mac** [comment]
@Albonicomt [here](https://youtu.be/T4jazyKj8xg) is a short video with my feedback.  @joewheaton and @banderson1618 please also chime in.  Thanks

**Comment by Albonicomt** [comment]
Hey @wally-mac , Thanks for the Feedback. I think what happened is I misunderstood the instructions above. I believe, under each file name folder (PDF, PNG, and AI) I should have folders named Inputs, Intermediates, and Outputs. Then each corresponding map goes into those folders. That would probably make the most sense. I will get on that one and put one together for the Tomales-Drake-Bay watershed.
