### ISSUE TITLE
Add this watermark to all maps

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#193]
@CHafen and @Albonicomt [Watermark](https://usu.app.box.com/file/311272249312)

**Comment by joewheaton** [comment]
Once you guys have some examples of these, post them here and we'll get you quick feedback.

**Comment by Albonicomt** [comment]
![middle_columbia_existing_vegetation_suitability](https://user-images.githubusercontent.com/39168968/46907206-5c2e7980-cecc-11e8-983e-a7161e82cff2.png)
![middle_columbia_hood_context_layers](https://user-images.githubusercontent.com/39168968/46907207-5cc71000-cecc-11e8-9530-53a56bccb486.png)
![middle_columbia_hood_hist_riparian](https://user-images.githubusercontent.com/39168968/46907209-5cc71000-cecc-11e8-9f50-275ded2fad5d.png)

**Comment by joewheaton** [comment]
Nice work... Some critical thoughts on just CC watermarks:
- So  I think we should put these in lower left or lower right (depending on map layout). Putting them up top draws to much attention to them (like scalebars and north arrows, they aren't the main point, just context). 
- I also think we need a few more flavors. I'm noticing that the blue lab logo is kind of lost and ironically the white background on the CC and the person (i.e. attribution) circles pops and draws a bit more attention then we might like to something as mundane as a copyright. Hmmm. So maybe make a few 
- Size is bout right. 

Do you want me to comment on the three maps too (those seem to reflect some of the comments we discussed by phone last Thursday)?

**Comment by Albonicomt** [comment]
Thanks for the feedback @joewheaton, I would suggest looking at these Maps for the NF Burnt River. These are the most up to date versions with feedback from @wally-mac and @CHafen 

Summary Products:https://usu.box.com/s/4b0932q08zosnuheq1s2rcl7g57tppz9

Atlas Products:https://usu.box.com/s/gnow4xb080naaunk933k5boq0qknlvnh

**Comment by Albonicomt** [comment]
@joewheaton, Here are those Zoom-in figures displaying 30m and 100m buffers at a 1:1000 scale for the NF Burnt on box if you want to take a look at them.

Zoom-ins :https://usu.box.com/s/l8stpe6vpslbt4nojfxidy8i1y9lfqvg

**Comment by joewheaton** [comment]
Moving this to #203:

> @joewheaton, Here are those Zoom-in figures displaying 30m and 100m buffers at a 1:1000 scale for the NF Burnt on box if you want to take a look at them.
> 
> Zoom-ins :https://usu.box.com/s/l8stpe6vpslbt4nojfxidy8i1y9lfqvg

**Comment by joewheaton** [comment]
Moving to #204
> Thanks for the feedback @joewheaton, I would suggest looking at these Maps for the NF Burnt River. These are the most up to date versions with feedback from @wally-mac and @CHafen
> 
> Summary Products:https://usu.box.com/s/4b0932q08zosnuheq1s2rcl7g57tppz9
> 
> Atlas Products:https://usu.box.com/s/gnow4xb080naaunk933k5boq0qknlvnh

**Comment by joewheaton** [comment]
I think we're good here... @Albonicomt and @CHafen:

Takehome is:
-  put these in lower left or lower right (depending on map layout). Putting them up top draws to much attention to them (like scalebars and north arrows, they aren't the main point, just context).
- We need a few more flavors (i.e. variants without white background in CC circles and using the white for the USU ETAL logo) to use for backgrounds that are dark. The one we have is fine for backgrounds that are light.
