### ISSUE TITLE
Survey123 Apps for Powder Basin

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#196]
We need to have Survey123 apps specifically for Powder:
- BRAT Advanced form
- Single Dam - Advanced form
- Complex - Advanced Form

**Comment by joewheaton** [comment]
In addition, please transfer [Thomas's observations](https://usu.box.com/s/wjux6b88t1lzkcx7d65jkl7q2e11u7u2) into the Single Dam Advanced form.  He only has 13 'active dams', 1 inactive dam and 3 potential dams. So it shouldn't take long. See my video though as some of them are awfully suspect... 

https://youtu.be/csUL7Q3I6WI

@wally-mac feel free to reasign as you see fit. I don't know who else can make the Survey123 apps. We also DESPERATELY need the documentation on those. I noticed Weber didn't take your bait on: #73

**Comment by wally-mac** [comment]
@joewheaton @chadFHC informed me today that he has yet to build these Survey123 apps so he having difficulties documenting this process.  @MatthewMeier and @chadFHC are however working on transferring these to a Single Dam Advanced Form.
