### ISSUE TITLE
Folder Structure of BRAT

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#197]
HI Braden,
I should have looked at this earlier, but I have not. I'm going to suggest that we **change the BRAT project folder structure to be more consistent with GCD folder structure and more intuitive**. 

### Current Project
Right now, as best I can tell you just have an `Inputs`, a `Temp` folder and as many `Output_n` that autonumber. You also have a `log` file in root and a `project.rs.xml` riverscapes project file. 
![brat_project](https://user-images.githubusercontent.com/9723905/46906651-1ec5ee00-cec4-11e8-9876-82b053028195.png)

#### Your inputs:
![brat_inputs](https://user-images.githubusercontent.com/9723905/46906827-b88e9a80-cec6-11e8-925d-e143c49b3166.png)
This works. I imagine adding an 05_DataCapture events for the Survey123 BRAT_cIS runs as well as Dam Surveys and Dam Complex Surveys (all three of are of type point). So maybe something like:
- `05_DataCapture`
  - `BRAT_cIS_Events`
      - `cIS_001`
      - `cIS_002`
  - `Dam_Events`
      - `BD_001`
      - `BD_002`
  - `Complex_Events`
      - `BDC_001`
      - `BDC_002`
#### An Output Realization:
The outputs seem logical. It seems like you have two shapefiles out in root of `02_Analyses` and then 
![brat_output_realization](https://user-images.githubusercontent.com/9723905/46906858-4a96a300-cec7-11e8-99c2-3bded75506db.png)

-----
#### What I dislike
- If we're going to auto-number, lets autonumber with two digits (i.e. instead of `Output_1` make it `Output_01` so that if we get more than 10 the sort order is logical.  This should apply to all realizations of inputs, intermediates and outputs (e.g. instead of `Ex_Veg_1` make it `Ex_Veg_01`)
- I don't like that each Output is dumped into root of project. `Output_01`, `Output_02` , `Output_03`, .... `Output_0n` should be gathered up in a parent directory of `Outputs`. 

#### I'm not sure about
I like how you use two digit, numeric prefixes to keep the sub-folders in order (e.g. 01_ 02_) . However, this could get confusing to sum with things that are 'realizations'. I think its okay as long as 'realizations' (things there are more than one of) are kept as suffixes (i.e. after _00)

##### Intermediates
I see the logic in having all the intermediates in its own `Output_0n` realization folder:
![brat_intermediates](https://user-images.githubusercontent.com/9723905/46906859-4e2a2a00-cec7-11e8-95cf-2e3598e42018.png)

### GCD
Here's an example of a GCD project:
![gcd_project](https://user-images.githubusercontent.com/9723905/46906657-2d140a00-cec4-11e8-9ce0-ea2db3336d9a.png)
And this is how that directory structure is accessed by the GCD Project Explorer:
![gcd_tree](https://user-images.githubusercontent.com/9723905/46906729-8a5c8b00-cec5-11e8-8c91-0d3d952805d9.png)

You can see how there are a bunch of libraries under inputs (DEM Surveys, Reference Surfaces, Masks and Profile Routes), which are analogous to your `01_Vegetation`, `02_Network`, `03_Topography`, `04_Anthropogenic`. So those concepts port across nicely, and the idea of having as many different versions of inputs is also nice. 

Note that in GCD we have `Analyses` instead of `Outputs`.  Not sure if it matters. But then we have different types of analyses like `CD` for Change Detection, and `IC` for inter comparison. I do imagine we'll add new analyses to BRAT like:
- Intercomparisons (of both different BRAT runs and data capture events to BRAT)
- Verification/Validation
- More advanced sub runs (e.g. similar to a budget segregation of a change detection) 

We should think about where these should be housed. 

Thoughts @wally-mac and @philipbaileynar?

**Comment by joewheaton** [comment]
@banderson1618 can you scope these changes above please? It is relevant to your XML recode as in principle we should have as close as alignment as possible in the nesting and folder structure between:
- Layers and layer groups in Table of Contents and Layer Packages
- RS Project Explorers in project explorer in RAVE tree
- Organization of folders on disc (i.e. what's above)

Also, let me know if anything does not make sense!

**Comment by banderson1618** [comment]
Since the only major change that I'm seeing is putting the outputs in an `Outputs` folder, and changing one digit numbers to two digit numbers, I think this should be a pretty quick change. I'm still focusing on XML changes, since that seems more pressing to me, but if you want, @joewheaton, I can set that down and work on this.

**Comment by joewheaton** [comment]
@banderson1618 that makes sense to focus on XML. This will play into that and it is related... so as long as you charge ahead on XML with this in mind, I think we're good. Then pick this up when it makes sense next (& before we have analysts crank through all the Idaho and TNC runs). 

Cheers,
Joe
