### ISSUE TITLE
Errors running through the Layer package

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#198]
@banderson1618  the layer package generator is having issues if you do not close arcgis throughout the process of running BRAT I do not know why but when I rush through BRAT with multiple steps in between closing arc Layer package will not work.
Also what is the development of the clipping feature in the Layer package generator @Albonicomt  and I tried using this feature and it didn't work.

**Comment by MatthewMeier** [comment]
There are also some errors and changes that need to be made in the overall symbology of the BRAT symbology folder. First off historic capacity lyr file is a duplicate of the existing. Meaning that it is also referencing the oCC_EX column instead of the oCC_PT. There are also some additions to the folder need to happen. I have not messed with any of the source code for the tool and this sounds like something that I could do. Is there a time or could you make a video about just some minor edits in the brat script unless I am supposed to be hands off with it? I would be happy to get some of the layer package fixes going. Contact me early this next week if you can.

**Comment by MatthewMeier** [comment]
I have also noticed that there were some errors with the slope and hillshade rasters not building pyramids for the layer package outputs

**Comment by banderson1618** [comment]
@MatthewMeier, sorry that I've been slow responding to this. I'm going to need more to go off of. How does the LPG not work? Does it throw an error? Does it crash Arc? I haven't been able to replicate this error, so I'm going to need you to describe it for me.

**Comment by banderson1618** [comment]
I haven't been able to replicate your problem with the LPG crashing when not closing Arc. Are you still having this problem, @MatthewMeier?

**Comment by banderson1618** [comment]
Closing it for now, unless @MatthewMeier is still having this problem.
