### ISSUE TITLE
Management Unsuitable or Limited...bug)

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#199]
@banderson1618 looking over the outputs from BRAT it appears that there is an error in the code for indicating whether a segment is slope limited for the oPBC_UD field. It appears that many of the segments that are greater than 23% are being classified as being hydrologically limited instead of slope limited. In  speaking with @joewheaton and @wally-mac there should be more segments that are slope limited than what we are seeing. In reference to the code under the Conservation_Restoration.py there seems to be an order of operations error occurring between line 48-68 specifically looking at line 52 dealing with slope limited segments and possibly line 62 as well with vegetation limited. It seemed to us that if it were slope limited it would be classified as that and then if it were less than 23% grade to be classified as hydro limited. Could you look into this.  @joewheaton let me know if I misunderstood.

**Comment by bangen** [comment]
To clarify there isn’t an error with the code.  I coded this up as Joe had outlined.  If the logic needs to be tweaked you should work closely with either Joe and/or Wally.
