### ISSUE TITLE
Need to move BRAT source code over.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#2]
@jtgilbert, We need to move the BRAT source code over here.  Maybe what you could do is start by uploading the Matlab version 1 code up from the old [bitbucket repo](https://bitbucket.org/etal_brat/brat_matlab.git)? Then use the 'release feature' and publish that as version 1.0.  Maybe ask @philipbaileynar  about best practice here. We could then either start a new branch or move the old stuff into a `MatlabBRAT_v1` folder. Then start pushing all your pyBRAT code for version 2 over to the repo. Then publish a release of that.  This will allow us to keep both in same repo. Philip any suggestions?

**Comment by joewheaton** [comment]
Or maybe we just leave the old https://bitbucket.org/etal_brat/brat_matlab reopo alone? And only put python version here? Not sure?

**Comment by philipbaileynar** [comment]
If BRAT currently exists as separate repos for Python and MatLab then keep it as such:

* Move both repos to the Riverscapes organization on GH.
* Ensure both repos clearly state the flavor/type that they refer to: "BRAT - Python" and "BRAT - MatLab"
* Invest most effort into the current Python repo and site.
* For the MatLab repo simply have a README.md file in the root that states that the code is deprecated and then link to the Python repo/site. The Python site should refer back to the MatLab repo where relevant.

If the MatLab version is truly dead and not needed other than for posterity, then simply move the code to a folder at the root of the Python repo called "MatLab". This will loose the commit history of the MatLab repo, but that's probably less important if the code is dead.

Don't try to mix the MatLab and Python commit histories together! Don't start a repo with the MatLab commit history, tag it as version 1 then stack the Python commit history on top. That's unnecessary mess that will be hard to untangle.

These are essentially different products and deserve different repos.

**Comment by joewheaton** [comment]
Thanks @philipbaileynar. Okay, that makes sense. @lhaycock  and @jtgilbert, let's rename current repo to [pyBRAT](https://github.com/Riverscapes/pyBRAT) and do just as Philip suggests. I'll make [matBRAT](https://github.com/Riverscapes/matBRAT) for the Matlab code. 

@lhaycock Lets make sure we:

-[ ] Move the [help documentation from version one](http://brat.joewheaton.org/home/documentation/manual-implementation/beaver-dam-capacity-model) to a `docs` folder in [matBRAT](https://github.com/Riverscapes/matBRAT) & reference it from [main BRAT website help documentation in pyBRAT](http://brat.riverscapes.xyz) 
-[ ] Move the [help documentation from version two](http://brat.joewheaton.org/home/documentation/manual-implementation/the-beaver-restoration-assessment-tool-brat---v-2-0) to a `docs` folder in [pyBRAT](https://github.com/Riverscapes/pyBRAT)

**Comment by joewheaton** [comment]
Okay. Philip showed me how to push over a repo from BitBucket to Github. Kind of a mess so I recorded a [video](https://youtu.be/X9Xq4yaz9d4) in case we ever need to watch it again ([https://youtu.be/X9Xq4yaz9d4](https://youtu.be/X9Xq4yaz9d4)). In a nutshell:
1. Clone BitBucket Repo Locally
2. Create a new `remote` pointing at your GitHub Repo that will receive this (call it `gh`)
3. Use Git Command line and `git push gh master -f` for a forced push to get content up

Kind of nice...

**Comment by joewheaton** [comment]
Source code all moved over for both now...
