### ISSUE TITLE
BRAT Project Builder error message

### ISSUE THREAD

**Issue by ctobalsk** [Riverscapes/pyBRAT#200]
I downloaded the latest BRAT toolbox and I get this error message when I try to run Step 1 (BRAT Project Builder):

Traceback (most recent call last):
  File "<string>", line 152, in execute
  File "E:\BRAT\pyBRAT-3.0.20\BRATProject.py", line 95, in main
    make_topo_layers(topo_folder)
  File "E:\BRAT\pyBRAT-3.0.20\BRATProject.py", line 175, in make_topo_layers
    arcpy.HillShade_3d(dem_file, hillshade_file)
  File "c:\program files (x86)\arcgis\desktop10.6\arcpy\arcpy\ddd.py", line 5407, in HillShade
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000859: The required parameter Input raster is empty, or is not the type of Composite Geodataset.
Failed to execute (HillShade).
Failed to execute (BRAT_project_tool).

My 10m DEM is a .img file, but I get the same error message when I use and Esri GRID raster.  I tried setting up the Environment Settings to Snap raster = my DEM; then it doesn't crash, but seems to run forever (I killed the process after 20 minutes), and wouldn't it then resample my 30m landcover to 10m?

Thanks for you help!

Claudine

**Comment by ctobalsk** [comment]
Incidentally, if I skip this step and go directly to Step 2 (BRAT Table), everything runs fine; but then of course I can't run the Summary Report because files aren't in the proper structure.

**Comment by banderson1618** [comment]
Hey Claudine,

There's something wrong with your DEM input that makes it so that it can't be used to make a Hillshade. I've added a try except block to the code for the Slope and Hillshade, so if you use the latest code on the master branch, it shouldn't crash (no guarantees, since I haven't tested it. If you send me your DEM, then I can test it), but you'll need to use a different DEM if you want have a Hillshade layer.

**Comment by ctobalsk** [comment]
Hey thanks for the response. I can generate a slope or hillshade layer in ArcGIS "manually", but it bonks the script, for some reason. Since I need to batch-run BRAT for 100+ HUCs (each with their own DEM), I'll automate the creation of slope and hillshade separately and add them to their proper folders.

**Comment by joewheaton** [comment]
@banderson1618 is this related to #201 that @MatthewMeier is experiencing?

**Comment by banderson1618** [comment]
@joewheaton, Matt and I have discussed this in person. We're trying to
identify a time to meet in person, so that he can show me the problem in
more detail.

**Comment by ctobalsk** [comment]
Solution was easy, albeit manual - I hashtagged-out the part of the script calling to generate slope and hillshade, and ran the commands myself in ArcGIS, placing the rasters in the appropriate folders. I also got an error because one the script couldn't find the Flow raster; it had been generated but was not where it was supposed to be, so I moved it (to /Inputs/03_Topography/DEM_1) and after that the Layer Package Generator ran fine.
