### ISSUE TITLE
BRAT Project Builder Crash

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#201]
@banderson1618 
So @Albonicomt and I are struggling with the Middle Columbia Hood BRAT run. Our initial thought was that the DEM was the cause of error with the error messages that Mic got but upon further inspection and seeing how far the tool is running through the project builder. I am led to believe that it is an issue with the bps vegetation layer when it reaches line 84 in the code. I think it might be an error in the text of the field or something with the field in the bps layer. I have ran every other input including the Middle Columbia DEM with a different bps layer from another watershed which tells me it is the bps layer. I looked at the BPS_Name and couldn't find anything peculiar but this is where it is crashing. The bps layer and all the other inputs are [here](https://usu.box.com/s/m9ealh16b64xsd4gnxisjak7lsuidh1t) on box. Could you or @Albonicomt take a quick look to see anything that might stand out different?
In the meantime I will take a look and see if I can see anything. We have already tried to re download it.

**Comment by bangen** [comment]
Closing
