### ISSUE TITLE
Editing roads for future runs of BRAT

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#202]
@joewheaton 
I am currently working on the Middle Columbia Hood and looked at the roads layer and thought about what we spoke about with Wally and was wondering how you would like to proceed with other watersheds. To edit the roads layer at all or to just use what is on the web from tiger? In the example of the Middle Columbia Hood I have an example with all of the named roads and one that was straight from tiger. the non named roads seem to be the logging or cell phone tower dirt roads/non existent one. Which one would you like. I have uploaded them to [box](https://usu.box.com/s/4p0ha99kpddjvv7xp3qrp2bi7xfhnc3u).

**Comment by joewheaton** [comment]
For Middle Columbia Hood, we're not on hook for management outputs, so lets NOT do any editing. For Idaho BRAT and TNC BRAT, we need to get feedback from our clients on this about what they want us to do. I'm thinking I like the idea of management model by default one clipping to 'named' roads only (sort of like filtering down to perennial network), and another with everything to show that contrast.
