### ISSUE TITLE
Remaining Maps Needed for NF Burnt & John Day Workshops

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#205]
OKay, @CHafen and @Albonicomt and @MatthewMeier , this is less about cartographic perfection requested in #204  (which you are approahcing BTW) and all about what we really need done by Friday. For a few of these @MatthewMeier has to finish up his analysis and runs. However, for a bunch of them you guys can update the maps here:

Basically, just go into these two powerpoints @wally-mac and I will be using for the workshops, and anything that says 'WRONG ... NEEDS UPDATING' is a map that either needs to be re-created or updated or just made (especially in John Day a bunch are missing):
- [JohnDay PowerPoint](https://usu.box.com/s/8sxnklgt6jekp9eg2n4iw4mbcnzc406u)
- [PowderBasin PowerPoint](https://usu.app.box.com/file/333820439700)

So please flip through and see all the maps that need fixing and coordinate tomorrow and Friday to get those done. Thanks so much. I know @MatthewMeier is in class for much of tomorrow... but the majority of these can get done without his help.

**Comment by joewheaton** [comment]
Also, note that all the map outputs derived from vegetation need to be updated (i.e. veg capacity and capacity), as they are all based on last week's incorrect veg-code blunder. @MatthewMeier please confirm that these are updated and provide @CHafen and @Albonicomt with the latest so they can update those in your absence at class today. Thanks!

**Comment by wally-mac** [comment]
It is my understanding that the veg code errors were only in the North Fork Burnt River watershed. Is this correct?

**Comment by MatthewMeier** [comment]
Yes this is correct the vegcodes only needed changed for the NF Burnt not the John Day

**Comment by joewheaton** [comment]
We're all set for NF Burnt (Thanks @CHafen, @Albonicomt, @MatthewMeier  and @kbartelt).
