### ISSUE TITLE
New logic for `oPBRC_UI` (Areas beavers can build dams, but could be undesirable impacts)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#207]
@banderson1618, after we manually implement some changes to `oPBRC_UI` in [Conservation_Restoration.py](https://github.com/Riverscapes/pyBRAT/blob/master/Conservation_Restoration.py), I want to strip apart the `oPBRC_UI`, `oPBRC_UD`, and `oPBRC_CR` into three seperate commands, which each populate their own tables and shapefiles, such that multiple versions of each can exist, each with its own dependencies.  Lets wait to do this until we've manually played with (#206), got some feedback from the workshop participants and clients, and can confirm.

## Dependencies & Order of Operations
So all three of the new components of Conservation_Restoration module require both the BRAT capacity runs (historic and current) 

### `oPBRC_UD` (Areas beavers can't build dams and why)
Related to #161

###  `oPBRC_UI` (Areas beavers can build dams, but could be undesirable impacts) 
Related to #151.

### `oPBRC_CR` (Conservation & Restoration with Beaver Opportunities)
Related to #175
 [ ] Run new [ConservationRestoration.py](44847eb844177072816ccf09819f38988dc4c0ce) which fixes the logic for the 
- [x] Manually update and populate the logic we defined in comments of lines 54-61 of [Conservation_Restoration.py](https://github.com/Riverscapes/pyBRAT/blob/master/Conservation_Restoration.py)
- [x] Manually update and populate the `oPBRC_CR` such that anything that is currently a 'Easiest - Low-Hanging Fruit', 'Straight Forward - Quick Return', or 'Strategic - Long-Term Investment' is converted to a 'NA' if 'oPBRC_UI' Negligible or Minor (note @MatthewMeier that line 94 is already checking for this, so it might work correctly). We need to basically make sure that 'NA' is used everywhere that `oPBRC_UI = 'Considerable Risk' or oPBRC_UI = 'Some Risk'  `

###  `oPBRC_UI` (Areas beavers can build dams, but could be undesirable impacts) 
Related to #151.

This is just the SQL syntax if doing this in Select by Attributes manually (needs refactoring to Py) to use as pseudo code:

``` sql
            #row[0] = 'Considerable Risk'
            ("oPC_Dist" < 30 OR "iPC_LU" > 0.6) AND ("oCC_EX" >= 15)
            #row[0] = 'Some Risk'
            ("oPC_Dist" < 100 OR "iPC_LU" > 0.6) AND ("oCC_EX" >= 5 AND "oCC_EX" < 15) 
            #row[0] = 'Minior Risk'
            "(oPC_Dist" < 300 OR "iPC_LU" > 0.3) AND ("oCC_EX" > 0 AND "oCC_EX" < 5) 
            #row[0] = 'Negligible Risk' - What's left...

```

However, what we really need to do is make a separate, optional tool in the pyBRAT toolbox for running the 'Beaver Dam Risk Assessment, which populates the 'oPBRC_UI', which prompts the users for the following inputs:
- Input 'Distance to Closest Infrastructure' (`oPC_Dist`) - _allowing user to have different 'realizations' of `oPBRC_UI` (stored in different tables/shapefiles) based off different realizations of road inputs, railroad inputs, canals and then `oPC_Dist`)._ - I'm not sure where and when this gets run now, but we need to make sure that allows multiple realizations!
- Name of realization (default is autoname `oPBRC_UI_00n)` where `n` just auto indexes 1, 2, 3... n)
- Notes or Custom Description:

The user should not have any say in where the thresholds are in the logic above as they represent the categorical breaks in the symbology.  

I would like this to be output into its own shapefile (right now its just in regular BRAT table output... I don't want this: e.g. `17050202_BRAT_CR_P_beta.shp`), which has its own table. Let's put this in its own shapefile we call `BRAT_UI.shp` and let all the place specific and realization version be taken care of in project file and by folder structure. The table should only brings in the fields relevant to this calculation:
- Intermediates (copies of the things that `oPC_Dist` was based on)
  - `iPC_Rail`
  - `iPC_RailVB`
  - `iPC_Canal`
  - `iPC_RoadX`
  - `iPC_Road`
  - `iPC_RoadVB`
- Inputs (passed from which ever realization as appropriate and noted in the project XML) required:
  - `oPC_Dist`
  - `iPC_LU`
  - `ioCC_EX`
- Output
  - `oPBRC_UI`

**Comment by joewheaton** [comment]
Okay. This worked out really well for the John Day and Burnt out in Oregon. Now that @MatthewMeier ran through it manually, @banderson1618 it is a high priority to get this updated in pyBRAT 3.X before we run it elsewhere.

Here's an example of the output. 
![nf_burnt_river_brat_dam_conflict](https://user-images.githubusercontent.com/9723905/47622538-ae29ee80-dacb-11e8-86b8-e828ffb44353.png)

@banderson1618, please have a look at the 'New Logic' above and post any specific questions you have. Otherwise, please scope and @wally-mac and I will work on prioritizing this relative to your other commitments.

**Comment by MatthewMeier** [comment]
@joewheaton 
@banderson1618 and I have implemented the code needed for this output and it is uploaded to the pyBRAT_master branch there are some minor edits that could happen. Such as the user control knob if you would like them to choose whether to eliminate the considerable and some risk segments in the "Restoration or Conservation Opportunities" output. I am sure this will be covered under a separate issue but I will upload the layer file to the master branch as a proposed push.

**Comment by banderson1618** [comment]
@joewheaton, as the tool is currently designed, the field `oPBRC_UI` is made and calculated in Conservation_Restoration.py (Matt and I implemented the commented code in commit 9652d6a). If I understand you correctly, you would like us to take that code, as well as the code that finds `oPBRC_UD` and `oPBRC_CR` and split them into three tools, each of which calculating one field. Is that an accurate summary?

**Comment by banderson1618** [comment]
@joewheaton, it'd be good to get your feedback on my summary, so that I can get started implementing it.

**Comment by wally-mac** [comment]
@banderson1618 and @joewheaton where are we on this front? Please advise.

**Comment by banderson1618** [comment]
@MatthewMeier and I have modified `Step 6: BRAT Conservation and Restoration` to create the three fields outlined in @joewheaton's post. However, we haven't implemented an optional tool that creates those field based on the user defined thresholds.

**Comment by wally-mac** [comment]
Thanks for the update.  What it the "hold-up" on the generation of an optional tool that creates those field based on the user defined thresholds?  Please advise and thank you.

**Comment by banderson1618** [comment]
When I last read this, I had a fuzzy idea about how this should be implemented, and was waiting for clarification from Joe about how to proceed. At this point, it might be better to slap something together on a separate branch and see if it's what he's looking for.

**Comment by wally-mac** [comment]
That sounds like a good plan to me.  Please give it a go and thanks!

**Comment by wally-mac** [comment]
@banderson1618 per our conversation regarding "pulling back the curtain" on the conservation and restoration outputs it might be useful to re-read this post.

**Comment by banderson1618** [comment]
Good find, thanks @wally-mac!
