### ISSUE TITLE
BRAT Table Error

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#209]
@banderson1618 
I am running into the following error with the brat table have you ever seen this before. It seems to be an issue with the railroads layer
![image](https://user-images.githubusercontent.com/30604787/47225619-bec7bf80-d37b-11e8-846b-114b68cbcb29.png)

**Comment by banderson1618** [comment]
I have not seen this error before. It looks like it's a problem with the historic vegetation input. It's trying to create a table based on zonal stats in the area, and for some reason it's failing.

The only thing I have to go off of is "Workspace or data source is read only." Is it possible that there's something in your environment that's preventing it from being able to write a table? I've read online about people having problems if they're trying to run in a folder that syncs with Dropbox. Are you trying to do something like that?

**Comment by MatthewMeier** [comment]
I am not trying to sync the data it was just weird and I thought it was an issue with the railroads layer but I will check out the vegetation layer. I will look into this more.

**Comment by banderson1618** [comment]
Were you able to get past this problem, Matt? It'd be nice to close this issue if we can.

**Comment by MatthewMeier** [comment]
I did get this resolved one of the files that make up the railroad shapefile was read only. it just took a check box click to fix
