### ISSUE TITLE
Mainstem attribute missing error

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#21]
It seems to me that the Mainstem attribute field is not being created anymore since the last 3.0.6 release. I get the following error when I run Braiden's Braid Handler tool.
![image](https://user-images.githubusercontent.com/30604787/38214412-c4f8b7a2-3681-11e8-92fb-e804a0266393.png)
notice no "is mainstem" field was created...
![image](https://user-images.githubusercontent.com/30604787/38214648-8ba570f2-3682-11e8-8a6c-4a38cf7cf9ee.png)

**Comment by bangen** [comment]
Fixed with release version 3.0.7.  Tested and the 'IsMainstem' field is now being created and populated with default '1' value.
