### ISSUE TITLE
Problem with management display?

### ISSUE THREAD

**Issue by ctobalsk** [Riverscapes/pyBRAT#210]
Anyone else has problems with the Management group display after they run the Layer Package Generator?  Everything else displays fine (match between shapefiles /rasters and layer files), but my 3 management displays (Unsuitable or Limited Opportunities, Restoration or Conservation opportunities, and Beaver Management Zones) do not have a symbology (beside a plain Single Symbol colored line).  When I look into the attribute table, there are 3 management-related fields (oPBRC_UI, oPBRC_UD, and oPBRC_CR) but their entries do not match those of the layer files in the BRATSymbology folder. 
For example, oPBRC_CR can be "Easier - Low-Hanging Fruit", "Straight Forward - Quick Return", "Strategic - Long-Term Investment" or "NA". But the Beaver management Zones .lyr lists things like "Low Hanging Fruit - Potential Conservation/Restoration".
Am I missing something???

**Comment by banderson1618** [comment]
You're not missing anything, don't worry. These are new fields that have only recently been added to BRAT, and we haven't been able to create symbology for them yet. I'm not sure who's in charge of it. I'll go ahead and close this issue, and make a new issue with the relevant people assigned to it. Thanks for bringing this to our attention.

**Comment by ctobalsk** [comment]
Oh good!  Thanks Braden!

Claudine
