### ISSUE TITLE
Definitions for new BRAT fields??

### ISSUE THREAD

**Issue by ctobalsk** [Riverscapes/pyBRAT#214]
pyBRAT 3.0.20 generates several fields for which I can't find a definition anywhere: mCC_HisDep, oPBRC_UI, oPBRC_UD, and oPBRC_CR. We're writing the report that will go with the Montana BRAT and would really appreciate something similar to the format in this table: http://brat.riverscapes.xyz/Documentation/Tutorials/WorkingWithBRATOutputs.html
Thank!

Claudine

**Comment by joewheaton** [comment]
Yep.... We're really backed up on documentation these days and are punting
on that until we get through testing the beta releases of 3.2 and we are
happy with the outputs to the point that code development has slowed down.
In meantime, check out enhancement issues in forum, which describe the
fields and algorithm...

**Comment by ctobalsk** [comment]
Thanks Joe, I'll do that.
This is totally unrelated, but I am wondering why several steps of the model generates a new shapefile (e.g. Combined, Conservation, Summary Report) instead of simply adding fields to the attribute table, as is the case of iHyd for example?
