### ISSUE TITLE
Problem with oPBRC_UD?!?

### ISSUE THREAD

**Issue by ctobalsk** [Riverscapes/pyBRAT#215]
Hum, sorry to be posting all the time, but...
See jpeg below, it's the BRAT output for the Montana Bitterroot River HUC displayed on oPBRC_UD, and it makes absolutely no sense to me -- those scattered "Anthropogenically Limited" stream segments (in red) at the head of drainages? Blue segments are Hydrologically limited and make more sense. And it's the same for other HUCs I look at; there seems to be no rhyme or reason for the Anthropologically Limited segments. Is this because this part of the model is still being worked on? Or is it a problem on my end?
Thanks!
Claudine

![capture](https://user-images.githubusercontent.com/43616547/47523108-82e99a00-d854-11e8-94a0-9b2aeff1036f.JPG)

**Comment by joewheaton** [comment]
> Hum, sorry to be posting all the time, but...

That's what these forums are for... no worries. We just won't always necessarily have the time to be super responsive, but we do what we can.

> See jpeg below, it's the BRAT output for the Montana Bitterroot River HUC displayed on oPBRC_UD, and it makes absolutely no sense to me -- those scattered "Anthropogenically Limited" stream segments (in red) at the head of drainages? Blue segments are Hydrologically limited and make more sense. And it's the same for other HUCs I look at; there seems to be no rhyme or reason for the Anthropologically Limited segments. Is this because this part of the model is still being worked on? 

This is definitely still in development and flux. As I said in #223, this is BETA and pre-release status stuff that we're only just developing ourselves. So we're in no position to support it. Yes, there was a flaw in some of the logic in that part of the code as initially described by me (#161) and [implemented by Sara](https://github.com/Riverscapes/pyBRAT/commit/d740427c61b12cbc9d13ed052eba373bafa3b1a3).  The flaw was really an order of operations thing and what 'gets left over'.  

@MatthewMeier and I fixed these provisionally in the [commits to 'Conervation_Restoration.py`](https://github.com/Riverscapes/pyBRAT/commits/master/Conservation_Restoration.py) on October 16th and 17th.  

It seems to be doing what we want now (i.e. for places with existing capacity of zero explain why), but we're still testing.  Really, the anthropogenically limited places are all the places where whatever we've done (typically vegetation) its screwed. Then there is all the natural stuff. What is 'hydrologically limited' basically includes both true stream power limitations (@ baseflow or highlow) and the drainage area threshold.  The vegetation limited seems to rarely show up.  

![why](https://user-images.githubusercontent.com/9723905/47659340-630aec80-db5a-11e8-9747-36781649d851.png)
