### ISSUE TITLE
Edit BRAT Advance V2 Survey123 Form

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#217]
@MatthewMeier the drop down selection "Top of Reach (looking upstream)" under  the "Observer Position Relative to Reach Location" heading needs to be changed to "Top of Reach (look downstream)". For the obviously reason if you are at the top of the reach and you are observing that reach you can only be looking downstream at it.

**Comment by MatthewMeier** [comment]
I have updated the master form and the John Day BRAT adv survey 123 form however if I update the Powder mountain form data will be lost. I am considering this issue closed unless you want me to overwrite the collected powder mountain data.
closes #217

**Comment by MatthewMeier** [comment]
Closes #217
