### ISSUE TITLE
BRAT Paper Forms Edits (simple and complex versions)

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#219]
@MatthewMeier let's work on the following edits to the "hard copy" BRAT forms based on feedback from the NF Burnt River BRAT workshop:

- The inference tables need some edits> Get rid of the “Not Cannot build dam” and change to “build dam”

- Brian pointed out the order of the fields in the form does not match the table, we need to make them match.

**Comment by MatthewMeier** [comment]
This has been fixed and uploaded to box for all of the locations that these forms are found as "[BRAT_cIS.Asessment.Form_Basic_v2](https://usu.box.com/s/75scvh9q008mh793atp3v4cyzr4yzphf)" and "[BRAT_cIS.Asessment.Form_Advanced_v2](https://usu.box.com/s/fntumw3ybujj2ynmy9iry9waacq97sds)"
