### ISSUE TITLE
LANDFIRE Vegetation Score Changes: Making Sure EVT and BPS Match 

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#221]
@MatthewMeier per on discussion on 10/26/18 we should make sure that if we are making coding changes to LANDFIRE EVT we should also be considering making the same changes to the BPS layer when and where this is appropriate. We want to avoid what we had in the uplands of the Brunt River watershed BPS veg scores that were lower than EVT.

**Comment by MatthewMeier** [comment]
@wally-mac I have a few changes that I made that we can go over today and I will look over some more and see if there are more that we could discuss today. The excel document on box can be found at the following [link](https://usu.box.com/s/jsm3nmwckr74rmklb4f7heh10hnvtouz).

**Comment by joewheaton** [comment]
@MatthewMeier please make an attempt at populating [this new standard page](http://brat.riverscapes.xyz/Documentation/Standards/Calibration/LANDFIRE_VegChanges.html) on these calibration standards. Post questions if you have them...

**Comment by MatthewMeier** [comment]
This documentation webpage has been constructed and can be found [here](http://brat.riverscapes.xyz/Documentation/Standards/Calibration/LANDFIRE_VegChanges.html).
