### ISSUE TITLE
Matt Meier not Matt Reimer

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#222]
@joewheaton in looking over a number of issues this morning I noticed you, and I, on occasion,  have mistakenly addressed issues to Matt Reimer instead of Matt Meier. (I'm rather surprised that Reimer has never said anything about this).  Anyway, in the future, I plan on being more careful here and make sure I'm using the correct Matt.

**Comment by joewheaton** [comment]
Dough! Sorry @MatthewMeier for missing you and @MattReimer for the spam. Good catch!

**Comment by MattReimer** [comment]
I just assumed you meant a different Matt when I didn't understand what you were talking about.
