### ISSUE TITLE
Help Documentation

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#225]
Hey @wally-mac, as we discussed, I've cleaned up a bunch of the [help documentation](http://brat.riverscapes.xyz/Documentation/) to start giving people in lab some examples to follow and to start populating. Please have a look through (especially [here](http://brat.riverscapes.xyz/Documentation/))  and make edits as needed for typos. If you or staff have questions on how to document stuff, post them as issues. For basics:
- [How things look](https://riverscapes.github.io/TemplateDocs/styleguide.html) - and [corresponding markdown](https://github.com/Riverscapes/TemplateDocs/edit/master/styleguide.md)
- [Jekyll Themed Standards for Riverscapes Sites](http://riverscapes.northarrowresearch.com/Technical_Reference/jekyll_toolbox.html)
- [Documentation Standards](http://riverscapes.northarrowresearch.com/Technical_Reference/how_to_document_a_model.html)
- [The Base Template Site Theme & Helpful References](https://github.com/Riverscapes/TemplateDocs) and [what that looks like rendered](https://riverscapes.github.io/TemplateDocs/)
- [Icon Library we use in buttons](https://fontawesome.com/v4.7.0/icons/)

As you engage with it and want to update this for benefit of staff, update [this page](http://brat.riverscapes.xyz/Documentation/Standards/documentation.html).

**Comment by wally-mac** [comment]
@Albonicomt, @MatthewMeier, @CHafen, @mhallerud, and @BrittGraham I'd like you all to get familiar with the help documentation that Joe has listed in the above links and how to update and populated this documentation.  In the coming weeks, I'm going to start tasking each of you with using markdown to update and populate our help documentation pages.

Thanks

**Comment by wally-mac** [comment]
[Here](http://brat.riverscapes.xyz/Documentation/Standards/Documentation/) is a working link to the documentation standards page.
