### ISSUE TITLE
Burnt River Workshop Page

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#226]
Hey @wally-mac. Can you take a look at this draft [Burnt River Workshop page](http://brat.riverscapes.xyz/Documentation/Workshops/2018/burnt.html)? Please edit as you see fit, and then we can attempt to do same for John Day BRAT using this as template.

**Comment by wally-mac** [comment]
Hey Joe, this looks really good! I think it will exceed their expectations. The only thing I think we should make sure we get is Brian’s last name. I could reach out to Suzanne for this information if you’d like me to.

**Comment by wally-mac** [comment]
@joewheaton, I made the change to Brian's name and title and made the commit. I think the Burnt River workshop page is good to go. 

 I worked with Justin Rowell to come up with the text for the John Day BRAT Workshop page which can be found [here](https://usu.box.com/s/7dob6mwvatryxk013voy4a3qa8iza2jd).  I want to learn how to do the Github webpages but need some more guidance. Should I make a copy of the Burnt River page and then change the links? Please advise and I'll try to fit this into my busy week with some deadlines looming.

**Comment by wally-mac** [comment]
@joewheaton, just a reminder. You were going to generate a short video showing how you edit Google Slide so I could separate the John Day BRAT workshop slides into sections.

**Comment by joewheaton** [comment]
> @joewheaton, just a reminder. You were going to generate a short video showing how you edit Google Slide so I could separate the John Day BRAT workshop slides into sections.



> @joewheaton, I made the change to Brian's name and title and made the commit. I think the Burnt River workshop page is good to go.
> 
Yep... that looks good.

> I worked with Justin Rowell to come up with the text for the John Day BRAT Workshop page which can be found [here](https://usu.box.com/s/7dob6mwvatryxk013voy4a3qa8iza2jd).

Text looks good, implement it.

>  I want to learn how to do the Github webpages but need some more guidance. Should I make a copy of the Burnt River page and then change the links? Please advise and I'll try to fit this into my busy week with some deadlines looming.

Yep, I finished all that documentation for you last night:
- Everything is linked off of [here](http://brat.riverscapes.xyz/Documentation/Standards/Documentation/)
- [Making New File & Folders](http://brat.riverscapes.xyz/Documentation/Standards/Documentation/new#making-a-new-file--folder)
- [Embedding a Slideshow](http://brat.riverscapes.xyz/Documentation/Standards/Documentation/Common.html#embed-a-slideshow)
- [Linking to a PDF](http://brat.riverscapes.xyz/Documentation/Standards/Documentation/Common.html#linking-to-a-pdf)

**Comment by wally-mac** [comment]
@mhallerud and @BrittGraham please see the links in the above post from Joe Wheaton that provide some very useful information on how to make documentation on the websites.
