### ISSUE TITLE
Video Tutorial Request: Working with BRAT LayerPackages

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#227]
@MatthewMeier,  [here](https://youtu.be/eezz0v3Y3wA) is a short video that describes my request for you to generate a video tutorial for how to use and navigate a BRAT LayerPackages. Once generated I like you to add it to the working with BRAT outputs webpage found [here](http://brat.riverscapes.xyz/Documentation/Tutorials/WorkingWithBRATOutputs.html). In my video I also requested that you locate some better metadata for the BRAT outputs.  

These are highest priority tasks that I'd like to included with the Yakama BRAT deliverables that are due today, but if you need additional time I understand and we can work on these tomorrow as well.

**Comment by MatthewMeier** [comment]
@wally-mac that makes sense and I will get on that asap.

**Comment by wally-mac** [comment]
Matt, what is the status of this request?

**Comment by MatthewMeier** [comment]
Working on it now

**Comment by MatthewMeier** [comment]
I have uploaded the video to the [website](http://brat.riverscapes.xyz/Documentation/Tutorials/WorkingWithBRATOutputs.html) and I am working on the lookup tables now.
