### ISSUE TITLE
What should the Summary Report tool be renamed?

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#229]
The Summary Report tool has a confusing name. What would be a better one?

Suggestions from the discussion today included:

- Data Capture Validation
- Validation Report
- Data Capture Event

@wally-mac, @MatthewMeier, are there any that I'm missing? What should we rename the tool to be?

**Comment by MatthewMeier** [comment]
I think some other possibilities could be...

- "Dam Capture and Model Validation" (bit long but descriptive)

I like any of those that you suggested @banderson1618  but I like the Data capture validation the most out of your suggestions.

**Comment by wally-mac** [comment]
@joewheaton do you have an suggestions here?
