### ISSUE TITLE
Issue with segments

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#23]
Didn't know exactly where to report this Sara but there are some issues that I have been seeing with the network building for idaho and the ones you have uploaded recently that need to be addressed. I am seeing that not including the artificial segments indeed saves time with canals but enters in the possibility of discontinuity due to small segments missing in the network. These are difficult to see as you are editing and can result in the following issues where overlapping nhd areas occur or culverts under roads. I think this is a prime candidate for a tweak in the code and after speaking with wally is pretty important to remedy.  examples include...
![image](https://user-images.githubusercontent.com/30604787/38832438-c4d7b5c6-417f-11e8-8258-80db6f01b537.png)
![image](https://user-images.githubusercontent.com/30604787/38832491-ef5652bc-417f-11e8-9134-34dc342677f6.png)
Maybe this could be an extending line segment to connect to the vertex of another in the segmenting network tool.

**Comment by joewheaton** [comment]
Chiming in late here. At this point, 'connectivity' is less of an issue as we don't *yet* do anything with topology. However, I see us using topology soon. I'm still unsure about why we use the Network Prep tool at all. The old logic was 'Trim down NHD network to smallest chunk of network and only run tool on that. ' However, I thought we now pretty much run it on everything (after segmenting) and then break out the perennial and main focal areas (or maybe those intermittents above some threshold capacity), to be our 'primary' output layer, but still have the 'rest' (i.e. intermittents and ephemerals, and canals) calculated everywhere? Can you guys bring me up to speed?

**Comment by wally-mac** [comment]
To bring everyone up to speed Joe is correct that **now** we pretty much run BRAT on everything (after segmenting) and then break out the perennial and main focal areas (or maybe those intermittents above some threshold capacity), to be our 'primary' output layer, but still have the 'rest' (i.e. intermittents and ephemerals, and canals) calculated everywhere.  **The issues that Matt Meier was facing was a artifact of the old logic 'Trim down NHD network to smallest chunk of network and only run tool on that. '**

**Comment by wally-mac** [comment]
I like the more thorough approach.
