### ISSUE TITLE
Beaver Dam data should be asked for in the BRAT Project tool

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#230]
Per the discussion today with myself, @MatthewMeier and @wally-mac, we will be asking for beaver dam data in the BRAT Project tool as an optional input.

We will also be automatically copying beaver dam inputs to the Summary Report tool to our inputs folder, if they aren't in there already.

**Comment by wally-mac** [comment]
@joewheaton, do you have an input to provide to this enhancement?
