### ISSUE TITLE
VBET_Project_builder_issue

### ISSUE THREAD

**Issue by Albonicomt** [Riverscapes/pyBRAT#231]
@banderson1618, I keep running into this issue with building the VBET project builder. 
![vbet_project](https://user-images.githubusercontent.com/39168968/48501933-a1133c00-e7fb-11e8-9390-6481d8a6af38.PNG)

I haven't run into this issue before. I have re-downloaded The VBET tool and have tried building a separate test project that I have run before and have gotten the same error. Not sure if this is an issue with my computer or not? Do you have any thoughts or suggestions?

**Comment by MatthewMeier** [comment]
I do not know what is wrong with your pc from reading about the error it occurs with tif files sometimes but I ran the VBET project tool through my pc using RCAT 1.0.11 and it worked just fine. I have sent you the project folder through email because there isn't a box location yet. Let me know if you have more errors. I would maybe try pip updating the management.py file since that seems to be the one that is being used. I am not sure the real source of your error though.

**Comment by banderson1618** [comment]
@Albonicomt, I've never seen that particular error before. From what I've read online, it might be a problem with your environment variables? I assume that you've tried restarting ArcGIS?

**Comment by Albonicomt** [comment]
@banderson1618, I am not sure what the Envirmonment variables is. Could you clarify?

I have tried restarting ARC. I still receive the same error. 

Also, in pycharm, I am trying the run the LANDFIRE_LUCode, and I receive this error: 
![lucodeerror](https://user-images.githubusercontent.com/39168968/48575070-32eb7980-e8ce-11e8-926b-46a8942866af.PNG)

It looks like the error is also associated with some 'Environments' problem. Could this be related to my VBET_project issue?

**Comment by banderson1618** [comment]
@Albonicomt, I was basing that off of what I skimmed from the page [here](https://community.esri.com/thread/80038). I don't think that's the problem, since that seems to be a different issue than what you're having. 

However, based on that error, I wonder if there's something wrong thing in your ArcGIS install. Importing arcpy should not be crashing your tool.

**Comment by Albonicomt** [comment]
@banderson1618 , It is possible something is wrong with my ArcGIS install. What is strange is I am able to Build a BRAT project with the same inputs (DEM and NHDnetwork), as well as, the additional BRAT inputs.

**Comment by Albonicomt** [comment]
@banderson1618, As I was able to get through the BRATProject Builder and most of the BRAT Table. The BRAT Table was assigned the appropriate fields all the way through to the ClusterID. The tool seems to be having trouble completing the .xml. Here is the new error associated with the BRAT run. It is something I have not seen before. It could be a case where the tool is having trouble with some file locations on my computer, which could also be associated with an Arc Install problem. Any thoughts?
![xmlerror](https://user-images.githubusercontent.com/39168968/48587374-2415be80-e8f0-11e8-830a-63c0ebf82bee.PNG)

**Comment by banderson1618** [comment]
@Albonicomt can you send me the data you were using for this? I think this problem is unrelated to the other problems you're having.

**Comment by banderson1618** [comment]
@Albonicomt, I think I fixed that particular bug. If you download the latest from the master branch, it should solve your problem. Let me know if you encounter the same bug.

**Comment by Albonicomt** [comment]
@banderson1618, Great news is that I was able to push through to the Combined FIS portion of BRAT. Step 5. Although, I did run into a similar error as before, when the tool is applying info to the xml. 
![combinedfis_xmlerror](https://user-images.githubusercontent.com/39168968/48634554-0c3b4a80-e983-11e8-8e70-250fa0455edd.PNG)

Is there something I can do more to help with these errors. Unfortunately, I don't know a ton about coding, but if these errors are similar, are they easy to fix on my end. Is there any forums or documentation you usually refer to when fixing these issues?

**Comment by Albonicomt** [comment]
Luckily, the tool still creates the appropriate fields and assigns appropriates values to the outputs, even though the tool is having trouble adding info to the xml. I do have the outputs. I am having trouble running through the layer package generator. It runs through most of the LPK generator, but the tool gets hung up on a "non-existing" value. I believe it is the rails layer, but there are no rails in this watershed, so that input is left blank. Here is the error and a forum that I believe correlates to the error. https://stackoverflow.com/questions/16169035/coercing-to-unicode-need-string-or-buffer-nonetype-found-when-rendering-in-dja
![lpk_error](https://user-images.githubusercontent.com/39168968/48637686-b1f2b780-e98b-11e8-9a68-3830a49b2b66.PNG)

**Comment by banderson1618** [comment]
@Albonicomt, I was unable to replicate your Combined Dam bug. Could you send me the project, so I can see if I did something different up to that point?

**Comment by Albonicomt** [comment]
@banderson1618, Yup. I am currently uploading the project to box. I will send a link once it is finished. Thanks!

**Comment by Albonicomt** [comment]
@banderson1618 here is a link to the project folder: https://usu.box.com/s/d5lmh0t92gu0r5h7dz7js92fb7cufq9j

**Comment by banderson1618** [comment]
Great, I'll take a look at that. In the mean time, I just pushed a change that should fix the LPG bug you were having.

**Comment by Albonicomt** [comment]
Cool! Thanks @banderson1618 !

**Comment by Albonicomt** [comment]
@banderson1618, I had not done any editing to the XML. It is possible there could have been a typo somewhere. I will try rerunning from Step 5 again with a careful eye on the file path and see how it goes. Thanks for looking into this Braden.

**Comment by JherimeK** [comment]
My students are having a similar error with the VBETBuilder but with additional error message - 'Not running inside a server process'.  My guess is a pathway issue.  Thoughts?

[VBETBuilder error.pdf](https://github.com/Riverscapes/pyBRAT/files/2947843/VBETBuilder.error.pdf)

**Comment by bangen** [comment]
@JherimeK I recently did some clean-up of the VBET code, which are now on Git [here](https://github.com/Riverscapes/RCAT).  Should hopefully fix the issue your students were running into.  Let me know if are still running into errors.
