### ISSUE TITLE
Salinas River BRAT - cIS/Dam Complex Monitoring Form Questions

### ISSUE THREAD

**Issue by ssuplick** [Riverscapes/pyBRAT#233]
Hey @wally-mac @joewheaton:

If you have a few spare minutes, some clarification on the following sections would be super helpful before I continue with my next round of field surveys:

1. cIS Advanced Form

**SUITABILITY OF RIPARIAN UPLAND VEGETATION**: if "within 100m of water's edge" is ag land but on top of a steep terrace (there was river downcutting to bedrock)...how should this be accounted for in field surveys cIS? If otherwise preferred, on say the other side of the channel for say 70m before another steep slope, should this section's option be downgraded a level or two to account for the fewer acres available for woody harvest?

2. Dam Complex Monitoring Form - Advanced

**STREAMWISE EXTENT OF COMPLEX**: Is this estimated by "dam-to-dam", or "downstream-most dam-to-final pond" or "downstream-most dam-to-final water presence"? Should I just refer to Hafen, 2017 for this?

**FLOW TYPES PRESENT**: not quite sure what "Basal Flow" means (i.e. base flow conditions or flow seen trickling through dam base?), and if "Flow through top" means massive flooding over the top, or just trickling similar to "Throughflow"

**POND EXCAVATION, DAM NOTCHING, DRAINING/FLUSHING**: not sure what these mean - in order, possibly: signs that beaver are "dredging" their pond, that there are visible nicks in the top of the dam to let water through, or their is substantial throughflow or flow over the dam top?

**CORN ON THE COB (FORAGING) vs HARVESTING OF BRANCHES**: is the latter more so for dam building, i.e. if one sees a bunch of branches piled or located near a dam for likely, easy-maintenance efforts?

Thanks for the help,
Stuart

**Comment by wally-mac** [comment]
Hi Stuart,

- Yes, I would suggest downgrading the vegetation score a level.  

- Yes, I'd suggest referring to Hafen, 2017 for this.

- Flow seen trickling through dam base, and throughflow through top.

- Yes, signs that beaver are "dredging" their pond, that there are visible nicks in the top of the dam to let water through, or their is evidence to suggest that beaver intentionally drained their dam.

- Yes, branches piled or located near a dam for likely, easy-maintenance efforts.

Thanks for reaching out and I hope this helps.
