### ISSUE TITLE
Philip's Test Run of BRAT

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#234]
@philipbaileynar, [here](https://youtu.be/0DZQqK5DQKY) is a link to a short YouTube video that describes the content of the BRAT folder found [here](https://usu.box.com/s/rsm1txj1lr3hg3p5mb4bxvsjkhe7nkgn).  Please let me know if this will meet your needs or not.

**Comment by philipbaileynar** [comment]
@wally-mac this is perfect thanks! Having both the inputs and output is really helpful. As you said in the video, this allows me to compare my results with those of an experienced analyst.

I've download and unzipped the file already. Now I'm starting to run the software.

I will check in once I've taken a pass through the pyBRAT tool.
