### ISSUE TITLE
Unable to load Toolbox 3.0.19

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#235]
## Steps To Reproduce

1. I downloaded the zip file from the [releases page on this site](https://github.com/Riverscapes/pyBRAT/releases/tag/3.0.19). This got me a zip file called `pyBRAT-3.0.19.zip`.
1. I uncompressed this file into the same folder.
1. Following the instructions in this [video](https://youtu.be/MVEXXMOPTBI) I added a folder connection to the folder where I uncompressed the Toolbox.

## The Problem

I see a series of red X marks through the `*.pyt` files in ArcCatalog. I don't see the list of tools like Joe got in the video above.

![2018-11-26_115335](https://user-images.githubusercontent.com/8645379/49038686-7bc6ec00-f172-11e8-824a-878a3352d8d9.png)

Help please? What am I doing wrong

Note I am running ArcGIS 10.4.1 with all extensions enabled.

**Comment by banderson1618** [comment]
You should be able to right click on `BRAT.pyt` and click "Check Syntax". That should pull up a window that explains what the problem is. Once you've done that, we'll have a better guess about what went wrong.

My best guess would be that you haven't installed a dependency (probably scikit-fuzzy) to the Python install that ArcGIS is using. The documentation for that is at the link [here](http://brat.riverscapes.xyz/Download/ComputerSetup). Let me know if that works or not.

**Comment by philipbaileynar** [comment]
Thanks @banderson1618 . Here's the message I get with "Check Syntax":

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "D:\GISData\BRAT\pyBRAT-3.0.19\bdwsRun.py", line 1, in <module>
    from bdws import BDLoG, BDSWEA
  File "D:\GISData\BRAT\pyBRAT-3.0.19\bdws.py", line 1, in <module>
    from osgeo import gdal, ogr
ImportError: No module named osgeo
```

I did pip install scikit-fuzzy into the Python installation being used by ESRI. (And I do have several copies of Python).

Do I need to install OSGeo for BRAT? There's no mention of that in the docs.

**Comment by philipbaileynar** [comment]
I finally got all the necessary Python dependencies installed. Straightforward it was not! I'm impressed that others have managed to figure out the process of installing SciPy and other dependencies that require the use of wheel files etc.

**Comment by wally-mac** [comment]
Yea, to be honest the difficulties you have faced have limited PyBRAT's use by individuals outside the ETAL.  Way-to-go... you are among the elite!

**Comment by philipbaileynar** [comment]
I cheated @wally-mac and used @MattReimer !!!!

Figuring out deployment is always going to be our biggest challenge! This is especially true for Windows users and within that group, those that don't really know how to configure their Python environments. 

We buy some flexibility if we can drop ESRI and so I'm going to be very curious to see what essential ArcPy routines are being used.

**Comment by wally-mac** [comment]
It's sure nice to have a genius on your payroll! Yes, I'm very interested in getting your assessment of how we can improve the deployment of BRAT.
