### ISSUE TITLE
Braid handler issue

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#24]
Cluster id issues and drainage areas that is discussed further in the following video...
https://youtu.be/4Pr0fbpfN-U

**Comment by banderson1618** [comment]
Thanks for making the video, I think this is good feedback.

I should be able to implement your first solution fairly easily. I can put in a checkbox called "Find Clusters" in the BRAT Table tool, and then have the Braid Handler handle it differently based on whether or not the stream network already has a ClusterID attribute. It'll be a bit tricky to find the Drainage Area values, but I should be able to manage. That solution made the most sense to me out of the ones you suggested. Does that sound good?
