### ISSUE TITLE
BRAT.xyz Documentation Modifications

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#244]
@BrittGraham,
@wally-mac would like you to work on some website documentation that is lacking for the BRAT project. Many of the issues that have been posted on github is useful for the user but is not what we want the user to necessarily first access in order to find answers to their questions. This will still be a primary way for users to access us for questions, but the better our documentation that we have the less questions users will have and the more time we will have to work on other things. Here are some possible issues that we would like you to document on the website given the standards as described in the following issue #225 

- #121 and #120 illustrates the issue of having to replicate the [Drainage Area](https://en.wikipedia.org/wiki/Drainage_basin) (or number of cells that drain to a certain cell) of Watersheds that are not contain the headwaters of river systems. Basically when you have large rivers like the Columbia, Colorado, Green Rivers. 
- #77 see if this could be added to the DA check documentation or if it is clear enough in the documentation
- #144 See if you can incorporate this into the website or if it is useful
- #189 how to define what is the most current version of BRAT and what the version of BRAT means.
Examples of me documenting an issue that was presented in Github
- #227 
- #221 

Also if you see any confusing organization or other issues on the website that you feel like could be cleared up we could use some help with that.

**Comment by MatthewMeier** [comment]
@BrittGraham 
Here is another topic that would be good to document #125 This will be for the valley bottom tool that is an input for BRAT. Notice that this [issue](https://github.com/Riverscapes/RCAT/issues/11) should be added onto the end of it. This will be documentation that will be done for the [RCAT website](https://github.com/Riverscapes/RCAT).

**Comment by wally-mac** [comment]
@MatthewMeier and @BrittGraham where are you on this? If it's been completed please share links to the documentation here if not can you please let me know what happened (what the hold up is)?  Thanks

**Comment by BrittGraham** [comment]
I will be going through some of these today and seeing what I can update.

**Comment by MatthewMeier** [comment]
@BrittGraham remember that one reason that we are asking you to do this is because there are things that make sense to us because we have been around it more. We want it to make sense to the first time user. It is all right to not know in depth the information that your documenting but we want you to make it comprehendable
