### ISSUE TITLE
Plots and outputs for "Data_Capture_Validation"

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#245]
@mhallerud 
@banderson1618 and myself have created and been working on the validation of BRAT using data capture events/beaver dam locations through field or computer imagery methods. We use this data in order to validate the BRAT outputs for reports that @wally-mac writes up. We would like to implement some additional pieces to the outputs such as plots that relate the observed dam density vs the model density to get as close to a 1:1 ratio as possible but as little under estimate events as possible. For an example of what we have done in the past for validation parameters refer to the Yakama report on box pgs 34-38 (I am not including the link to the report because it is contract confidential). You can find it on box though. 
[Here](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/7-SummaryReport.html) is the documentation about the outputs from the tool.
*Note some of the outputs that were originally created by this tool like dam counts have been shifted over to the BRAT Table portion of the tool and so this is can be referenced now or be eliminated from the "Data_Capture_Validation" script. references to this data include.

**Comment by mhallerud** [comment]
Hey @MatthewMeier, I'm not entirely sure what you're asking for here but let me know if I'm on the right track: Are you looking to automate the table on page 36 of the Yakama report? What about also adding an observed vs. modeled plot (see below) with each point representing values from an individual stream segment? My reasoning for the plot is two-fold: First, observed vs. predicted plots are standard statistical visualizations of model validation. Second, I find a single plot that summarizes model performance a bit simpler and more intuitive. This obviously wouldn't replace the maps, it just might be a nice addition to summarize what is shown in greater detail and complexity on the maps. 
![image](https://user-images.githubusercontent.com/43869036/49681034-ad846080-fa58-11e8-96ef-ae48e0c663f5.png)

**Comment by mhallerud** [comment]
@MatthewMeier Do you also want the symbology added to the relevant fields?

**Comment by MatthewMeier** [comment]
@mhallerud the plot that you illustrated is what we would like to have with some minor changes to it. You are right that we want a trend line but it needs to represent a 1:1 ratio not what is the trend line for the data. This line would represent the model being exactly on with what is actually true. However since this is a capacity model we would like all of the dots to be below the line or right on the line and minimal points above the line. It would be beneficial if we could change the symbology of the points above the line to red and below the line to blue. A in plot legend would be helpful as well. Refer to the following [plots](http://gcd.riverscapes.xyz/Tutorials/GeomorphicInterpretation/morphodynamic-signatures-from-budget-segeregation.html) that @joewheaton has created with the [GCD project](http://gcd.riverscapes.xyz/). Notice that he has a pie chart off to the side. This might be something that the cartographers end up doing but in the meantime get the plot changes done and the legend.
As for the table I would say have the tool just output a excel document that holds all of the data in the attribute table for now and we can visit the specifics on this later.

**Comment by MatthewMeier** [comment]
@mhallerud,
 @braden should have created a new folder in the inputs folder for data capture events(DCE). We will want this optional analysis under a new folder in the outputs_Analysis_"Inter-Comparison" folder.

**Comment by wally-mac** [comment]
@mhallerud, @MatthewMeier and @banderson1618 [here](https://usu.box.com/s/14ih176i9v7xf653hpx01b97ukxvbe6ql) is a draft manuscript that has a good example of what we are looking for.  **See Figure 9**.

**Comment by wally-mac** [comment]
Try the link now... it should work.

**Comment by MatthewMeier** [comment]
Yes that adds some good insight into what they should look like. I think that I would need some personal insight into the figure on the left to know what to look for and why it isn't a linear relationship. I think this would be something we can discuss in person. Thanks for the direction @wally-mac

**Comment by mhallerud** [comment]
@wally-mac Quick question, would you be able to send me the R code for the models these plots are based on so I can better understand exactly how the data is being subset in the cross-validation? It's a little bit unclear in the writing.

**Comment by mhallerud** [comment]
Yes, it's all coded up I just haven't had a chance to do a thorough check yet before I push it to the master branch.

**Comment by mhallerud** [comment]
Here's the latest rendition of the plot:

![predicted_vs_expected_plot](https://user-images.githubusercontent.com/43869036/50187180-804a7480-02da-11e9-8312-d9f3fed85194.png)

The "missing" points were actually just points that were covered by other points with equivalent values. I added a (small) element of randomness to the points so that they don't cover each other up like that, similar to what geom_jitter does in R's ggplot package. Let me know if this is ok and if you want any other changes made.

**Comment by wally-mac** [comment]
@mhallerud, your plot looks good to me.  @bangen and @joewheaton do you have any suggestions for improving the above plot?

**Comment by mhallerud** [comment]
@wally-mac @MatthewMeier Do you think the 1:1 ratio line should be renamed something more useful/understandable to managers?

**Comment by mhallerud** [comment]
Maybe something like "Perfect Prediction" or "Ideal Correlation". A quick google search shows a lot of figures using "perfect line" or "line of perfect agreement".

**Comment by mhallerud** [comment]
@MatthewMeier Working on automating the electivity ratios today. If there is anything of higher priority for me to be working on, feel free to give me a call.

**Comment by MatthewMeier** [comment]
@mhallerud Sounds good use the following [excel sheet](https://usu.box.com/s/6yunsnhob44jhsg488u6kh1d5oxx1irk) for guidance
