### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/pyBRAT#25]
@banderson1618 
I noticed you made a new page under the documentation for the braid handler- unfortunately now there are a couple navigation buttons that are not working.  I took one last look at the [dead link checker](https://www.deadlinkchecker.com/) and noticed the last two buttons are not working (see below).  Let me know if you need more info about how to fix them.
![image](https://user-images.githubusercontent.com/30474526/39269340-c75e3150-488f-11e8-9cd8-306da4eee0a7.png)

**Comment by banderson1618** [comment]
Well, this is a bit embarrassing. I had a typo in the link to the next page, and copied and pasted the same typo. Should be fixed now, thanks for catching this!
