### ISSUE TITLE
Idaho BRAT Dam Censusing Tutorial (Using Chad's ESRI Webmaping)

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#253]
@mhallerud, @BrittGraham, @chadFHC , @GabeStudent1234 , @MatthewMeier , and @banderson1618 [here](https://vimeo.com/310598444/d307902359) is a video tutorial I just cranked out describing my technique for collecting beaver dams using the web app that Chad generated.  Please watch the video and please work on collecting beaver dams when you have time.  It is going to require a team effort to get all of the 84 HUC 8's completed.  We'll need to be systematic and fast as well.  Please let me know if you have any questions.  Thanks!

**Comment by MatthewMeier** [comment]
@wally-mac will do

**Comment by GabeStudent1234** [comment]
I'll be in later today to work on that

**Comment by wally-mac** [comment]
Hey team [here](https://vimeo.com/310605569/94da988ae7) is a short video to clear up the confusion I may have caused in the first video.

**Comment by chadFHC** [comment]
Sounds good.

**Comment by mhallerud** [comment]
10-4, Will do.

**Comment by wally-mac** [comment]
@mhallerud, @BrittGraham, @chadFHC , @GabeStudent1234 , @MatthewMeier , and @banderson1618 [here](https://vimeo.com/310639904/6f23fe3186) is a short video that describes how to keep track of where you have worked with in the watershed.

**Comment by wally-mac** [comment]
@mhallerud, @BrittGraham, @chadFHC, @GabeStudent1234, @MatthewMeier [here](uhttps://arcg.is/0OzD5Ll) is an example watershed where I did the dam collection on. Please refer to this if you have any questions on identifying dam locations.

**Comment by mhallerud** [comment]
@wally-mac I'm having an issue with the link, do you mind updating it?
