### ISSUE TITLE
Changes to Idaho Dam Censusing ESRI Webmap App

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#254]
@chadFHC since it is very difficult to identify lodges with the imagery provided in the web app it is therefore very difficult to identify primary vs. secondary dams.  As such, I would like you to modify the form as followings:  in the **Feature Type** drop-down remove '_lodge_' and '_stock pond_' ( we are not under contract to map stock ponds) and remove the **Dam Type** drop-down altogether.  Please let me know when you can do this and how long it will take to do it for each of the Idaho HUC 8's. If you need to delegate this task please let me know. I'd like to get this done ASAP.

**Comment by chadFHC** [comment]
@wally-mac 
I can do this. Although, if I do this to surveys that already have data, it deletes the data and starts fresh. So, we should just finish the ones that are already started with their current forms. I will update the rest now.

**Comment by wally-mac** [comment]
@chadFHC
