### ISSUE TITLE
Red X?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#256]
Kellerman wrote:

> I’m using BRAT to assess placement of BDAs in the upper Klamath Basin for stream restoration with a group of students.  I have not used BRAT previously and have basic problem off the bat – hate to bug you with it, but…
> 
> We still have the red x over the Toolset & have tried turning on all extensions (both in ArcMap & through Administrator).  Other Suggestions?
>

**Comment by joewheaton** [comment]
What version of ArcGIS are you using? My guess is that the toolbox is not compatible with earlier versions of ArcGIS (e.g. 10.4 or earlier), but I could be wrong. @banderson1618 any thoughts?

While the code is open source, we've never had the development budget to turn this into a more reliable  AddIn and GUI.... we're trying.

**Comment by banderson1618** [comment]
Hi @jherimek, I might be able to help. If you right click on the toolbox with the red x, you should see the option to "Check Syntax". That will open a window telling us what's wrong. Can you post whatever that comes up with on here?

**Comment by JherimeK** [comment]
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\0_BRAT\pyBRAT-3.0.19\Veg_FIS.py", line 13, in <module>
    import skfuzzy as fuzz
ImportError: No module named skfuzzy

So looks like perhaps I need to add skfuzzy - I was under the impression that was not necessary anymore, but maybe I misread

**Comment by banderson1618** [comment]
Yep, that'd do it. We do still use skfuzzy, unfortunately. It would be nice to not have the dependency, but we haven't found a good alternative that isn't just another dependency. Here's a link to the page with instructions on installing skfuzzy, in case you don't have much experience with installing python dependencies:

[http://brat.riverscapes.xyz/Download/ComputerSetup](http://brat.riverscapes.xyz/Download/ComputerSetup)

**Comment by banderson1618** [comment]
Let me know if you're still having problems after that.

**Comment by JherimeK** [comment]
Thanks, just walked through that process, but got following message whn trying to install scikit.fuzzy 
  Could not find a version that satisfies the requirement scikit.fuzzy (from versions: )
No matching distribution found for scikit.fuzzy
I was running from admin cmd prompt.

**Comment by banderson1618** [comment]
Good to hear.

BDWS isn't necessary for most uses, so that's fine. It uses OSGeo, which most people don't have installed, so that's not a surprise.

**Comment by banderson1618** [comment]
I'll go ahead and mark this issue closed.
