### ISSUE TITLE
Additional fields in the BRAT output

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#26]
Purpose: Documentation for relating beaver dam censuses collected in the field or google earth to a recent run of BRAT. 
Creator: Matthew Meier 
Date: 4/30/2018
Steps to creating new fields:
1.	The dams as point shapefiles need to be snapped to the edges of the BRAT table. User needs to define the search radius
2.	Through the spatial join tool to get the counts for the amount of dams that are on each line segment. What you will want is to have the BRAT output as your target features, your join features as the dams point shapefile, the new output feature class as the output polyline file for this tool, join one to one for the join operation, keep all the target features, match option as intersect, and the search radius should not matter because you snapped it to the line(you might not even need the snap with this tool but I did for working through it).  
a.	Note that there will be fields that were created in this from the points shapefile that may desired or not depending on the information in it.
b.	The tool creates a join count field which you will be creating a e_DamCt field that matches this joint count field i.e. how many dams are on each line segment. Description is underlined, the attribute field name is bold, and the specifics of the field name in ArcGIS italicized
•	Empirical: Actual Dam Count
e_DamCt : estimating dam count per segment (double, precision = 0, Scale = 0)
From this information you will run through the following calculations…
Calculating for additional fields… (note all of these will be new fields and could be done through the update cursor function in python but these are the functions as I did them in excel.)
•	Actual Dam Density - These are the adjusted flow types by FHC [dams]
e_DamDens: =(e_DamCt/seg_length)*1000 (double, precision = 0, Scale = 0)
•	Actual Percent of Existing Capacity Ratio - These are adjusted flow types by FHC [dams/km]
e_DamPcC: =IFERROR(e_DamCt/ oCC_EX,0) (double, precision = 0, Scale = 0)
•	Existing Capacity Dam Count defined by category- Product of oCC_EX and Segment Length [dams] 
Ex_Categor: =IF(oCC_EX=0,"None",IF(AND(oCC_EX>0, oCC_EX<=1),"Rare",IF(AND(oCC_EX>1, oCC_EX<=5),"Occasional",IF(AND(oCC_EX>5, oCC_EX<=15),"Frequent",IF(AND(oCC_EX>15, oCC_EX<=40),"Pervasive")))))   (text)
•	Potential Capacity Dam Count defined by category- Product of oCC_PT and Segment length [dams] 
Pt_Categor: =IF(oCC_PT=0,"None",IF(AND(oCC_PT>0, oCC_PT<=1),"Rare",IF(AND(oCC_PT>1, oCC_PT<=5),"Occasional",IF(AND(oCC_PT>5, oCC_PT<=15),"Frequent",IF(AND(oCC_PT>15, oCC_PT<=40),"Pervasive"))))) (text)
•	Existing Capacity Dam Count - Product of oCC_EX and Segment Length [dams] mCC_EX_Ct: 
=( oCC_EX * SegLen)/1000 (double, precision = 0, Scale = 0)
•	Potential Capacity Dam Count - Product of oCC_PT and Segment length [dams] 
mCC_PT_Ct: =( oCC_PT * SegLen)/1000 (double, precision = 0, Scale = 0)
•	Existing to Potential Capacity Ratio - Ratio of actual to potential dam densities [dimensionless ratio between 0 and 1]
mCC_EXtoPT: =IFERROR(oCC_EX / oCC_PT,0) (double, precision = 0, Scale = 0) 
Once these are added to the BRAT shapefile you are done with the additional attributes that I have calculated by hand.

**Comment by banderson1618** [comment]
Hey @MatthewMeier,

Is this related to the statistics on BRAT runs that we talked about in the meeting on Monday, or is this something else?

**Comment by MatthewMeier** [comment]
Yes this is. The word document that I sent to you is the same information and better than this. So refer to that word document for information.

**Comment by banderson1618** [comment]
Sounds good, I'll get on it then.

**Comment by banderson1618** [comment]
@MatthewMeier, I've implemented the non-dam related statistics. Here's an example of the output, run on the Lemhi (because it's what I have on hand right now). Let me know if it looks OK to you.

[SummaryReportOutput.zip](https://github.com/Riverscapes/pyBRAT/files/1968317/SummaryReportOutput.zip)

If you can get me an existing dam dataset, I'll be able to start on that section of the program.

Cheers,
Braden

**Comment by MatthewMeier** [comment]
Sent them over to you via email

**Comment by banderson1618** [comment]
@MatthewMeier, I implemented the dam statistics. I've attached the output of the Lower Yakima, using unsnapped dams and all. It looks like it works to me, but I don't have your critical eye. Let me know if it looks good when you get a chance.

[SummaryReportWithDams.zip](https://github.com/Riverscapes/pyBRAT/files/1975406/SummaryReportWithDams.zip)

Just a thought: should we implement a limit somehow on the Dam Density (e_DamDens) statistic? It's possible that a single dam would snap to an extremely small segment, which could give you a ridiculously large Dam Density for that one reach. It's not a big problem, but if it's an easy fix, we may as well implement it.

**Comment by joewheaton** [comment]
@banderson1618 thanks for this. Please in the future reference the issue by `#26` mention in your commit title or if you're confident that the issue has been fully addressed by `Fix #26` in your commit history. I am going to open a new ticket to combine this and #14. I've changed my mind not on the functionality of what this does, but on where we should save that.
