### ISSUE TITLE
BRAT Project Status Tracking (Internal)

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#261]
@mhallerud @wally-mac 

I put together a more comprehensive BRAT project status tracking Google spreadsheet.  I just shared it with both of you.  You can also view it [here](https://docs.google.com/spreadsheets/d/1c6TsjZD0GlgK58tadOGA2VlrQXKAemZ6MPnSUIWLea0/edit?usp=sharing).  I put together a quick [video](https://youtu.be/v7yTX36dYug).  @mhallerud , could you please populate one of these for the GYE project and share with Wally and I?  Thanks!

**Comment by bangen** [comment]
@mhallerud I got the GYE tracking doc you shared.  Thanks for getting it going!  Once you populate the HUC8 sheets could you please add a column that specifies which project the HUC8 falls within (i.e., Idaho, GYE ETAL).  Thanks!

**Comment by mhallerud** [comment]
@bangen @wally-mac Updated (Google Sheet)[https://docs.google.com/spreadsheets/d/12wagTe21zK6IgPUAqivUx_4c5jo02IPvstBlzdZ9rQE/edit?usp=sharing] for the GYE. 
@bangen I was not aware of the upstream drainage area issue with the major rivers, so at some point you'll probably need to walk me through that either via another meeting or email (whichever is easier).

**Comment by mhallerud** [comment]
@bangen @wally-mac Here is the tracking sheet for [Idaho](https://docs.google.com/spreadsheets/d/1ER65qFlc44K6U-xHFpwHLjSpXrQfM508Dz0qGa7CxxQ/edit?usp=sharing)

**Comment by mhallerud** [comment]
@wally-mac @banderson1618 @bangen @CHafen @chadFHC See above for links to status tracking documents for the Idaho and GYE BRAT projects.
