### ISSUE TITLE
Highflow regional regression equations wrong for Idaho?

### ISSUE THREAD

**Issue by mhallerud** [Riverscapes/pyBRAT#262]
@bangen 
@wally-mac and I were reviewing the Middle Salmon Panther Creek results this afternoon and realized that a large portion of the network is stream power limited. The highflow stream power values seem much too high, even after double checking and rerunning those calculations: 
![panther creek high flow](https://user-images.githubusercontent.com/43869036/52604118-d3e2c580-2e26-11e9-9e46-5d77541e8936.PNG)

In comparison, the baseflow stream power appears fairly normal:
![image](https://user-images.githubusercontent.com/43869036/52604176-055b9100-2e27-11e9-95f1-f40ecb8a50bf.png)

I'm thinking that the regional regression curves (found [here](https://pubs.er.usgs.gov/publication/sir20165083) are erroneous and am concerned about applying them to all of Idaho. I know that calculating new regression curves is possible, but I do not know how to build those quite yet and am not sure if we have the time/budget to do so.

**Comment by bangen** [comment]
@mhallerud 

Which hydrologic region does Panther Creek fall in?  I can take a look on Box if the latest run is up.

**Comment by mhallerud** [comment]
@bangen It's in Idaho region 6_8. The latest run is [here](https://usu.box.com/s/0ix0t3durjd1fmrgist18mti3gci8l3a). Thanks!

**Comment by bangen** [comment]
@mhallerud 

The equations in the doc seem fine.  The issue seems to either be which equations were used and/or the precip value that was used.  I detail things in [this video](https://youtu.be/RKknuWpCq58).  Let me know if you have any questions.

**Comment by mhallerud** [comment]
@bangen Got it, thanks for the help. I grabbed the wrong equation and am rerunning it now.
