### ISSUE TITLE
Automating Perennial Network (Internal)

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#264]
@wally-mac @mhallerud 

The automated perennial code is as fine-tuned as I'm going to be able to get it for now.  That being said, I think it does a pretty darn good job and I like that it's an objective approach.  Here [is a video](https://youtu.be/rgKUYYuNbLc) giving an overview of what the script does (...sorry it's not as brief as I originally intended...).  Here's a second, much shorter, [video](https://youtu.be/6HLKSaWwPQs) with a few items I forgot to mention.

@mhallerud I put the code under the 'SupportingTools' folder.  It's not written as a batch script but should be easy enough for you to turn it into one.  Holler if you need help.

@wally-mac a few questions for you:

- What are your thoughts about including intermittents as I outlined in the video(s)?
- What are your thoughts on using the code to regenerate the perennial networks for Idaho and TNC?  From the 4 basins I worked with on the code the manual networks derived have a lot of canals, etc.

**Comment by wally-mac** [comment]
@bangen thanks for the informative videos on your automated perennial coding.  

- Here is a link to a [video](https://vimeo.com/319529632/e31f21ef33l) that describes my feedback on including intermittents.
- Because the manual approach includes so many canals I think we **should use** your automated approach for Idaho and TNC.

**Comment by bangen** [comment]
@wally-mac The video link isn't working.  Is it still uploading?  Thanks!

**Comment by wally-mac** [comment]
Try it now.

**Comment by bangen** [comment]
@wally-mac I updated the script based on your feedback.  You can check out the changes in [this video](https://youtu.be/tRxoPjUHavA).  Think we're ready to roll this out unless there are any other changes you'd like to see.

**Comment by bangen** [comment]
@mhallerud Just a quick FYI that I updated the perennial network script based on Wally's feedback.  There is now just a single script.  So if you previously grabbed it you'll want to pull again before running the code.

**Comment by wally-mac** [comment]
Nice work @bangen! I really like the way you have it set-up. No changes needed.
