### ISSUE TITLE
pyBRAT-3.0.19 SupportingTools folder is empty

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#266]
Hi BRAT team,

     I've been plugging away, but have found that my SupportingTools folder is empty. I have attached a screenshot to show this. Is this common and does anyone have a workable solution. Appreciate the help as always. Cheers,

Andy
![Empty SupportingTools folder](https://user-images.githubusercontent.com/48166366/54097576-cfa2bd00-437e-11e9-9dcb-b53783fc3cb5.JPG)

**Comment by andrewsechrist100** [comment]
Do I run these supporting tools, which are in the appropriate Supporting Tools folder in pyBRAT-3.0.19 in
 my File Explorer in Windows 10, from within ArcMap or as stand-alone tools using something like 
PyScripter? I need some guidance with either method. If I run them from within ArcMap, do I bring them
 into a newly-created Toolbox with a .py or .tbx extension, or does it not matter which? When I create a 
new .pyt toolbox, there is no Add drop-down when I right click it, but there is for a newly-created .tbx 
toolbox (I can add a script or a tool). Or, do I somehow just bring in the "SupportinTools" toolbox 
wholesale from the SupportingTools folder in File Explorer. Finally, how do I know which parameters to 
set to which data types if I need to add the scripts one-by-one? Thanks,  

Andy

**Comment by banderson1618** [comment]
These are meant as standalone scripts that can be run from the command line or from an interpreter like PyCharm. Whatever method you have to run a Python script should work fine for these scripts, as long as it uses the python.exe in the ArcGIS folder.
