### ISSUE TITLE
BRAT Crashing on Project Builder

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#268]
@banderson1618 

I'm trying to run the Truckee in ArcMap.  I pulled the main branch so everything should be clean.  The tool crashes on the first step.  See the error message below.  The raster exists (it was copied into the correct `03_Topography/DEM_01` folder) but appears to be crashing when applying symbology.  I'm running 10.6. Need this one resolved ASAP.  Thanks.

```
Executing: BRAT_project_tool C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\BRAT\CRM_Run_01 "TNC BRAT" 16050102 Truckee C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\LANDFIRE\LANDFIRE_140EVT.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\LANDFIRE\LANDFIRE_140BPS.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\NHD\NHD_24k_300mReaches.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\DEM\NED_DEM_10m.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\LANDFIRE\LANDFIRE_140EVT.tif C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\ValleyBottom\Provisional_ValleyBottom_Unedited.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\RoadsRails\tl_2017_county_roads.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\RoadsRails\tl_2017_rails.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\NHD\NHDCanals.shp C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\LandOwnership\NationalSurfaceManagementAgency.shp # C:\etal\Shared\Projects\USA\California\SierraNevada\BRAT\wrk_Data\Truckee_16050102\NHD\NHD_24k_Perennial.shp
Start Time: Thu Mar 14 09:51:42 2019
Running script BRAT_project_tool...

Traceback (most recent call last):
  File "<string>", line 195, in execute
  File "C:\etal\LocalCode\pyBRAT\Main\BRATProject.py", line 108, in main
    make_topo_layers(topo_folder)
  File "C:\etal\LocalCode\pyBRAT\Main\BRATProject.py", line 217, in make_topo_layers
    make_layer(dem_folder_path, dem_file, "DEM", dem_symbology, is_raster=True)
  File "C:\etal\LocalCode\pyBRAT\Main\SupportingFunctions.py", line 105, in make_layer
    raise arcpy.ExecuteError(err)
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000860: Output raster layer name: is not the type of Raster Layer, or does not exist.
Failed to execute (MakeRasterLayer).


Failed to execute (BRAT_project_tool).
Failed at Thu Mar 14 09:52:00 2019 (Elapsed Time: 17.45 seconds)
```

**Comment by banderson1618** [comment]
@bangen, can you send me the data you were using for this? It would be good to be able to try to replicate the problem.

**Comment by bangen** [comment]
@banderson1618 It was the Truckee basin in the TNC project.  You can grab the data on Box.  When you test please do so both in the BRAT Arc Toolbox and in Python to make sure it's working in both platforms.

**Comment by banderson1618** [comment]
@bangen I couldn't replicate your bug with any of the DEMs found in the folder [here](https://usu.app.box.com/folder/48416727731). Am I looking in the wrong spot?

**Comment by banderson1618** [comment]
I pushed a temporary solution. I moved all the making layer code to the end of the program, and put in a try except block that will pass on this specific error code. You won't make the layers we want, but you will be able to progress the tool.

**Comment by bangen** [comment]
Did you test in both ArcMap (which version) and in python?

**Comment by banderson1618** [comment]
I tested in ArcMap, since that seems to be where you found the bug. Should I try from the command line?

**Comment by banderson1618** [comment]
@bangen, should I try it on the command line?

**Comment by bangen** [comment]
@banderson1618 what version of Arc did you test?

**Comment by banderson1618** [comment]
10.6

**Comment by bangen** [comment]
@banderson1618, go ahead and run on the command line for those 2 sites.  Call the run folders 'CR_Run01'.  Let me know when they're up on Box so Wally and I can go through the outputs.

**Comment by banderson1618** [comment]
Which two sites do you want me to run? I'm not sure which two of the four folders in the BRAT folder you want me to run.

**Comment by banderson1618** [comment]
Also, do you want me to run all the way through BRAT, or just the project builder?

**Comment by bangen** [comment]
The Truckee and the Lemhi.  Through the entire model using the 'main' branch.
