### ISSUE TITLE
Truckee strategy map iterations

### ISSUE THREAD

**Issue by kwilsonh2o** [Riverscapes/pyBRAT#269]
Hello Braden,

Attached is a revised table for the strategy map iteration for the Truckee River based on yesterday's conversation with Wally and Rodd.

Kristen

[BRAT legend 3.19.2019.xlsx](https://github.com/Riverscapes/pyBRAT/files/2986023/BRAT.legend.3.19.2019.xlsx)

**Comment by banderson1618** [comment]
Here's the layer package that we get for management with that setup, except for without the land use stuff (because I haven't figured out how to get that as an input). Let me know what you think.

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/2990043/Management.zip)

**Comment by kwilsonh2o** [comment]
Something strange is happening. What was showing up as 'medium restoration-veg' is now showing as 'low restoration'.  'Medium restoration' and 'high restoration' reaches are missing.  None of the restoration criteria changed.  I'm guessing this is due to trying to use the road crossing layer only (iPC_Roadx).  Please try with the combined conflicts layer, see attached.  


Strategies   to promote beaver dam building | risk | historic   departure dams | historic   potential dams (OCC_HPE) | current potential   dams (OCC_ET) | OCC_HPE/OCC_EX | historic veg   departure (OVC_PT-OVC_ET) | land use | infra-structure
-- | -- | -- | -- | -- | -- | -- | -- | --
Relocation and   conservation | split into individual risk factors | - | ≥15 | ≥15 | - |   | no urban | >100
High   restoration potential | - | ≥5 | ≥5, <15 | >1 |   | no   urban |  
High   restoration - veg first |   | ≥5 | ≥5, <15 | >1 | ≥5 | no urban |  
Medium   restoration | - | ≥5 | <5 | >1 |   | no urban |  
Medium   restoration - veg first |   | ≥5 | <5 | >1 | ≥5 | no urban |  
Low   restoration |   | ≥1,   <5 | <5 | >1 |   | no urban |  
Low   restoration potential - veg first | - | ≥1,   <5 | <5 | >1 | ≥5 | no urban |  
Living with beaver solutions - infrastructure |   |   | ≥5 | - |   | - | oPC_Dist≤30
Living with beaver solutions - urban and ag use |   |   |   | ≥5 | - |   | urban   or ag |  

[BRAT legend 3.20.2019.xlsx](https://github.com/Riverscapes/pyBRAT/files/2990438/BRAT.legend.3.20.2019.xlsx)

**Comment by kwilsonh2o** [comment]
The table didn't copy here correctly.  Please look at the excel spreadsheet attached.  The table is dated 3.20.19.

**Comment by banderson1618** [comment]
[Management.zip](https://github.com/Riverscapes/pyBRAT/files/2994066/Management.zip)

**Comment by kwilsonh2o** [comment]
Looks good Braden.  Is it possible to run a few other watersheds to see how it does across the state?
Tomales Bay, South Fork Kern, North Fork Feather, and Shasta

**Comment by banderson1618** [comment]
Here's Tomales Bay:

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/2997860/Management.zip)

I'll try to run at least two more today, and post them here when they're complete.

**Comment by kwilsonh2o** [comment]
Awesome.  Will run this past project partners to get their feedback.

**Comment by banderson1618** [comment]
Here's South Fork Kern:

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/2998211/Management.zip)

**Comment by banderson1618** [comment]
North Fork Feather:

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/2998371/Management.zip)

**Comment by banderson1618** [comment]
Shasta:

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/3005096/Management.zip)

**Comment by kwilsonh2o** [comment]
Thank you. Will set up a time to share with project partners and get their input. I’m out of the office through Thursday this week.

Sent from my iPhone

On Mar 25, 2019, at 12:23 PM, Braden Anderson <notifications@github.com<mailto:notifications@github.com>> wrote:


Shasta:

Management.zip<https://github.com/Riverscapes/pyBRAT/files/3005096/Management.zip>

**Comment by banderson1618** [comment]
Carson:

[Management.zip](https://github.com/Riverscapes/pyBRAT/files/3014835/Management.zip)

**Comment by kwilsonh2o** [comment]
Downloaded them all and am sending to partners to review by the end of next week.  The Tomales Bay results are showing the Truckee.  Please send Tomales again when you have a chance.

**Comment by kwilsonh2o** [comment]
Another model iteration for Truckee.  Please run the Truckee using these values.  Please label it Campos.
[BRAT strategy map legend_BRC.xlsx](https://github.com/Riverscapes/pyBRAT/files/3035782/BRAT.strategy.map.legend_BRC.xlsx)

**Comment by bangen** [comment]
Including the final strategy map legend for reference

[BRAT_StrategyMapLegend_6.7.19_Doc.xlsx](https://github.com/Riverscapes/pyBRAT/files/3278396/BRAT_StrategyMapLegend_6.7.19_Doc.xlsx)
