### ISSUE TITLE
UnboundlocalError

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#27]
Do you have any idea of what could be causing this error. I am running ArcGIS10.6 and it works for other datasets so I redownloaded and cleaned up some things but I am getting this error
![image](https://user-images.githubusercontent.com/30604787/39728076-80ea4984-5212-11e8-870f-42698e3b2be0.png)
I sent the project folder to Sara in an email

**Comment by bangen** [comment]
Fixed issue in the latest release (v 3.0.9).  I ran the input data you sent and it runs fine in the new version.  I'm using Arc 10.5 so let me know if you still run into any issues in 10.6.
