### ISSUE TITLE
Python interpreters do not recognize method spatialReference in call from line 38

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#270]
Hello ETAL,

     I've made some progress since my last question. Some of it may seem trivial, but getting my
 python.exe into the Environmental Variables and correctly formatting PyCharm (after PyScripter
 corrupted some of my data) has taken me some research and time (a full day ;) ). No matter 
whether I run segmentNetwork.py from the Command Prompt, PyScripter (now uninstalled), or
 PyCharm, though, I am getting an attribute error that the method spatialReference does not
 exist. On one run I entered (32135) after spatialReference (i.e. spatialReference (32135)), as that
 is the EPSG code for NAD 83 State Plane South Dakota South...., but still got the error. Can 
anyone help me understand what is happening here? Thanks again!,

Andy
![Capture](https://user-images.githubusercontent.com/48166366/55004179-bcf7cd00-4fa7-11e9-8c84-ad503b77237a.JPG)

**Comment by bangen** [comment]
Glancing at your screenshot looks like there are a few issues with your 'nhd_flowline_path':

- Missing file extension 
- Use of single backlash (i.e., '\').  In Python single back slashes are escape characters.  Either replace with double backslashes (e.g., "C:\\BRAT\\NHD\\MyNetwork.shp") or include a lower case 'r' in front of your path string (e.g., r"C:\BRAT\NHD\MyNetwork.shp")

Try those changes and let us know if you're still running into issues.

**Comment by andrewsechrist100** [comment]
Hi Bangen,

      I tried those fixes and they solved that issue :). I then received an "ExecuteError: ERROR 999999: Error 
executing function. The Geometry has no Z values." Should I not have included a filename in the 
"outpath" variable? It seems to me the directions state to do so. Likely it's another issue. I appreciate
 your help,

Andy
My attachments are probably overkill, but not sure what's important here, so.....

![Capture1](https://user-images.githubusercontent.com/48166366/55038475-f43d9c80-4fee-11e9-86d8-043d06feb4c9.JPG)
![Capture2](https://user-images.githubusercontent.com/48166366/55038478-f7388d00-4fee-11e9-95f8-67653e4e606a.JPG)
![Capture3](https://user-images.githubusercontent.com/48166366/55038481-f9025080-4fee-11e9-8616-cf80232b84c1.JPG)

**Comment by andrewsechrist100** [comment]
I doubt this matters bangen buuuuttt, just to overwhelm you some more ;), I have attached the folder
 contents that the shapefile is in. Thank you again,

Andy
![Capture4](https://user-images.githubusercontent.com/48166366/55039067-c5c0c100-4ff0-11e9-82a4-834f30db2c18.JPG)

**Comment by bangen** [comment]
@andrewsechrist100 you may have already resolved this, but wanted to let you know that I added a line to the segment network script that should fix the z value error message (commit c28a18d).  I'm going to close this for now, but if you're still running into the issue feel free to comment and re-open the issue.
