### ISSUE TITLE
Minimum Slope Values

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#271]
@wally-mac Documenting our conversation earlier today.  

Stream power is calculated using reach slope (`iGeo_DA`).  In BRAT, reach slope (m/m) is calculated using the minimum DEM Z values within a 30 m buffer of the reach start and end points.  We occasionally see reaches with extremely low slope values (e.g., 0.000001).  Most of the values that are this low are artificial and simply an artifact of the geo-processing workflow and input data.  The main issue is the effect that slope has on stream power values.  For a given reach the effect can be on the order or magnitudes difference.  

To address the issue we decided to enforce a minimum reach slope.  Based on the literature, a slope of 0.001 m/m (0.1%) is defensible (see Table 2.2 below).  This corresponds with typical slope values for dune-ripple channel types.

@wally-mac, I'm not sure if it's best to just 'correct' the slope in the iHyd script or to override the value in the BRAT table.  I'm leaning towards the first option (in the iHyd script) for 2 reasons:
1. No need for techs to re-run the BRAT table on data that's already been processed
2. I'm never a big fan of overriding values

Thoughts?

Here's the reference table.  From Bisson et al 'Valley Segments, Stream Reaches, and Channel Units'

![Table2 2](https://user-images.githubusercontent.com/6502954/55194115-efe7bf80-5165-11e9-8d8b-bcc7bc721187.PNG)

**Comment by wally-mac** [comment]
@bangen, thank you for this post.  I agree with you. Let's just 'correct' the slope in the iHyd script. Thank you!
