### ISSUE TITLE
No durational flow values for South Dakota

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#272]
Hello ETAL,

I spoke with an employee of SD USGS today and he told me that SD does not calculate durational flows (i.e. flows exceeded a certain proportion of the time - 80% suggested for iHYDE), only peak flows. I've looked over gage point data, and this is accurate. Will this make the BRAT model impossible for me to utilize or are there ways for me to still get through the iHYDE step of the process? Thank you,

Andy Sechrist

**Comment by banderson1618** [comment]
iHyd is not critical for the model. It primarily gives us information on how powerful a stream is, which tells us when blowouts happen, but this is not generally the limiting factor, depending on what streams you care about. Using default iHyd values will still give a useful model, even if not necessarily ideal.

**Comment by andrewsechrist100** [comment]
Well, that is definitely good news. Thank you Braden. I had submitted another question on 3/26. It looks like it is Issue #270 in Riverscapes / pyBRAT. Bangen had issue my initial question on this Issue and got me over a hump, but I haven't heard about the second. The second involves an error I am getting: "the Geometry contains no Z Values." Is it possible for you to look into that? In any case, thanks again,
Andy Sechrist
    On Monday, April 1, 2019, 1:31:06 PM CDT, Braden Anderson <notifications@github.com> wrote:  
 
 
iHyd is not critical for the model. It primarily gives us information on how powerful a stream is, which tells us when blowouts happen, but this is not generally the limiting factor, depending on what streams you care about. Using default iHyd values will still give a useful model, even if not necessarily ideal.

**Comment by mhallerud** [comment]
@andrewsechrist100 This is a common issue especially when running in a Python GUI instead of ArcMap and when shapefiles are manipulated between BRAT steps. The Z-values essentially represent elevation. You can either add Z-values (see [this ESRI help post](https://support.esri.com/en/technical-article/000012292)) or disable the warning in Python using `arcpy.env.outputZFlag = "Disabled"`. Having no Z-values should not impact the results.
