### ISSUE TITLE
BRAT not finding veg data

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#273]
I just noticed that my veg wasn't being picked up by my command line run of BRAT Table. This is what I talked about in the meeting with @wally-mac, @bangen, and @mhallerud. This is where I'll be tracking problems that arise with that.

**Comment by bangen** [comment]
Was only an issue for Braden running code via the command line.  Not sure if he resolved or not.  Recommend other users run the tool via ArcMap toolbox or in Python interpreter.
