### ISSUE TITLE
Updates based on manager feedback

### ISSUE THREAD

**Issue by mhallerud** [Riverscapes/pyBRAT#275]
@wally-mac @bangen @banderson1618 

Just wanted to get some maps up on Git before our meeting tomorrow:

**1. Adding land ownership to the layer package and assigning land ownership to each reach**
![image](https://user-images.githubusercontent.com/43869036/55517541-fc6c8c00-562d-11e9-84ae-126fd1125562.png) 

- How do we want to assign symbology in the layer package? By agency (USFS, BLM, USFWS, BoR, etc.) or just federal, state, private, and unknown?

- Do we want just the input land ownership polygons or also an intermediate polyline showing land ownership for reach?
 
**2. Calculating distance from private land for each reach**
![image](https://user-images.githubusercontent.com/43869036/55517309-47d26a80-562d-11e9-8141-fb16b9a5b7f4.png)

- Do we want to include these values into the conservation restoration model somehow?

**3. Finding points of diversion and distance to points of diversion**

- I'm having a harder time with this one. Using Intersect_analysis gives output with canal reaches next to each other flagged as points of diversion:
![image](https://user-images.githubusercontent.com/43869036/55518280-abaa6280-5630-11e9-81ae-a3ee1bfa178e.png)

- I also decided to only use the perennial network for this, since I'm assuming that's where water is being pulled from.

- Questions going forward: Do we want to include points of diversion in the risk model, or just in the layer package?

**4. Adding conservation restoration field based on dams present and estimated capacity**
![image](https://user-images.githubusercontent.com/43869036/55520263-b0731480-5638-11e9-8697-c325d6c53052.png)

- Should the threshold for being classified as conservation (observed densities are 25% of capacity) be lowered at all?

- Should this be included in the conservation restoration model or stay as a separate layer?

**Comment by wally-mac** [comment]
Hi @mhallerud,

First off, let's try these out in a development branch and run it in the Jordan watershed, Idaho to test it.
Here are my short and sweet answers to your questions:

1. By agency (USFS, BLM, USFWS, BoR, etc.) 
2. I think we want to include these values into a new layer called "priority beaver translocation", which will be a copy of conservation restoration model and these new outputs. 
3. Similar to "stream crossings" we want "points of diversion" in the risk model.
4. Let's try a 25% of capacity as a threshold starting point. Let's keep as a separate layer.
