### ISSUE TITLE
Am I configuring the path variables incorrectly?

### ISSUE THREAD

**Issue by andrewsechrist100** [Riverscapes/pyBRAT#278]
Hello,

     I had to switch gears as PyCharm became corrupted on my desktop and I couldn't locate the 
2.7 version again. So, I am using the Command Prompt in Windows and modifying the code with
 Spyder. The CP won't open the shapefile I specify in the variable within segmentNetwork.py, 
though, so am I configuring the variable value incorrectly? Thank you,

Andy Sechrist
![Capture](https://user-images.githubusercontent.com/48166366/56100745-25203b80-5ee2-11e9-8aab-713e6540b48d.JPG)
![Capture2](https://user-images.githubusercontent.com/48166366/56100748-26e9ff00-5ee2-11e9-8fdb-05c393c04fdf.JPG)

**Comment by andrewsechrist100** [comment]
Hi Bangen,

     I just have not been able to work my way through correctly configuring PyCharm on my computer. I 
did it once, but cannot seem to duplicate whatever I did before. I lost it when my system became 
corrupted somehow. Are you willing to work me through setting up PyCharm? I'd really like to have it 
running correctly for this project and beyond. 
      First, I could only download PyCharm x64 this time, so is that sufficient? Also, I have ArcGIS 10.5.1. Do I need any kind of an Anaconda environment to go with these? As of now, I have only the Python 2.7 that comes with ArcGIS on my computer and it is not a networked computer. I did not import any settings when installing PyCharm. And, I chose 'Skip Remaining and Set Defaults." C:\Python27\ArcGIS10.5 is set as a Path environment variable. So, in PyCharm I set "Add Python Interpreter" with the 'New Environment' radio button clicked to: Location -> C:\Users\Andy\venv and Base Interpreter -> C:\Python27\ArcGIS10.5\python.exe. I am still, though, receiving the "No module named Arcpy error." Is this something that you can help me with Bangen?  Andy

**Comment by bangen** [comment]
It's been so long since I set up PyCharm, it's a little hard for me troubleshoot.  From the screenshots it looks like you have you're setting up the interpreter correctly within PyCharm itself.  Have you looked at [this thread](https://gis.stackexchange.com/questions/14713/setting-up-pycharm-to-reference-arcpy)?

**Comment by andrewsechrist100** [comment]
Thank you very much for that link Bangen! That is what I used the first time to correctly set up PyCharm, 
but I could not locate the page again when I searched for it. The useful part is about 3/4 of the way 
down that begins, "A lot has changed since the recent update hence answering this to align with the 
PyCharm version 2018 interface:" Very helpful! I have now set up PyCharm again and tried to run 
SegmentNetwork, but got the following error: TypeError: 'geoprocessing spatial reference object' object 
is not callable. Do you have any suggestions for this? Thanks again,  Andy
![Capture](https://user-images.githubusercontent.com/48166366/57185220-6da19800-6e95-11e9-92c0-1a5bd0e4a65d.JPG)
![Capture2](https://user-images.githubusercontent.com/48166366/57185222-6f6b5b80-6e95-11e9-8593-cccd97903493.JPG)

**Comment by bangen** [comment]
Can you zip and attach your shapefile (and associated files)?  I can take a quick look to see if it's a simple fix.

**Comment by andrewsechrist100** [comment]
Hi bangen,
I used 7-Zip for this. Thank you,  Andy

[PerennialOnly.zip](https://github.com/Riverscapes/pyBRAT/files/3169263/PerennialOnly.zip)

**Comment by bangen** [comment]
@andrewsechrist100 are you still having this issue?  I ran your data on my pc and didn't run into any issues.
