### ISSUE TITLE
Which ShapeFile and Attributes Contain BRAT outputs?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#283]
@wally-mac can you please specify which ShapeFile and attribute contains the following three BRAT outputs (for the web map):

* Existing dam capacity
* Historic dam capacity
* Beaver management 

Hopefully these are three separate attributes on a single ShapeFile. If they are not, can you also provide the attribute that I can use to join the output ShapeFiles together.

My goal is to produce a single ShapeFile with four attributes; the three above plus some unique feature ID.

**Comment by mhallerud** [comment]
@philipbaileynar Existing and historic dam capacity are found in the combined capacity model shapefile. There are two fields for existing dam capacity, `oCC_EX` which represents estimated dams per kilometer and `mCC_EX_CT` which represents the estimated number of dams on the given reach.  Beaver management outputs are all found in the conservation restoration model shapefile and those fields include `oPBRC_UI` which corresponds to risk of undesirable dams (i.e., risk of infrastructure damage), `oPBRC_UD` which corresponds to unsuitable or limited dam building opportunities, and `oPBRC_CR` which corresponds to conservation restoration opportunities. The symbology for these fields can be found on the Code page in the BRATSymbology folder.

**Comment by wally-mac** [comment]
@mhallerud, thanks. For @philipbaileynar can you please clarify what field the historic capacity is.

**Comment by mhallerud** [comment]
@wally-mac @philipbaileynar Historic dam capacity is `oCC_HPE` for the density and `mCC_Hpe_CT` for the count. We focus on the density rather than the count, but just in case that's something you're interested in those mCC fields are the ones to look for.

**Comment by mhallerud** [comment]
@philipbaileynar These links may help if you have further questions about the fields in BRAT outputs:

[BRAT v3.0 Outpus](http://brat.riverscapes.xyz/Documentation/Documentation%20by%20Version/Outputs/WorkingWithBRATv3XOutputs.html)
[BRAT v2.0 Outputs](http://brat.riverscapes.xyz/Documentation/Documentation%20by%20Version/Outputs/WorkingWithBRATOutputs.html)

**Comment by philipbaileynar** [comment]
Thanks @mhallerud 

Can you confirm that the `SegID` field uniquely identifies the same feature across all output ShapeFiles?

My intent is to join the necessary output ShapeFiles on the SegID field and then produce a single ShapeFile with the following attributes:

* SegID
* SegLen
* oCC_EX - dams per kilometer
* mCC_EX_CT - dams on the given reach
* oPBRC_UI - risk of undesirable dams
* oPBRC_UD - unsuitable or limited dam building opportunities
* oPBRC_CR - conservation restoration opportunities
* oCC_HPE - Historic dam capacity density
* mCC_Hpe_CT - Historic dam capacity count

**Comment by mhallerud** [comment]
@philipbaileynar The conservation restoration output should already have all fields from previous outputs copied over. If you do join shapefiles anyways, I would use the `ReachID` field as that is guaranteed to be unique. I think `SegID` is pulled over from the NHD data which could lead to issues.

**Comment by philipbaileynar** [comment]
I have searched around and I don't see several of the attributes listed above. I also don't see ReachID... I'm going to close this issue and reopen a new one with a different slant on this request.
