### ISSUE TITLE
Does Idaho BRAT include HUC8s that don't flow into the Columbia?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#285]
Does the et-al effort to produce BRAT for Idaho include the southeast corner of Idaho that doesn't flow into the Columbia?

![Screen Shot 2019-05-07 at 3 54 12 PM](https://user-images.githubusercontent.com/8645379/57337988-82be3700-70e0-11e9-9733-611d98932274.png)

**Comment by wally-mac** [comment]
Very few. Just the SE conner that are blank on the map above.
