### ISSUE TITLE
Landfire questions

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#286]
I have a few quick questions about Landfire datasets:

1. How many distinct classes of original Landfire vegetation are present in all of Idaho?
1. How many distinct classification **schemes** are using using for BRAT within Idaho? @wally-mac mentioned that sometimes you use a different reclassification of Landfire data depending on whether a particular valley is wet or dry. I am calling each different reclassification a "scheme" and I'm curious roughly how many different schemes you are using over all of Idaho?

**Comment by wally-mac** [comment]
@mhallerud see Philip's questions above. Can you please attempt to address them and I can help where needed.

**Comment by wally-mac** [comment]
Great questions @philipbaileynar. I generated a [video](https://vimeo.com/339333875/233c09460a) to answer these questions at a high level. This is the same video used in issue #287. @mhallerud can you please address Philip's Idaho specific questions?

**Comment by mhallerud** [comment]
@philipbaileynar The 2016 LANDFIRE data isn't available for all of Idaho so we're merging it with 2014 data where needed. For the full project area (including parts of watersheds outside of Idaho) there are 128 classes for the 2016 existing vegetation, 129 for the 2014 existing vegetation, 221 for the 2016 historic vegetation, and 267 for the 2014 historic vegetation. There is a bit of overlap between the existing and historic classes and their extents, plus some overlap across classes where the class name is the same for multiple raster values. 

We have 10 classification schemes for Idaho based on the EPA Level 3 Ecoregions. Here are the number of classes by ecoregion:
- Blue Mountains (2016 LANDFIRE): 99 existing vegetation classes, 81 historic vegetation classes
- Central Basin and Range (merged 2014 and 2016 LANDFIRE): 183 existing vegetation classes, 110 historic vegetation classes
- Columbia Plateau (2016 LANDFIRE): 85 existing vegetation classes, 87 historic vegetation classes
- Idaho Batholith (2016 LANDFIRE): 99 existing vegetation classes, 115 historic vegetation classes
- Middle Rockies (2016 LANDFIRE): 100 existing vegetation classes, 125 historic vegetation classes
- Northern Basin and Range (merged 2016 and 2014 LANDFIRE): 188 existing vegetation classes, 139 historic vegetation classes
- Northern Rockies (2016 LANDFIRE): 85 existing vegetation classes, 112 historic vegetation classes
- Snake River Plain (2016 LANDFIRE): 114 existing vegetation classes, 160 historic vegetation classes
- Wasatch and Uinta Mountains (merged 2016 and 2014 LANDFIRE): 186 existing vegetation classes, 101 historic vegetation classes
- Wyoming Basin (merged 2016 and 2014 LANDFIRE for existing, 2016 only for historic): 141 existing vegetation classes, 42 historic vegetation classes

Hope this helps, let me know if you have further questions on the subject.

**Comment by bangen** [comment]
@philipbaileynar I'm going to close this for now.  Feel free to re-open if necessary.
