### ISSUE TITLE
What scale are hydrologic equations applied?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#287]
I am reviewing the BRAT [hydrologic equation instructions](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/5-iHydAttributes.html) and I'm curious how many "regions" are required per HUC8?

For example, to process the typical Idaho HUC8 does it take one, two or three sets of `Q2` and `QLow` equations?

I guess another way of asking this question is, what is the region identifier in the aforementioned documentation? Does it refer to a specific level of NHD hydrologic unit?

**Comment by wally-mac** [comment]
Great questions @philipbaileynar. I generated a [video](https://vimeo.com/339333875/233c09460a) to answer these questions. This is the same video used in issue #286.

**Comment by philipbaileynar** [comment]
Thank you!
