### ISSUE TITLE
Typical Max Drainage Area?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/pyBRAT#288]
@mhallerud what is a typical or range of the "max drainage area" value that you use when running the combined FIS model please?

**Comment by mhallerud** [comment]
@philipbaileynar The drainage area thresholds are extremely variable based on the topography of the watershed and how much upstream drainage area they represent. For example, it's around 800 for the Yellowstone Headwaters compared to 18,000 for the Upper Klamath River. See [here](https://usu.box.com/s/7w5mawvoaycnzm7po5knjiv20fwckp8q) for example thresholds throughout California.

**Comment by philipbaileynar** [comment]
That's perfect @mhallerud. Thanks!
