### ISSUE TITLE
Conversation about where Field App Can go

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#29]
From @webernick79:

Some more ideas for validation workflow. These are just concept what could work and are not meant to be finished products

This example shows how Arc Explorer and Survey123 work together to allow offline data collection: 
![2018-05-09_152408](https://user-images.githubusercontent.com/9723905/39840569-146f76a8-539d-11e8-84b7-43bcdec30593.png)
https://www.youtube.com/watch?v=26rqpWeay-o , this makes use of a vector tile package as a basemap, and is brought into Arc Explorer using a the mobile map package, which also launches survey 123 to record validation observations.

The survey 123 data would then be available in as a layer in ArcOnline. This can be used in a web map or app, here’s an app example: https://www.youtube.com/watch?v=ieZPHtKUPxk

Let’s chat about limitations of this approach and others soon and decide where to go. If this is a route we consider I would need to start getting final layers to develop Basemaps and validation layers etc…..

**Comment by webernick79** [comment]
@joewheaton Let's try to get some feedback on final workflow early next week.

**Comment by wally-mac** [comment]
@joewheaton and I talked today (5/10/18) and attempted to determine what the BRAT app should allow the user to do. We agreed that the main thing the app should do is address the same questions that the BRAT capacity model assesses: 
1.	 Is the stream segment a reliable water source for dam-building beaver?
2.	What is the forage and building material value (0-4) within 30 meters of the stream (streamside vegetation)? 
3.	What is the forage and building material value (0-4) within 100 meters of the stream (maximum harvest distance)?
4.	Is it likely that beaver could physically build a dam during low-flow?
5.	Is it likely that a beaver dam on the stream segment could persist once built?

On the human-beaver conflict potential side of things we also discussed that the app should allow users to add location data (“drop a point”) in areas of known beaver conflict and in areas where there is infrastructure constraints. 

We also talked about how the app could help make determinations regarding the NHD stream network misalignment and when it is worth making modifications to the NHD Network based on if the misalignment actually affect dam building material preferences or slope calculations (i.e., if the stream is offset but within that offsite the vegetation class does not change nor do the elevation values significantly change it is not worth re-digitizing the stream segment. 

Joe, thought that it would be useful to have a BRAT calculator that would allow the user to run a simple inference system and get a capacity output “in the field.”

@webernick79 I hope this is useful information.  We also talked about trying to have a catch up call tomorrow late afternoon with @bangen, @joewheaton and you and I.  Are you available?

**Comment by webernick79** [comment]
This is good feedback. I'm available tomorrow, just let me know the time.

**Comment by bangen** [comment]
Wally and I have a meeting from 10 to 11 am PST tomorrow morning.  I'm available after that.

**Comment by wally-mac** [comment]
Joe and I have a meeting that will probably last until 2:30 MST so how about 3:00 MST?

**Comment by wally-mac** [comment]
@webernick79 I ask Kristen Wilson (our TNC contact) for locations data and where we should test the app and she provided a kmz file (below as a zipfile). She identified 250-600 m reaches of stream that are within walking distance of the field station where we are staying. She put notes in the location names to indicate why these reaches might work well.  
[BRAT model validation locations Sagehen.zip](https://github.com/Riverscapes/pyBRAT/files/1993488/BRAT.model.validation.locations.Sagehen.zip)

I think the task for @bangen to use this kmz to select stream segments (and the associated 30 and 100 m buffers) from the BRAT output and provide them to @webernick79 so he can produce the sample dataset for the workshop.  Note: Joe and I discussed earlier today that the 30 and 100 meter buffers are the polygons that the user will interact with.

**Comment by webernick79** [comment]
This seems very doable.

**Comment by wally-mac** [comment]
@joewheaton and I talked today (5/10/18) and Joe stated that for the TNC BRAT project TNC staff, forest service personnel and citizen scientists will only be responsible for **data capture** and this data capture can occur as **field, desktop or a combination between field and desktop** interpretations. We (the ETAL lab) is responsible for model **calibration, verification and validation** based on the data that they provide us.

**Comment by joewheaton** [comment]
This conversation has run its course....
