### ISSUE TITLE
TNC BRAT - Final Runs

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#290]
@wally-mac @mhallerud 

I made the final changes to the conservation restoration model based on Kristen's feedback.  We're ready to roll out the rest of the model for the project!

A few things:

**Folder Run Name**
- Pretty sure we used 'BatchRun_02' for the folder run name for all basins.  Maggie, can you please verify this is the case?  Wally, are you fine with that name?  If not, we could try and batch rename the directory, but I'm not sure if that would mess anything up with the xml.

**Landfire**
- I noticed issue #183 is still open.  Maggie, please double check this still isn't an issue.

**Reach Slope Symbology**
- Wally and I made some changes to the ReachSlope symbology layer file (see screenshot at the end of this post).  This was after the batch runs of all the basins.  Maggie, you'll need to batch delete the 'ReachSlope.lyr' files in the 'Outputs\Output_01\01_Intermediates\02_TopographicMetrics' folder so they are recreated in the layer package generator script.

**Combined FIS Runs**
- Maggie, if I remember correctly you'd run all the basins up through the capacity models, correct?  We decided to revert back to the default slope membership functions and you had planned to re-run all the basins through the combined FIS code.  Did that happen?  If not, please do so.

**Conservation Model**
- I pushed the changes to the TNC_Changes branch.  Note, this includes changes to the symbology layer file, so make sure you pull the latest changes from Git before running.

**Layer Package Clipping**
- Is this working properly now?
- Wally, should the network be clipped to just the perennial or the perennial + canals?

I think this covers most of the potential issues, hiccups.  @mhallerud and @wally-mac is there anything else you can think of?  

![Capture](https://user-images.githubusercontent.com/6502954/59374301-67a69e80-8d00-11e9-89ad-8a56e9bfc0fe.PNG)

**Comment by mhallerud** [comment]
@bangen @wally-mac I can get this going early tomorrow mornings; I think the changes will be pretty quick and then layer package will take a bit longer but I should have them done by the end of the week! Addressing the above:

- **Folder Run Name:** Folder names are all BatchRun_02 for this run. Let me know if you want them changed at all. 

- **LANDFIRE Issue:** I was completely unaware of #183 but will take a look at those basins. I did not notice any issues in running them.

- **Reach Slope Symbology:** Sounds good, those will be easy enough to delete and I might just re-create them via batch running the make_layer function to avoid layer package issues.

- **Combined FIS:** I double checked and everything was re-run shortly after that change was made.

- **Conservation Restoration Model:** Done.

- **Layer Package Clipping:** The clipping is working properly now in the standalone layer package generator. It's a little buggy and tends to crash Arc every 10-12 watersheds, but beats doing it manually. I talked to @wally-mac and we'll be clipping to the perennial plus canals/ditches.

- **Other Fixes:** Looking at Idaho results, there's a few small symbology changes that I'll make (renaming risk categories and changing colors in the unsuitable/limited opportunities layer). For the validation watersheds, do we want to run the Idaho version of the validation tool with those new outputs? See [American Falls layer package](https://usu.box.com/s/oj6u2ll4g448k9pg4cv7e031tg2xzr8j) for example.
