### ISSUE TITLE
BRAT Map update

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#298]
Hey guys,
Thanks for updates to: http://brat.riverscapes.xyz/BRATData/ map.

Chris pointed out (asked) what about the stuff we ran for WFF and SGI workshops in:

- Nevada (Humboldt)
- New Mexico (not us)
- California Salinas (not us)
- Arizona (for WFF we ran two right)
- Colorado (for WFF)?

Wally, do you remember these?

Cheers,
joe

**Comment by wally-mac** [comment]
@joewheaton yes BRAT was run for the Humboldt, NV by @sshahverdian . As far as I know, we did not run BRAT in Arizona or Colorado for WFF . For WFF we run R-CAT. We can add the Humboldt to the map if Scott thinks his run is complete.  Scott what do you remember about this?

**Comment by sshahverdian** [comment]
Not a whole lot. I recall there were some interesting problems regarding the HUC delineation (did not include a large area that should have been included in the drainage area and produced artificially low drainage areas); that regression equations were hard to come by and so I think I hard-coded some values for baseflows; and that this run was well before the BRAT runs were producing a lot of the intermediate outputs that they are currently producing. I can try to track down some notes from back then, if that would help, but if we want it to stand alongside current outputs, then I imagine it'd be worth re-running.
