### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#3]
Hey @philipbaileynar  or @MattReimer . An annoying one for you.  I've tried all sorts of tricks to get the  [`favicon.ico`](https://github.com/Riverscapes/BRAT/blob/master/docs/favicon.ico) to properly display. These were semi-useful:
- https://stackoverflow.com/questions/30551501/unable-to-set-favicon-using-jekyll-and-github-pages
- https://stackoverflow.com/questions/35037482/favicon-with-github-pages

But ultimately, none of them worked. Any suggestions? I haven't tried saving it as a png instead and changing from the: `<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">` syntax to the `<link rel="shortcut icon" type="image/png" href="favicon.png">`. I tried it on a few sites... no luck. I'm not sure if putting this html in the `index.md` is the best thing. Someone mentioned to put it in the `[head]` part of the document. Not sure what that is with md?

**Comment by philipbaileynar** [comment]
@joewheaton, stare into my eyes and repeat after me... "conteeeeeeeeeeent".... "cooooooooonteeeeeeent".

We can figure this out later. Might be possible with page layouts. This is such a lower priority than coordinating the content of 20 or so sites to get migrated over.

**Comment by joewheaton** [comment]
@philipbaileynar, I'm staring in your eyes ;), and I'm not seeing an answer? I thought you geeky types liked annoying things like this. Don't worry... we've got an army gearing up to work on content. As I work through pushing things over and getting things set up for folks here to, there are lots of stupid little things like this I come across. I obviously don't need an answer now on this stuff (later is fine), but I do want to queue them up so we make sure everything is there and ready to go. If I don't post these questions as I discover them, I won't remember. Plus, I want to make sure the army we're going to unleash on content gets in the habit of using these issue boards to post problems and concerns as they come across them. We can always flag them as a low priority.

**Comment by joewheaton** [comment]
Okay... turns out that the: `<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">` being placed in the `index.md` file does the trick. I used [http://www.favicon-generator.org/](http://www.favicon-generator.org/) to generate my icons or downloaded existing one from my Google Sites. The trick is to be patient. This just takes a little while (few hours) for it to show up.

**Comment by MattReimer** [comment]
Ok, @joewheaton don't put link tags into the `index.md`. The proper way to do favicons is as follows:

1. Find a nice sized copy of your logo that is square.
2. Go to a service like http://www.favicon-generator.org/ and upload it. It will give you the following files in a zip: `android-icon-144x144.png`, `apple-icon-114x114.png`, `apple-icon-60x60.png`, `favicon-16x16.png`, `ms-icon-150x150.png`, `android-icon-192x192.png`, `apple-icon-120x120.png`, `apple-icon-72x72.png`, `favicon-32x32.png`, `ms-icon-310x310.png`, `android-icon-36x36.png`, `apple-icon-144x144.png`, `apple-icon-76x76.png`, `favicon-96x96.png`, `ms-icon-70x70.png`, `android-icon-48x48.png`, `apple-icon-152x152.png`, `apple-icon-precomposed.png`, `favicon.ico`, `android-icon-72x72.png`, `apple-icon-180x180.png`, `apple-icon.png`, `manifest.json`, `android-icon-96x96.png`, `apple-icon-57x57.png`, `browserconfig.xml`, `ms-icon-144x144.png`
3. put these files in the folder `assets/images/favicons`

Now you're ready to link them up. Open `src/_layouts/default.html` and add the following lines:

```html
      <link rel="apple-touch-icon" sizes="57x57" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-57x57.png">
      <link rel="apple-touch-icon" sizes="60x60" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-60x60.png">
      <link rel="apple-touch-icon" sizes="72x72" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-72x72.png">
      <link rel="apple-touch-icon" sizes="76x76" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-76x76.png">
      <link rel="apple-touch-icon" sizes="114x114" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-114x114.png">
      <link rel="apple-touch-icon" sizes="120x120" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-120x120.png">
      <link rel="apple-touch-icon" sizes="144x144" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-144x144.png">
      <link rel="apple-touch-icon" sizes="152x152" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-152x152.png">
      <link rel="apple-touch-icon" sizes="180x180" href="{{ site.baseurl }}/assets/images/favicons/apple-icon-180x180.png">
      <link rel="icon" type="image/png" sizes="192x192"  href="{{ site.baseurl }}/assets/images/favicons/android-icon-192x192.png">
      <link rel="icon" type="image/png" sizes="32x32" href="{{ site.baseurl }}/assets/images/favicons/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="96x96" href="{{ site.baseurl }}/assets/images/favicons/favicon-96x96.png">
      <link rel="icon" type="image/png" sizes="16x16" href="{{ site.baseurl }}/assets/images/favicons/favicon-16x16.png">
      <link rel="manifest" href="{{ site.baseurl }}/assets/images/favicons/manifest.json">
      <meta name="msapplication-TileColor" content="#ffffff">
      <meta name="msapplication-TileImage" content="{{ site.baseurl }}/assets/images/favicons/ms-icon-144x144.png">
      <meta name="theme-color" content="#ffffff">

```

be really careful about the paths here. Too many broken links and it starts to affect your google ranking.
