### ISSUE TITLE
Landfire VEG_CODE and CODE Key

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#30]
The following is an excel sheet that describes the VEG_CODE and CODE used for different Landfire codes. Let me know what you think. Specifically if the developed needs to be lowered. I was on the premise that even though it was developed that like you said beavers are not discriminatory of who owns the land but that the CODE would take care of the conflicts that would arise from land ownership and agriculture. https://usu.box.com/s/jsm3nmwckr74rmklb4f7heh10hnvtouz
@wally-mac @bangen @joewheaton @banderson1618

**Comment by wally-mac** [comment]
@MatthewMeier here is my feedback as a short video: https://youtu.be/1_CWyZZrX-I in brief I suggest that we need one master veg code spreadsheet with consistent and agreed upon coding and specifically we need to get on the same page regarding developed classes and the classes that Josh adjusted. Thoughts @bangen ?

**Comment by wally-mac** [comment]
Here is the document that Josh used to help him make some of the Veg Code adjustments: 
[LF-GAPMapUnitDescriptions.pdf](https://github.com/Riverscapes/pyBRAT/files/1993319/LF-GAPMapUnitDescriptions.pdf)

**Comment by bangen** [comment]
@MatthewMeier  Based on Wally's feedback moving forward we should classify the developed vegetated classes as:

- Developed, Deciduous: 2
- Developed, Conifer: 1
- Developed, Herbaceous: 0

@wally-mac I agree that it would be good to put together a 'master list' of landfire veg classes and suitability codes.  This can easily be transferred into a data dictionary that lives in a supporting tools script.

**Comment by wally-mac** [comment]
Yes, I agree.  Well stated!
