### ISSUE TITLE
Flow accumulation layer not accounting for upstream contributing area outside of HUC8

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#301]
From @sshahverdian and moved here from: [RAVE](https://github.com/Riverscapes/RaveAddIn/issues/17): 
> The Problem
Data set: MiddleBear (ID) HUC8 16010202 RSContext. The flow accumulation layer does not account for upstream contributing area outside of the HUC8 boundary. The result is that portions of the mainstem Bear river which should have a very large contributing area are identified as having very small contributing areas. It appears that in order to accurately capture the flow accumulation values, other HUC8s would need to be integrated for this specific output.

**Comment by philipbaileynar** [comment]
@sshahverdian are you trying to display the catchment area cartographically or simply calculate total drainage area for each reach?

Note that the riverscapes context project uses NHDPlusHR which comes with total drainage area pre-calculated. See the TotDASqKm field in the NHD flow lines ShapeFile.
