### ISSUE TITLE
Can't link to Attribute Table LookUp

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#305]
@Cashe93  wrote:

> Is there an updated website for BRAT documentation? I can't seem to access the links from the '[Understanding BRAT Outputs](http://brat.riverscapes.xyz/Documentation/Outputs/)' page. I'm specifically trying to reference the attribute table lookup. I've been able to access it in the past, but for some reason, it's saying the URLs don't exist. Any info would be great, Thanks!

**Comment by joewheaton** [comment]
The Attribute table is [here ](http://brat.riverscapes.xyz/Documentation/Outputs/Glossary.html)(http://brat.riverscapes.xyz/Documentation/Outputs/Glossary.html), that static link on the [page](https://github.com/Riverscapes/pyBRAT/blob/master/docs/Documentation/Outputs/index.md) is just broken.

**Comment by joewheaton** [comment]
Links now updated.

**Comment by joewheaton** [comment]
@Cashe93, please see [this video](https://youtu.be/nn6TP7CZK1M) for how to fix:

[![https://youtu.be/nn6TP7CZK1M](http://img.youtube.com/vi/nn6TP7CZK1M/0.jpg)](https://youtu.be/nn6TP7CZK1M)

**Comment by Cashe93** [comment]
Awesome thanks, @joewheaton!
