### ISSUE TITLE
sqlBRAT links dead

### ISSUE THREAD

**Issue by NewGraphEnvironment** [Riverscapes/pyBRAT#311]
Hi there. Wonderful work. Thank you so much! 

Keen to test climbing into the nuts and bolts of these analysis for western Canada and wondering about how an old hack might access and contribute to sqlBRAT.  It appears as though all the links to  `sqlBRAT` are currently broken in this repos readme. I was able to find some lovely documentation at [tools.Riverscapes.Net/brat](tools.Riverscapes.Net/brat) however it appears to be referencing python code only? Links in said [documentation](http://tools.riverscapes.net/brat/Support/Advanced_Users/architecture.html) for “international users” also appear to broken along with the https://github.com/Riverscapes/sqlBRAT link. 

Maybe it is a currently a private repo?Any chance you might be able to direct me to the SQL version is currently being developed?

Any specific reason it is not here on GitHub? 

Again - all this work is next level and you all should be proud!

Thank you!!!

**Comment by jtgilbert** [comment]
@NewGraphEnvironment Thanks for reaching out. The current version of sqlBRAT can be found here:
https://github.com/Riverscapes/riverscapes-tools/tree/master/packages/brat

We package all of our production grade riverscape tools in this riverscapes-tools repository. 
The documentation process is ongoing, glad you found what we have so far. We run sqlBRAT on the cloud using nationally available datasets for the CONUS. Configuring it to work in other areas with other datasets is possible, but challenging and will need extensive documentation.

**Comment by NewGraphEnvironment** [comment]
Wonderful. Thank you!
