### ISSUE TITLE
Error creating zonalstatistics

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#33]
I am getting an error message when trying to run the ipc part of the BRAT tool. I have supplied the project files to Sara and Braden for investigation. Here is an image of the error.
![image](https://user-images.githubusercontent.com/30604787/39900118-e89d95e2-547c-11e8-9351-5acb55c712c9.png)
@wally-mac @bangen @joewheaton @banderson1618

**Comment by wally-mac** [comment]
@MatthewMeier where are you working (what watershed) what version of ArcGIS are you running.  @banderson1618 is working on the virtual machines so we can eliminate version errors.

**Comment by banderson1618** [comment]
From the email chain, it looks like this was ArcGIS being unstable, not a problem with the tool specifically. I'm closing the issue for now, unless someone believes differently.
