### ISSUE TITLE
Running BRAT with Amazon S3 Bucket

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#34]
@joewheaton  and I talked about having @banderson1618 connecting with @philipbaileynar and @MattReimer to learn how towork with Amazon S3 buckets to run BRAT for entire states at the HUC 8 level. The rational is utilize many machines and just crank through it. This would need to be coordinated with @bangen

**Comment by joewheaton** [comment]
Yes... @banderson1618, just to clarify, please:
1. First, move our VM Server Box to lab and learn how to set it up with help from Wes.
2. Make images ISO of Windows10 64 bit machines, w/ 8 GB of RAM and different versions of ArcGIS: 10.0, 10.1, 10.2, 10.3, 10.4, 10.5, 10.6.
3.  Write documentation on internal FHC help pages for analysts to use these VMs to run specific versions of tools that have a version specific ArcPy depencies.
4.  After that... then bug @MattReimer to:
  - Get AWS access to my USU accounts
  - Setup an S3 Bucket (and instructions and documentation) for how folks in lab can upload data to this (similar folder structure to on Box) and then point to it to run their simulations, and save their outputs to, and download back to Box.
  - Setup EC2 with same or equivalent ISOs to above and make sure all our Riverscapes Models are loaded on them.
 -  Figure out how to queue up jobs.

@MattReimer will have lots to clarify and add here, but lets do the 1-3 stuff first to cut your teeth so we're not wasting Matt's time. Also, @MattReimer, if you have any specific suggestions for what we should read up on now or research, please point us in right direction or share. Thanks all!

**Comment by MattReimer** [comment]
Well, I have limited experience with VM Server Box so I'm not going to be that much help there. I have no idea how you would queue up jobs that way. 

On CHaMP we used [AWS SQS queuing](https://aws.amazon.com/sqs/) with the job work being done by [AWS Lambda](https://aws.amazon.com/lambda) and the "WORK" work using [ECS spot-priced](https://aws.amazon.com/ecs/) with [auto-scaling instances](https://aws.amazon.com/autoscaling/)

All the code for all of that is totally open source and [available here](https://github.com/Riverscapes/CHaMPAutomation) but it's probably overkill for what you need. If you can figure out how to run jobs on VM Server you can probably just end each job with an upload step to S3 (which is insanely easy) and you're good to go.

**Comment by banderson1618** [comment]
Thanks for the input, @MattReimer. I think the plan right now is to move the server to the lab and work on setting it up on Monday, so any questions will probably wait until then.

**Comment by wally-mac** [comment]
@banderson1618 can this be closed or are you waiting on information?

**Comment by banderson1618** [comment]
I'm not waiting on information, I just haven't had time to look into this recently.
