### ISSUE TITLE
BRAT Manuscript Ideas

### ISSUE THREAD

**Issue by wally-mac** [Riverscapes/pyBRAT#36]
@joewheaton and I discussed the need to outline the manuscripts that could come from our various BRAT work.  @bangen and @joewheaton lets get your ideals here. 

- Case studies: highlight all the various work we are doing (compare and contrast)
- Ground Verified outputs vs. Non verified and what gains you get with additional data capture
- Conflict and Management Model
- BRAT  Castor comparison?  

Have Elijah and Kristen as a co-authors

**Comment by joewheaton** [comment]
I like this @wally-mac. Lets get together and flushout the funded Projects, labels and milestones, and then we can break these out into outlines and manuscripts.

**Comment by bangen** [comment]
@wally-mac @joewheaton IMO we should take an evening at the upcoming TNC BRAT meeting to whiteboard manuscripts in person

**Comment by joewheaton** [comment]
For each of the projects we have at least one manuscript (Idaho BRAT/ GYA BRAT/ TNC BRAT/ John Day BRAT). I think the key is to keep each contribution tight and focused on the major methodological, management or scientific advance in those respective projects. 

My thoughts on:

> Case studies: highlight all the various work we are doing (compare and contrast)

I like this maybe for TNC BRAT, but lets not get too carried away. 1-4 could be compelling. 

> Ground Verified outputs vs. Non verified and what gains you get with additional data capture

Kind of methodological... I can see something that uses these new data capture methods and tells a story about performance of BRAT across hugely different physiographic settings...


> Conflict and Management Model
This seems really important.... not sure which project this ties to. 

> BRAT Castor comparison?
Not interested... without funding specifically for this. Not worthy of a paper.

**Comment by wally-mac** [comment]
@joewheaton thanks for flushing some of these ideas out. I think this is a good start. The next step would be flushing out some outlines. This has been effective in the past.

**Comment by joewheaton** [comment]
Closing as no current plans.
