### ISSUE TITLE
pyBRAT could use a development branch

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#39]
We've been talking creating a development branch for pyBRAT for at least a month now, so it seems fair to make it an issue. I propose that @bangen should be the one who makes the branch, primarily because she would be the main person using it, but also so that she can gain experience and familiarity with using branches. I'm willing to do it myself, but I believe that the experience would be better for @bangen than for me.

In case you need a refresher on how branching works, here's a link to the [Branch Demo](https://www.youtube.com/watch?v=esA187QDO_s) I made back in March. There's plenty of other resources online about branching, which can be useful if you get stuck.

@wally-mac and @joewheaton, should we finally pull the trigger on this? Feedback is appreciated.

**Comment by wally-mac** [comment]
I think this is a great idea.

**Comment by bangen** [comment]
I'll get this set-up post TNC BRAT workshop.
