### ISSUE TITLE
New field for summary report idea

### ISSUE THREAD

**Issue by MatthewMeier** [Riverscapes/pyBRAT#44]
Hi Wally and Joe,

Further investigation of the dam points for the rock creek area is given below in a [Layer Package](https://usu.box.com/s/qq4vk60mpelwh71skxs3xyde5p3c0t1m) to better illustrate the under predictions of the BRAT model in this area. Here are some statistics

Of the total _34_ stream segments with validation dam counts only _28_ exceeded the capacity estimates indicating that the model effectively segregates the factors controlling beaver dam occurrence and density _82_% of the time.  (Total segments in the network is ~8351)  

The following are some more statistics when I dived into the reasons why these under predictions occurred.

![image](https://user-images.githubusercontent.com/30604787/40027783-deac0acc-5798-11e8-90d6-5627e90f5874.png)

The following layer package describes this further and more information can be found there. From examining it I found that the landfire that the under predicted reaches occur on are primarily sagebrush and agricultural land with "VEG_CODE" values of 2 and 1 respectively. There is also one that has a dirt road going over it which is throwing it into conflict. After speaking with Joe today the origin of the dam census according to duration and precise year/s collected is unknown.
Another idea is to base the distinction of the calibration and quality of the model based on censused dam counts
I hope this provides some information and look forward to hearing from you all on your input.
@wally-mac @bangen @joewheaton @banderson1618

**Comment by wally-mac** [comment]
@MatthewMeier , looking at your graph of the preliminary run I see that of the total 34 stream segments with validation dam counts 28 exceeded the capacity estimates indicating that the model only segregated the factors controlling beaver dam occurrence and density 18% of the time. Showing that this preliminary run is grossly underestimating capacity if in fact the dam census data that we used is an accurate assessment of 2014 conditions (the year of the LANDFIRE data). I think Scott and Joe's site visit will help calibrate the model and future runs will have improved predictions of beaver dam capacity in this area.

**Comment by MatthewMeier** [comment]
Looking further into the issue it was found that while the year was not clarified by the metadata contained in the following excel file the activity of the dam was. Out of the points that contributed to the 34 validation reaches narrowed it down to 17 instead. And from 112 dam points to 36 active dams, 64 inactive dams, and 12 were just lodge locations. ALWAYS LOOK INTO THE DATA AND METADATA
The new statistics for the rock creek area of Big Wood is now as follows…
Of the total 17 stream segments with validation dam counts 9 exceeded the capacity estimates indicating that the model only segregated the factors controlling beaver dam occurrence and density 47% of the time.
I think that in looking at the underprediction or over prediction of the model it would be helpful to add the following fields to the BRAT Summary Report script…
•	Census Dam Count/km defined by category- Product of oCC_EX and Segment Length [dams/km] 
Cs_Categor: =IF(e_DamDens=0,"None",IF(AND(e_DamDens >0, e_DamDens <=1),"Rare",IF(AND(e_DamDens >1, e_DamDens <=5),"Occasional",IF(AND(e_DamDens >5, e_DamDens <=15),"Frequent",IF(AND(e_DamDens >15, e_DamDens <=40),"Pervasive")))))   (text)
•	Existing dam count to Dam census count Ratio - Ratio of model expected count to dam census counts [dams]
EXvsDamCt: = [mCC_EX_Ct] - [e_DamCt] (double, precision = 0, Scale = 0) 
•	Existing dam/km to Dam census density Ratio - Ratio of model expected dams/km to dam census density [dams/km]
EXvsDamDen: = [oCC_EX] - [e_DamDens] (double, precision = 0, Scale = 0) 
•	***Existing dam/km to Dam census density Ratio for number of classification discrepancy - Ratio of model expected dams/km to dam census density [dams/km]
EXvsDDdis: = Comparing the Cs_Categor and Ex_Categor fields to compare the difference in classifications. If the difference between the model and censused dams/km is still within the same category (“None, Rare, Occasional, Frequent, or Pervasive”) this would not be as big of a deal. However, if you are jumping classifications that would be good to know and quantify… Ideas are welcome @wally-mac @bangen @joewheaton @banderson1618

**Comment by MatthewMeier** [comment]
![image](https://user-images.githubusercontent.com/30604787/40079099-f7d2c512-5843-11e8-9e27-abbae5d2d751.png)

**Comment by wally-mac** [comment]
Thanks @MatthewMeier. This looks much better to me. @bangen @banderson1618 @joewheaton what do you all think of this improvement?
