### ISSUE TITLE
Survey123 App for 'Beaver Dam Complex - Basic'

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#52]
This is probably going to be the most used and popular beaver dam monitoring form:
https://usu.app.box.com/file/292685180394

**Comment by joewheaton** [comment]
@webernick79 are you planning or able to get this one done for @wally-mac by Monday? If not, they can use the #32 for single dams... but this would be super useful.

**Comment by webernick79** [comment]
@joewheaton , yes, I will kick this out Sunday morning. Won't take a minute.

**Comment by webernick79** [comment]
Shit, I made the advanced form: anyway, here that is anyway:

https://survey123.arcgis.com/share/1253dc28982f418d8cfc62b445066efb?open=menu


I can also kick out the Basic version of the form

**Comment by webernick79** [comment]
OK, Good to go, here is the Dam Complex - Basic Survey

https://survey123.arcgis.com/share/8c8660b01b234e639691aed53a9278ce?open=menu
