### ISSUE TITLE
For Willow Fly Catcher Sampling get UC Davis Meadow Layer

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#56]
Clip the BRAT analysis down to UC Davis Meadow Layer and get the to produce layers. Start looking at BRAT and maybe get refined outputs for just meadows to partners.

Existing dam density - Need to produce layers for analysis on data capture events. Get dam observations...

**Comment by joewheaton** [comment]
It looks like this meadows layer is available [here](https://meadows.ucdavis.edu/meadows/map). It doesn't look like that inclues the Hydo-Geomorphic Meadows classification of [Wiexelmann etal](https://meadows.ucdavis.edu/resources/18026). We need to work with Tina Mark (USFS) and get this layer.

**Comment by joewheaton** [comment]
Just an update from Tina Mark:

> Joe, the revision of the UC Davis Meadow layer is a work in progress, and as such hasn’t been uploaded to the UC Davis site yet.  The Sierra NF meadows are still being updated, but I can provide the interim meadow layer product with the HGM types by the end of the week (Dave is attending the Sierra Partners meadow meeting this week).   The link below is a pdf of the Meadow HGM field guide.  I’ll send a few hard copies your way also.   Best, Tina

>   | Tina Mark Forest Biologist - Wildlife, Aquatics, and Rare Plant Program ManagerForest ServiceTahoe National Forest, Supervisor's Officep: 530-478-6240 f: 530-478-6109 tmark@fs.fed.us

So end of the week @bangen

**Comment by bangen** [comment]
I still need to run the intersect analysis, but the meadows dataset is up on Box [here](https://usu.box.com/s/h2zxbhplxvn1t4nedg0om3imfi05iz4v).

**Comment by wally-mac** [comment]
@bangen, has the intersect analysis been done? If you need help you could ask a tech to help you.  Thanks!

**Comment by bangen** [comment]
@wally-mac from my understanding this was something Point Blue was interested in for their field planning efforts and Brent already completed.  Coming out of the meeting we were also interested in seeing the capacity predictions in meadows vs non-meadows.  IMO, this isn't a high priority and given we're making some model adjustments I think we should hold off for now until we have our final model output.  Thoughts?

**Comment by wally-mac** [comment]
@bangen, I agree let's hold off.
