### ISSUE TITLE
TNC Sagehen Workshop

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#59]
We need to invite the participants from the Sagehen workshop to GitHub that expressed interest in:
- Participating in development
- Participating in Data Capture (both BRAT & Beaver Dams)

As a reminder here are the participants:
![image002](https://user-images.githubusercontent.com/9723905/40580187-f1a963ce-60f6-11e8-8fbe-1d434c844761.png)

**Comment by wally-mac** [comment]
@joewheaton, do you want to take this task on? I think it would be great coming from you. I think folks could see how much work we have done since May. Thanks
