### ISSUE TITLE
Add Streamflow direction output layer for checking

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#61]
While in the field, @bangen noticed that the preliminary BRAT output (#54) was producing a bad over-prediction (by suggesting a flat slope of 0) in a reach that had a waterfall (i.e. [Eagle Falls](https://goo.gl/maps/ewTAih2HxHS2)). @bangen dug into this and found out that it was because the NHD  network had the flow direction wrong and reversed for that segment (i.e. flowing upstream) and the BRAT slope calculation algorithm's thing of fixing 'negative' slopes by making the reach flat (i.e. 0.00001) was failing here. 

@banderson1618 should update his Layer Package algorithm and the BRAT project so that a layer that symbolizes the network with arrows for flow direction is added to layer package output. This allows for visual identification of potential problems.

**Comment by banderson1618** [comment]
I've never worked with a flow direction symbology. I can probably figure it out eventually, but it'd be helpful if either @joewheaton or @bangen gave me a base layer package. If I can get that, it should be trivial to add.

**Comment by bangen** [comment]
@banderson1618 I just added the flow direction symbology layer file to the 'BRATSymbology' folder (commit 90ed8c1)

**Comment by joewheaton** [comment]
Can either @banderson1618 or @bangen please add a help documentation page on this and example cartographic output?

**Comment by banderson1618** [comment]
@joewheaton, where do you want the documentation to go? The layer is made in the BRAT Table tool, and put in the layer package in the layer package generator, so it could go in the documentation for either
