### ISSUE TITLE
Add error checking for streamflow direction...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#62]
Related to #61, @bangen wants to tweak the code so that we anticipate and correct for streamflow directions in the network that are going the wrong way.

@bangen should update the code to look for this problem and change the logic.

**Comment by bangen** [comment]
There was no real sure fire way I came up with to write this check into the code.  In the end, we just ended up adding the network flow direction to the layer package file.  So it's up to users to ensure flow is in the correct direction.
