### ISSUE TITLE
Should we calculate iVeg for River Right & River Left separately?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#64]
So right now we use the 30 m and 100 m buffers and calculate the average for all the `iVeg` (e.g. `iVeg_VT30_ex` and `iVeg_VT100_ex`) from the classified veg raster.  It is very common that the river left and river right are very different.  We could rather easily add a `iVeg_VT30_ex_RR` for river right and `iVeg_VT30_ex_RL` for river left and then calculate the values for each, and then take the average of both to calculate `iVeg_VT30_ex` . The advantage to this is we could produce a network output for river right and left separately, which might be helpful for design as well as pinpointing potential conflicts. The downside is it adds four new fields to the table and a bunch more intermediate layers.  Thoughts?

Not a high priority....

**Comment by joewheaton** [comment]
@bangen or @banderson1618 could you 'scope' this in the pyBRAT Development for how much time you think this would take. Also comment on whether you think it is a waste or necessary.

**Comment by banderson1618** [comment]
ArcGIS doesn't have a great way to automate splitting a polygon by a polyline, to my knowledge. The closest that it has is the [Feature to Polygon](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/feature-to-polygon.htm) tool, but I think that the overlapping buffers would create a new polygon where they overlap at the end of each line. Obviously, that isn't what we want for the tool. There's probably some workaround that's possible, but, given that I don't have a clear gameplan on how to implement this, it's pretty hard to scope. I'll keep this problem in mind, and post if I have any further ideas. @bangen, it would be great if you knew of a good way to do this that I'm not thinking of.

**Comment by joewheaton** [comment]
Agreed @bangen. This is a good idea if asked for. Lets shelve it.
