### ISSUE TITLE
Add to Data Capture Apps a 'Reach Position' attribute

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#67]
For 'Advanced' Survey123 Apps, ... we realized in the field that we were constantly taking measurements from the side of a road, or a bridge (#66 ) . This brought up the issue that when getting a point, what reach were we looking at.  Can we please add to the Advanced forms a simple 'Position of Reach (relative to survey point)' field with the following options:
- Within Reach
- Upstream of Point
- Downstream of Point
Those last two are really helpful in a subsequent post-processing ingestion into the pyBRAT project command for snapping to the 'right' reach segment on drainage network.

**Comment by joewheaton** [comment]
@chadFHC can you incorporate this into Survey123 apps?

**Comment by chadFHC** [comment]
@joewheaton 
I believe I would be able to. These "Data Capture" apps are completely new to me. I have been working on the beaver dam censusing apps, so I'm sure I would be able to. I guess I just need access to the survey. I think @wally-mac showed me the survey once from his phone, but I've never seen it other than that. 
Do you know where I would be able to find the survey to edit?

**Comment by wally-mac** [comment]
@chadFHC If you want to be able to find the surveys to edit please get them from @webernick79

**Comment by chadFHC** [comment]
@wally-mac 
I'll try to work with @webernick79 as soon as possible to get this done.

**Comment by joewheaton** [comment]
Superseded with QRiS.
