### ISSUE TITLE
Re-Thinking Labels and Symbology

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#68]
In the Sagehen Workshop #59, we discussed some sensitivities to some of the naming and labels and symbology. For example, Kate Lundquist was not a fan of the 'Conflict Potential' name. Rodd Kelsey (TNC) has a bunch of experience in packaging these types of outputs and workiing on the naming semantics and cartography. @wally-mac and I will work with him on this.

In meantime, @bangen can you please go through entire pyBRAT project and flag up ideas, questions and suggestions for making naming convention more consistent and flexible. One way we can do this easily in a Riverscapes project is:
- Dumb down names we give to things on disc (e.g. instead of `10m_USGS_NED.tif` we just store this as a DEM realization of `DEM_001.tif` 
- and then add a `<Label>` tag to project and that's what gets displayed to user and in subsequent graphs, plots, reports, tables, and layer names. 
- we can offer defaults for these names that make sense to us.

**Comment by bangen** [comment]
@banderson1618 here's [some feedback](https://youtu.be/uheFQnzvl18) on the layer package symbology.  Can you please take a stab at the items I point out in the video?

**Comment by wally-mac** [comment]
@Albonicomt please also review.

**Comment by banderson1618** [comment]
@bangen, if we can create a layer that bases symbology off of those RGB values, then we can apply it pretty easily. So far, though, we haven't changed any symbology in the code at all, just applied already existing symbology. You're probably closer to an expert on creating symbologies than I am, so I'll let you decide if you think it's possible.

As to the other stuff, I'll test if having spaces in layer names breaks everything. I wasn't sure, and ArcGIS can be fickle, so I was playing it safe, but it makes sense to test if that's actually the case. I'll make the other changes and push them up by the end of the day.

**Comment by Albonicomt** [comment]
@bangen, I really like the clean-up you did on the LPKs. I wasn't sure what to call some of the layers, but I definitely like what you have changed. 
As far as creating a symbology for the R,G, and B values, I am not too familiar as to what those fields are or mean. I would definitely be happy to look into it and talk about some options about what we can do with them. Unless anyone already knows, I can read up on the LANDFIRE's website to make some sense of the values in those fields to group the values associated with those fields.

**Comment by wally-mac** [comment]
Thanks for making the video Sara.  @Albonicomt, please spend a couple hours digging into the RGB option for coding LANDFIRE and report back to the group.  Thanks!
