### ISSUE TITLE
Re-thinking Conflict as a primary Output

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#69]
In response to #59 and #68, @bangen and @wally-mac and I discussed:
1. Ditching the probability of human-beaver conflict as a primary output
2. Getting rid of probability concept and calculation altogether
3. Burying this information as specific 'Intermediate' outputs
4. Changing 'Conflict' label of folder in inputs to 'Infrastructure' or something like that 
5. Getting rid of idea of a combined 'conflict' score and just showing the specific risks as contextual intermediates. 
6. Producing symbology in terms of 'Distance from Infrastructure' with a legend something like:
   - At (= 0 m)
   - Adjacent (0 -30 m)
   - Near (30 -100 m)
   - In Vicinity (100 -500 m)
   - Far Away (> 500 m)
7. Producing specific layer outputs in project and layer packages with above legends for:
  - Roads
  - Roads in Valley Bottom
  - Railroads
  - Buildings
  - Orchards, Farm Fields or Vineyards
  - Crossings (e.g. culverts, bridges)

Thoughts?

**Comment by bangen** [comment]
@wally-mac @joewheaton I really like this idea.  Just to clarify, you're suggesting getting rid of everything related to the conflict model but still calculating the the distance from the layers listed in point 7 above, correct?  

I think this is a good move considering we're no longer using conflict in the management model, several partners are concerned with the terminology, and it allows us to back away from setting what are pretty sensitive thresholds.  

Joe, are you envisioning the intermediary layers produced as a) euclidean distance rasters or b) network polylines attributed by distance from specific infrastructure (e.g., reach distance from roads shapefile, reach distance from roads in valley bottom shapefile, etc.)

**Comment by bangen** [comment]
In addition to Joe's point 7 above, @wally-mac had good suggestion of also calculating distance from:

- Railroad-Stream Crossings
     - Not limited to valley bottom
- Canal-Stream Crossings (any, even outside the valley bottom)
     - Not limited to valley bottom
     - Note: require removing canals from entire network and then running intersection with canals polylines.  These are most likely points of canal diversion.

**Comment by joewheaton** [comment]
> Just to clarify, you're suggesting getting rid of everything related to the conflict model but still calculating the the distance from the layers listed in point 7 above, correct?
Sort of @bangen. I don't think we want to have an output anymore that draws attention to some amorphous concept of 'probability of human-beaver conflict'. I think we still use this to inform the management model, but we just sort of bury the user in a bunch of intermediate outputs that are much more specific to what our logic actually is and the calculations we make (e.g. show distances, and symbolize outputs by same breaks in our logic) -> see #87 .

> Joe, are you envisioning the intermediary layers produced as a) euclidean distance rasters or b) network polylines attributed by distance from specific infrastructure (e.g., reach distance from roads shapefile, reach distance from roads in valley bottom shapefile, etc.)
I want to see b) on the network (i.e. the distance we use in our logic), not the raster, and the inputs (i.e. the roads). 

> In addition to Joe's point 7 above, @wally-mac had good suggestion of also calculating distance from:
> 
> - Railroad-Stream Crossings
>    - Not limited to valley bottom
> - Canal-Stream Crossings (any, even outside the valley bottom)
>   - Not limited to valley bottom
>   - Note: require removing canals from entire network and then running intersection with canals polylines. These are most likely points of canal diversion.

Good point. I think we should just derive a point-based feature class for all these intersection points. In the case of Canals, they can be points of diversion or points of confluence/return flow. In case of railroads and roads, they can be potential bridges, culverts, or low-water crossings. 

In all cases, we DON'T limit this to valley bottom (see also #87), but we may treat those circumstances differently. 

The overall goal in all of this is to provide some intermediate outputs that really help identify specific potential threats. We might then think about a revised Potential Conflict Assessment that gets back to the concepts we flagged up earlier, but requires this stuff as an input, as well as capacity (higher conflict potential in higher capacity areas), and optionally actual beaver dams and/or beaver activity. I want to focus on identifying what are the possible types of impact (i.e. flooding, clogging, harvest, etc.).

**Comment by wally-mac** [comment]
I think this needs to be put back on the front burner.  When I get back I think @bangen, @joewheaton @sshahverdian, @banderson1618, and I need to meet and come up with a game plan on how to tackle this important enhancement.

**Comment by joewheaton** [comment]
@wally-mac is right. This has been pushed to front burner in #16 again. I'm closing this one and cross referencing 16. Lets make the conversation and changes there.
