### ISSUE TITLE
BRAT Home link

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/pyBRAT#7]
I am trying to create a picture link to the BRAT homepage http://brat.riverscapes.xyz from the 'http://brat.riverscapes.xyz/Documentation/summary' page

Shouldn't this work:
'[![BRAT_Banner_Web]({{ site.baseurl }}/assets/Images/BRAT_Banner_Web.png)]({{ site.baseurl }})'

It is sending me to 'http://brat.riverscapes.xyz/Documentation/summary' instead.

I know I could use 'http://brat.riverscapes.xyz' instead of '{{ site.baseurl }}' but shouldn't that work?

**Comment by joewheaton** [comment]
Interesting. It seems like `[![BRAT_Banner_Web]({{ site.baseurl }}/assets/Images/BRAT_Banner_Web.png)]({{ site.baseurl }})` should take you to the root, but it seems like what its doing is just taking you to the current page. I guess you could just use http://brat.riverscapes.xyz instead, but maybe @MattReimer or @philipbaileynar  can explain what is going on?

PS - Also, note that `  `is different than ' ' (single quotes) if you're trying to have a code snippet...

**Comment by philipbaileynar** [comment]
1. Here's [some explanation on the Jekyll URL components](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/). I suspect that `site.baseurl` requires a page appended. So try `site.url` instead.
1. Also, don't forget that in a pinch you can always use plain old HTML. This is not advisable, but sometimes it just gets you over the hump: `<a href=""><img src=""></a>`

**Comment by lhaycock** [comment]
I tested the link using `{{ site.url }}` instead of `{{ site.baseurl }}` and am getting the same result.  When you say HTML is not advisable would you recommend using `brat.rivercapes.xyz` instead?

**Comment by philipbaileynar** [comment]
Let me do some experimentation myself @lhaycock ... will report back ASAP

**Comment by lhaycock** [comment]
@philipbaileynar It is ok, I just realized I had changed the picture link to the `site.url` instead of the actual link.  It is working now. Sorry for the confusion.
