### ISSUE TITLE
What Dan Presented

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#71]
Dan presented what he saw as some ideas for using beaver as an example of something that could help Google meet its water sustainability and conservation goals through stewardship. While the sustainability goals were more aligned with the Operations side of Google, he was keen in using beaver as a conservation/restoration example that could also dovetail with some of what Google can do on the product development side (especially Geo, GE Engine, and AI). Specifically, he thought that building on successes in their AI algorithms learning the differences between skylights and photovoltaic solar panels, there might be some value in being able to identify small open-water bodies and differentiate those from beaver dams from others (natural pools, stock ponds, small reservoirs, etc.). Even if the algorithm could cut the time it takes a technician to manually identify and inventory or census beaver dams (e.g. #32, #52) data capture events (#31).

**Comment by wally-mac** [comment]
Update: over the past couple of months I have been working with Dan on this (via email).  I have provided him a sample dataset (dam locations for the Big Wood watershed generated my @chadFHC). It is now in Google's court.
