### ISSUE TITLE
Smooth DA Values

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#77]
Due to horizontal alignment issues between the NHD flowlines and NED 10 m DEM, the drainage area (DA) values attributed to each BRAT reach can be erroneous.  This is particularly glaring in instances where the DA value dramatically decreases in the DS direction.

As example of this is shown in the figure below for Steamboat Creek where the flow direction is from bottom left to top right.

![capture](https://user-images.githubusercontent.com/6502954/41064289-010bf722-6990-11e8-8d1f-16e592a2c1e2.PNG)

To resolve this issue we need a workflow that enforces a rule whereby the drainage are for a DS reach on the same river/creek/etc can not be larger that the drainage area of the US reaches.  An example workflow for tackling this is:

- Group polylines by StreamID - *this field is created by dissolving by 'StreamName' ('GNIS_Name' in NHD flowlines)*
- Sort in ascending order by ReachDist - *this field is created by calculating the downstream distance of each reach midpoint along the StreamID*
- Increment through the sorted reaches, checking the DA values.  If the DA value for the ith reach is < the max upstream DA values, assign the ith reach the max upstream DA value
- **Important:** We want to be transparent about the fact that we're updating the DA values.  @wally-mac would like a field that will be a copy of the original DA values.   Unfortunately, we can't use 'iGeo_DA_Orig' due to 10 character limit, so maybe just 'DA_Orig'? The updated DA values should be housed in the 'iGeo_DA' field since this field is called on in the iHyd script.

*Note: We're limited by the NHD flowlines as far as identifying which polylines belong to the same river/creek/etc (effectively our StreamID field).  If a flowline has a name we can easily use this and enforce the above rule.  However, for un-named segments we can't easily automate an approach to determine which polylines belong to which creek.  This means there will still be some instances where the DA values may decrease in the downstream direction between segments.*

@banderson1618 here's a [link to a test dataset](https://usu.box.com/s/r0pz9na0173jyd5eux7n2bn6uf7545d5) for you to use.  And here's [a video](https://youtu.be/eSmumaPa-xI) re-capping some of what we talked about earlier today.

**Comment by banderson1618** [comment]
Quick question, @bangen: should we check the DA values for all the streams, or just for the named ones? I think I remember that being discussed in our GoTo meeting yesterday, but I just wanted to clarify.

**Comment by wally-mac** [comment]
All streams.

**Comment by bangen** [comment]
Just ran this for the Truckee and it appears to be working as intended.  Awesome job @banderson1618 !!

**Comment by banderson1618** [comment]
Great! I'll close the issue, unless someone else objects.
