### ISSUE TITLE
BRAT- cIS (Capacity Inference System) Rule Changes

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#78]
@webernick79 When @wally-mac, @joewheaton and I were out in the field we realized some of the rules weren't behaving as intended.  We did some digging and found that some of the rules were missing from the paper form (and likely the Survey123 app).  We also made some tweaks to the capacity output category for several of the rules in the combined capacity model.  

Long story short, these changes need to be integrated into Survey123.  I shared a Google spreadsheet with you.  The sheet you'll want to reference is 'CombFIS-RulesWithTrumps'.  The rose colored rows are the rules where we need the output capacity category changed.  The new output category is in the 'Capacity Changes' column.  Joe's field form table was cut off at 'pyBRAT Rule #' 52.  Not sure if this is what you were referencing to build the Survey123 logic.  If so, the missing rules will need to be coded in.

Lastly, Wally mentioned that the Survey123 conditional statements for the rules are pretty unwieldy.  Once you've re-coded things feel free to send me the code block to have a second set of eyes on it.

**Comment by wally-mac** [comment]
@webernick79 and @bangen I talked to Joe this morning and he wants/needs the Survey123 Form updated as Sara indicates above ASAP. I think we needs them for the Hailey workshop on June 20th. Also, Sara have you are can you please update the associated paper forms?  Let's make these a priority.  Thanks a ton!

**Comment by webernick79** [comment]
@wally-mac and @bangen , sorry this got away from me, I'm on it today.

n

**Comment by bangen** [comment]
@wally-mac I'll start working on the paper form updates

**Comment by webernick79** [comment]
Hey @bangen  - so it's this sheet, and the CombFIS RulesWithTrumps tab: 

https://docs.google.com/spreadsheets/d/15iImNpazHkgsZblwBck4kcbp72rMHI78UnVmisR3Uzk/edit?ts=5b187582#gid=1527294298

Form and logic should match that correct? and incorporate the updates in column "Capacity Changes"

**Comment by webernick79** [comment]
Hey @bangen and @wally-mac  For your trip to CA, is this map the actual data that needs to be kept and analyzed. Collected using the Advanced BRAT Form:
 http://nick-weber.maps.arcgis.com/home/webmap/viewer.html?webmap=e7e97066319443a19915cb7c913d0820

Was there anything else of importance collected using the other forms?

**Comment by wally-mac** [comment]
YES! All data that was collect on all forms is real and need to be saved.  Thanks for asking!

**Comment by bangen** [comment]
Hey @webernick79 to make things a little clearer I revised the Google spreadsheet I shared so it just has the 2 tabs: 1 for the combinedFIS and one for the vegFIS.  I also added the paper field form number since it's no always the same as what we have in the python code.  Thought this would make it easier for you to make your edits.

**Comment by webernick79** [comment]
Right @bangen I'm just testing out the logic in the survey, I'll send to you to have a look at in a bit.

**Comment by webernick79** [comment]
Hey @wally-mac and @bangen , looks like things are straightened out with the capacity logic. Thanks for the updates Sara.

Here is the [latest BRAT Advanced App for Survey123](https://arcg.is/1nOfm90) Sara, do you wanna give it a look and let me know if things need changing.

Also, here's a download of the [Truckee Validation Data](https://usu.box.com/s/4jqif0fseqjx5tyunuande87v8pic3bn) It would also be good to give this a look let me know if anything about the attributes looks wonky or difficult to analyze

Thanks,

**Comment by webernick79** [comment]
Also, @bangen and @wally-mac is anyone going to be using these forms anytime soon. When people use this data it will be best to create a new instance of the survey so that the data flows into its own layer. Will save us a lot of headache downstream.

**Comment by webernick79** [comment]
@bangen Here are the tables I used to build the logic expressions:

[BRAT_Survey123_Logic_20180714.xlsx](https://github.com/Riverscapes/pyBRAT/files/2103812/BRAT_Survey123_Logic_20180714.xlsx)

**Comment by wally-mac** [comment]
@chadFHC do you know how to "create a new instance of the survey so that the data flows into its own layer" as described by @webernick79.  This something that we'll want to do for the Idaho BRAT data collection that is going to start up this week and additional California data collection in the coming months.

**Comment by chadFHC** [comment]
@webernick79 
Nick, what exactly do you mean by "create a new instance of the survey so that the data flows into its own layer?" Do you mean just make "clones" of the survey so that each survey has its own results?

**Comment by bangen** [comment]
@wally-mac @joewheaton I put together new field forms which can be found on Box [here](https://usu.box.com/s/m4b3fiebyer6gue6wdnjr5ojzp2wpufv).   Joe, with the complete rule table for the combined FIS the tables no longer fit nicely on a single page.  Upside is they are a little more legible.

**Comment by wally-mac** [comment]
Thanks Sara! I'm going to have @kbartelt (Karen) read these over.

**Comment by kbartelt** [comment]
I read these over and everything looked good to me. The forms were easy to understand and use. I did change a small typo.

**Comment by wally-mac** [comment]
Excellent.  These should be ready to be used to update the Survey123 form, @webernick79.

**Comment by bangen** [comment]
@wally-mac brought up the following issue with the cIS Survey123 form:

_Hi Sara and Nick,

The reach slope component of the cIS form needs modification see video: [https://youtu.be/1S2zbsLZzo8](https://youtu.be/1S2zbsLZzo8)

Thanks_

**Comment by bangen** [comment]
@webernick79 what's the status of the cIS Survey123 forms?  Have they been updated to reflect the changes in the rule tables (updated paper forms [here](https://usu.box.com/s/m4b3fiebyer6gue6wdnjr5ojzp2wpufv)) and the slope drop down options?
