### ISSUE TITLE
BRAT Run for Middle Bear Step 6 issue

### ISSUE THREAD

**Issue by Albonicomt** [Riverscapes/pyBRAT#79]
I have been running BRAT for the Middle Bear watershed in Idaho and I keep getting this error message for Step 6 in the BRAT tool: 
![brat_step6_error](https://user-images.githubusercontent.com/39168968/41112951-9da9a464-6a3d-11e8-97a0-1ecb7e4b6020.png)
@bangen @MatthewMeier @banderson1618 , do either of you guys have any suggestions?

**Comment by MatthewMeier** [comment]
Sounds to me like you might be having an issue with the xml not being updated. I would try closing arc and rerunning it again. If that doesn't work something that you can look at is if your inputs for the tool specifically the veg code or code fields do not have correct values in it or if it is missing any.

**Comment by Albonicomt** [comment]
I did try the old trick of closing arc and opening it up again... I will look into the VegCode and Code fields and restart Arc. Thanks @MatthewMeier

**Comment by MatthewMeier** [comment]
This error can be a bit frustrating but some other things that I would try is that step five did not run correctly and so you need to rerun that and then move and and it will work.

**Comment by bangen** [comment]
@Albonicomt I just put up a new release (version 3.0.10) that may fix the issue you're running into.  I've run into the xml error before, but I believe it's at the end of the code after all the major geo-processing.  So, unless the xml is imperative to your deliverables you can ignore it and proceed (i.e., all the key attributes should be populated).

**Comment by Albonicomt** [comment]
Oh right on, thanks a bunch @bangen !

**Comment by wally-mac** [comment]
Can we close this issue?
