### ISSUE TITLE
Changes to Developed Vegetated Landfire VEG_CODE

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#80]
Including this here since it's currently buried in issue #75 

Wally and I chatted about this earlier today and moving forward everyone should be implementing these changes using the **'EVT_GP_N'** field:

**Developed-Upland Deciduous Forest** - VEG_CODE 3
**Developed-Upland Mixed Forest** - VEG_CODE 2
**Developed-Upland Evergreen Forest** - VEG_CODE 2
**Developed-Upland Herbaceous** - VEG_CODE 1
**Developed-Upland Shrubland** - VEG_CODE 1

We also need to be careful about blindly assigning VEG_CODE 2 to everything that has sagebrush in the EVT_GP_N. From observations in the field, beaver will use larger sagebrush to build dams, but not smaller dwarf sagebrush. To capture this any classes with an EVT_GP_N with **Low Sagebrush** (e.g., Low Sagebrush Shrubland and Steppe) should get VEG_CODE 1.

**Comment by bangen** [comment]
Tagging people who are currently working on projects and need to be aware of this.  Feel free to tag anyone who was left out @sshahverdian @wally-mac @Albonicomt @MatthewMeier @joewheaton

**Comment by bangen** [comment]
@mhallerud 

Here are the EVT Landfire veg codes for the developed - vegetated classes

**Comment by wally-mac** [comment]
Sara,

Can you please provide a hyperlink to the data?  Thanks!

**Comment by bangen** [comment]
@wally-mac This issue post was pertinent to all EVT veg codes.  Just wanted Maggie to have it on her radar.  If you want I can send a link to the TNC BRAT Landfire data.

**Comment by wally-mac** [comment]
Got it. Thanks
