### ISSUE TITLE
Running the Project Builder with a layer package on the map seems to crash the tool

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#81]
I attempted to run the Project Builder while having a layer package in the table of contents of the map. Unfortunately, I kept running into the error pictured below.

![projecterror](https://user-images.githubusercontent.com/21353496/41121682-6434dc4e-6a56-11e8-97bd-222096d226c0.PNG)

Eventually, I tried removing the layer package that was in the Table of Contents for my map. After that, I didn't have any problems. I think it was a problem with the tool trying to make a layer that was already named in the layer package, but I'm not sure.

I don't think this bug is worth tracking down and fixing. I just want to have this page to document the problem I had with the tool, so that people having problems can be directed here to see a possible solution. I'll add a try catch block to suggest this fix, but otherwise, this bug is a low priority.

**Comment by banderson1618** [comment]
@Albonicomt, can you email me a zip file with the whole project in it? It'd help me see if there's something funky with how your project folders were generated. My guess is the Conservation Restoration input was somewhere that it wasn't supposed to be, but I can't say for sure just from the error message.

**Comment by Albonicomt** [comment]
I was trying it for the MiddleBear @banderson1618. Here is the folder on Box: https://usu.box.com/s/bmm4nfh2yk1aklxr48f734xrv41br6c8

**Comment by banderson1618** [comment]
The layer package generator assumes that the input is in the new folder structure (changes were discussed in Issue #45), so it breaks if you try to run it in the old structure. You could try to revise the structure to fit in with the new folder structure, but it's probably easier to just make it from scratch, to be honest. Sorry that I don't have an easy answer for you, man.

**Comment by Albonicomt** [comment]
Oh ok, no worres @banderson1618. I will remember that for next time. Thanks!

**Comment by wally-mac** [comment]
@banderson1618, can this be closed?

**Comment by banderson1618** [comment]
This is an active issue that hasn't been fixed. The post here is meant to serve as documentation for future users who run into this error. Because it hasn't been fixed, I think it's best to leave it open, so that future users don't get the impression that this has been fixed.

**Comment by joewheaton** [comment]
That's fine... Instead of this being the 'documentation', lets start a known-bugs page on the website for things we  can provide guidance as to work around and then refer back to these issues.
