### ISSUE TITLE
Braid Handler Not Assigning Correct DA

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#83]
@banderson1618 please check out [this video](https://youtu.be/cIZV2gH9B9s)

From what I can gather the braid handler tool isn't assigning the correct DA value.  It appears to be assigning the max DA value for the entire cluster, regardless of whether the user has gone in and changed the 'IsBraided' field to '0' for several of the polylines.

**Comment by banderson1618** [comment]
Changes are pushed, let me know if it works.

**Comment by bangen** [comment]
It's working.  Thanks for the fix.
