### ISSUE TITLE
BRAT Table tool sometimes crashes ArcGIS when adding iPC attributes

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#86]
Every once in a while, when running the BRAT Table tool, ArcGIS crashes. It's fairly rare, but persistant. I've done my best to identify the cause. The only common link that I've found is that when it crashes, a file in the "Temp" folder has four lock files for some reason. Something strange is going on with that, but I can't identify what.

Logging off and logging back in is a doable workaround, even if it's not ideal. I don't know how to fix it (I've already spent hours trying to identify the cause), but I'm putting up this issue to document that this problem is known, and that we're probably putting it on the backburner for the time being.

**Comment by wally-mac** [comment]
@banderson1618  is this still a bug? If so is it version dependent?

**Comment by wally-mac** [comment]
@banderson1618 can this be closed?

**Comment by banderson1618** [comment]
This is an active issue that hasn't been fixed. The post here is meant to serve as documentation for future users who run into this error. Because it hasn't been fixed, I think it's best to leave it open, so that future users don't get the impression that this has been fixed.

**Comment by joewheaton** [comment]
@banderson1618 this seemed really version specific? Can you make sure by 3.2 we get this either:
a) fixed; or 
b) CLEAR documentation page (e.g. in a Known Bugs section)  that links back to this issue.
