### ISSUE TITLE
Please scope time...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#88]
@bangen and @banderson1618 can you please both go to the https://github.com/Riverscapes/pyBRAT/projects/8#card-10085733 pyBRAT Development Project and drag all the issues in the 'Not Scoped' list to the appropriate list based on how long you think they would take. Also, maybe flag up who is capable of doing them between you two in some comments. Then @wally-mac and I can assign them to individuals and tie them to milestones. We also may move them to the 'Shelved' tasks: https://github.com/Riverscapes/pyBRAT/projects/2.

**Comment by banderson1618** [comment]
I scoped the projects that I knew enough about to scope when you first made this issue. I just now scoped two issues that have been made since then, because your post here reminded me to do that.

**Comment by joewheaton** [comment]
Thanks Braden!
_____________________
Dr. Joseph M. Wheaton
435-554-1247 (direct) | http://www.joewheaton.org

**Comment by wally-mac** [comment]
@bangen , is there scoping needed, that you are aware of?  Thanks!
