### ISSUE TITLE
TNC BRAT Project Valley Width Thresholds for VBET

### ISSUE THREAD

**Issue by bangen** [Riverscapes/pyBRAT#92]
@Albonicomt we're getting ready to batch process the TNC BRAT project basins, but before doing so need to figure out the VBET [valley width buffer sizes parameters](http://rcat.riverscapes.xyz/Documentation/Version_1.0/VBET) for each basin.  @wally-mac said you have experience doing this and are prob ready to be lined out with a new task.  We'd also like you to train @kbartelt up on this later next week so she can help out.

I put together a google spreadsheet that I'll share with you.  This is what we should use to store/track values for each basin in the project area.  

There's a shapefile of all the HUC8 basins in the project area named 'WBDHU8_ProjectArea.shp' on Box [here](https://usu.box.com/s/qsgnxjfmejzgvsfqjianvwzive4lqp2g).  If you also want to see/use the NHD flowlines for the individual basins they're in the 'NHD' subfolder for each HUC8 basin folder [here](https://usu.box.com/s/xkz7tu7gtpizz3r0s83v8f8vd0qctd5u).  Let me know if you need any other data.

Holler with any questions.  Thanks!

**Comment by kbartelt** [comment]
@Albonicomt I sent you an email with my contact info. Thanks!
