### ISSUE TITLE
BDWS breaks the entire tool if you don't have OSGeo installed

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/pyBRAT#93]
While testing what dependencies were necessary to run pyBRAT, I realized that the BDWS tool will not allow the user to use any aspect of pyBRAT if the user doesn't have OSGeo installed (specifically, gdal and ogr). The toolbox will have a little red X on it, and won't allow any scripts to be run. The way I see it, we have three options on how to address this:

1. Simply expect that the user has OSGeo dependencies. We will have to update the documentation for dependencies at the page [here](http://brat.riverscapes.xyz/Download/ComputerSetup.html) to include a tutorial on installing those tools. This would be the simplest option, but it would also put the most work on the user's plate, for a tool that many users probably won't touch. Personally, I don't think this is a great option.

2. Refactor BDWS to remove OSGeo dependencies, possibly with arcpy alternatives. This would be a significant undertaking. I would be surprised if we could do it in less than a week. Conceivably, it could be up to a month of work, and would probably introduce changes in behavior and new bugs. Because of the work involved, I don't see this as a worthwhile option.

3. Put BDWS in its own toolbox. This would allow a user to use the rest of pyBRAT without issue, while also giving them access to it if they want it. Personally, I lean towards this option. It wouldn't be very difficult to implement, but it would give access to BDWS to users that want it.

@bangen, @MatthewMeier, @wally-mac, @joewheaton, let me know what you think. If you think something about my analysis is wrong, or if I've overlooked an option, it'd be good to hear.

**Comment by bangen** [comment]
Option 2 would require a substantial amount of work and we don't currently have the budget.   That leaves either option 1 or 3.  We already require pyBRAT users to install dependencies (see [here](http://brat.riverscapes.xyz/Download/ComputerSetup)).  Given that I'm not that concerned about them having to install a few more packages.  

I think @joewheaton should make the call on this one.  Thoughts?

**Comment by banderson1618** [comment]
I moved BDWS code to the development branch that I just made, so this won't be an issue for people downloading the latest code.

**Comment by banderson1618** [comment]
@joewheaton and @wally-mac, do you have any input on this? I don't think Sara and I have the confidence to make this decision without the input of the guys in charge, and it would be good to get this resolved.

**Comment by wally-mac** [comment]
I think option 3 is the best option.

Put BDWS in its own toolbox. This would allow a user to use the rest of pyBRAT without issue, while also giving them access to it if they want it. Personally, I lean towards this option. It wouldn't be very difficult to implement, but it would give access to BDWS to users that want it.
