### ISSUE TITLE
Provisional BRAT Runs Requested for Scott and other California Visits

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#97]
Joe has a meeting on July 12-13 with TNC and Scott River Watershed Council folks. 

I absolutely need provisional runs (no manual editing, just straight outputs from uncalibrated national inputs... i.e. like we did for Sagehen Meeting):
- [x] Scott Watershed (HUC: 18010208)
- [x] Salmon (HUC: 18010210)

It is not critical, but it would be really nice (as I will be visiting these areas) to also have (in order of priority):
1.  [x] Tomales-Drake Bays (HUC 18050005) - _Addition to scope (gives me Occidental and Marin)_
2.  [x] San Pablo Bay (HUC 18050002) - _Addition to scope (gives me Napa, Martinez)_
3.  [ ] Russian River (HUC 18010110) - _Already in scope_
4.  [ ] Upper Coon-Upper Auburn (18020161)- _Addition to scope (gives me one of our NFWS partner's project sites in foothills)_

[KMZ of CA HUCs](https://drive.google.com/open?id=1zwMu9c475Sp0R7OGsnaiUCPtejzH1LgY)

In response to @bangen clarification:

> Hey Joe,
> 
> You requested adding on Napa, Sonoma, and Marin.  From a HUC8 standpoint that would be San Pablo Bay, Tomales-Drakes Bay and possibly Gualalal-Salmon.  Can you take a look at the attached kmzs and makes sure that's correct.  The 'CA_HUC8Basins' kmz is all of California while the other is the project area (not including the tack on basins).
> 
> Thanks,
> Sara
> 

Actually, substitute Gualala Salmon with Russian River. There are a handfull of North Coast watersheds that we don't have in scope right now, and thats fine:
- Gualala - Salmon (18010109)
- Mattole (18010107)
- Chetco (17100312)

**Comment by kbartelt** [comment]
@joewheaton @bangen Sounds good. I am still going through my initial test run of Lake Tahoe (hoping to finish within the next couple hours) and then will begin running these in the order listed above. I will reach out here with questions.

**Comment by kbartelt** [comment]
I have a couple questions regarding the VBET portion for these provisional BRAT runs.

- which NHD Flowline shapefile input should I use for the NHD Network Builder tool? NHDFlowline, NHD_24k_Perennial, or NHD_24k_300mReaches?

- Should I remove artificial paths/aqueducts/intermittent/ephemeral streams/ etc during this step?


For my initial VBET run of Scott I used NHD_24k_300mReaches, did not remove any of the listed optional components, and did not do any manual editing of the valley bottom output.

**Comment by joewheaton** [comment]
@bangen and @wally-mac may have a different take, but I feel like we should be running VBET on the entire NHD that we run BRAT on (i.e. NHD 1:24K). I DON'T personally like that we've removed artificial paths, aqueducts, intermittent and ephemeral in this step. I think it means our valley bottoms look fragmented. I understand why we have done this in the past (i.e. to minimize post-processing and manual editing), but in this case we should just run the whole thing and then we have it. Now it may be worth thinking of some compromises to my suggestion. For example:
- Maybe run both what I'm suggesting and perennial only for contrast? Don't edit either by default.
- Maybe attribute valley bottoms so they are assigned a VB type based on FCODE? This may be helpful for later fan stuff.

Anyhow, let me know what I'm missing, but I don't see why we don't just run the bigger area. 

I can see cartographically only showing perennial or showing perennial as green and rest as light green or brown. It does make sense to me that we still apply 'conflict' models to entire valley bottom....

**Comment by bangen** [comment]
@kbartelt you should run VBET for the entire network.  In the case of the TNC project, the network input into VBET should be the 'NHD_24k_300mReaches.shp'.  The networks are named the same for each HUC8 in the project and can be found in the 'NHD' folder.

@joewheaton for the TNC project I've been running VBET for the entire network (but with pipelines and underground conduits removed).  If techs haven't been doing this for the Idaho projects (and other projects) we all need to get on the same page.

As far as attributing the valley bottoms by FCODE, I'm not sure how this would be possible given that the valley bottom polygon output by VBET is dissolved (see screenshot below for Truckee).

![capture](https://user-images.githubusercontent.com/6502954/42339118-e48b2ace-8040-11e8-86d9-96124fb1a44d.PNG)

**Comment by bangen** [comment]
@kbartelt let's not bother editing the valley bottom output.  @joewheaton do you agree or do you want Karen to make some manual edits?

**Comment by bangen** [comment]
@kbartelt once you have the Salmon up to the point your have the Scott, could you please start working on the Tomales-Drake Bays and San Pablo Bay basins?  Since these were out of the scope of the original project, you'll need to gather some of the inputs.  

I already created the project folders and populated the NHD data (since I had the NHD data for the entire state).  The folders are up on Box.  

You'll need to gather:

- DEM
- Landfire BPS and EVT
- Roads
- Railroads

**Important:**
- All the above will need to be projected into the coordinate system we're using for the project which is 'NAD 1983 California (Teale) Albers (Meters)'.  When projecting in Arc it can be found under Projected Coordinate System-->State Systems
- Please follow the folder structure and file naming conventions we're using for the other basins in the TNC BRAT project.  You can look at any of the other HUC8 folders in the project folder as an example.

See [this page](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/1-InputData.html) which provides info on where to get the data (again, you don't need to worry about the drainage network).  You can use the 'WBDHU8.shp' (i.e., the HUC8 watershed boundary) in the NHD folder to hone in on the areas you need to download the data for.

Once you've downloaded the data, you'll need to create some additional fields for the Landfire BPS and EVT rasters ([see this page](http://brat.riverscapes.xyz/Documentation/Tutorials/StepByStep/2-Preprocessing.html)).  Also see issue #80 to see how we code the developed vegetated Landire classes.

Holler with questions.

**Comment by kbartelt** [comment]
@bangen @joewheaton Thank you for the clarification. I ran VBET for the entire network and will not do any editing unless further instructed to.

@bangen Yes, I'll get started on Tomales-Drake Bays and San Pablo Bay once Salmon is up to the point Scott is at per your instructions above!

**Comment by kbartelt** [comment]
@bangen here is an update of where i'm at- Scott and Salmon are at the ihyd/ regression equation step, and I'm currently going through the is braided/is mainstem ID process for Tamales-Drake Bays.  Thanks!

**Comment by kbartelt** [comment]
@wally-mac Thank you. I finished running Scott and Salmon and uploaded the files to box. Tomorrow I hopefully will be able to run Tamales-Drake Bays, San Pablo Bay, and potentially Russian River but will likely need some help/ clarification with the ihyd equations.

**Comment by kbartelt** [comment]
I finished a provisional run of Scott and Salmon.

Scott: https://usu.box.com/s/n35s3aeytd6jqchjo5fe354bo8gu736u
Salmon: https://usu.box.com/s/3e3zxvx6r7htgq8upu4hjk1z7qz8wmon

**Comment by joewheaton** [comment]
Thanks a ton @kbartelt for all your efforts. I'm downloading right now and will let you know if I have any issues.

**Comment by kbartelt** [comment]
I uploaded a provisional run to Box for the two watersheds below:

Tomales-Drake Bays (HUC 18050005): https://usu.box.com/s/uvwshiupku6zm76e7yqfzhffdts5xyff
 San Pablo Bay (HUC 18050002): https://usu.box.com/s/ayoojqgfz5sd771ds50s1yhgylilil91

**Comment by kbartelt** [comment]
@joewheaton there are new complete layer packages for Scott and Salmon that should work on 10.4 located on box.

Scott: https://usu.box.com/s/116yymh78p7yxzdlihj4bzytvjp5knmv
Salmon: https://usu.box.com/s/16ghhr2577wqd6azmj8hx3k62kgzzbmp

I will add the same 10_4 layer packages for the Tamales Drake Bays and San Pablo Bay first thing tomorrow.

**Comment by joewheaton** [comment]
Thanks a ton for these @kbartelt! Nice work busting those out under a tight time frame.
